package mireille.core;

import net.minecraft.block.*;
import mireille.common.blocks.*;
import mireille.common.blocks.BlockWorkbench;

public class ModBlocks
{
    public static Block CreonitOre;
    public static Block Stone;
    public static Block Stone1;
    public static Block Stonebrick;
    public static Block Wood;
    public static Block Iron;
    public static Block Wood_2_Slab;
    public static Block Wood_3_Slab;
    public static Block Wood_4_Slab;
    public static Block Wood_5_Slab;
    public static Block Stone_0_Slab;
    public static Block Stone_1_Slab;
    public static Block Stone_2_Slab;
    public static Block Stone_3_Slab;
    public static Block Stone_4_Slab;
    public static Block Stone_5_Slab;
    public static Block Stone_6_Slab;
    public static Block Stone_7_Slab;
    public static Block Stonebrick_0_Slab;
    public static Block Stonebrick_1_Slab;
    public static Block Stonebrick_2_Slab;
    public static Block Stonebrick_3_Slab;
    public static Block Stonebrick_4_Slab;
    public static Block Stonebrick_5_Slab;
    public static Block Stonebrick_6_Slab;
    public static Block Stonebrick_7_Slab;
    public static Block Stonebrick_8_Slab;
    public static Block Stonebrick_9_Slab;
    public static Block Wood_2_Stair;
    public static Block Wood_3_Stair;
    public static Block Wood_4_Stair;
    public static Block Wood_5_Stair;
    public static Block Stone_0_Stair;
    public static Block Stone_1_Stair;
    public static Block Stone_2_Stair;
    public static Block Stone_3_Stair;
    public static Block Stone_4_Stair;
    public static Block Stone_5_Stair;
    public static Block Stone_6_Stair;
    public static Block Stone_7_Stair;
    public static Block Stonebrick_0_Stair;
    public static Block Stonebrick_1_Stair;
    public static Block Stonebrick_2_Stair;
    public static Block Stonebrick_3_Stair;
    public static Block Stonebrick_4_Stair;
    public static Block Stonebrick_5_Stair;
    public static Block Stonebrick_6_Stair;
    public static Block Stonebrick_7_Stair;
    public static Block Stonebrick_8_Stair;
    public static Block Stonebrick_9_Stair;
    public static Block Stonebrick_10_Stair;
    public static Block Stonebrick_11_Stair;
    public static Block Stonebrick_12_Stair;
    public static Block Wood_Wall;
    public static Block Stone_Wall;
    public static Block Stonebrick_Wall;
    public static Block Wood_2_Fence;
    public static Block Wood_3_Fence;
    public static Block Wood_4_Fence;
    public static Block Stone_0_Fence;
    public static Block Stone_1_Fence;
    public static Block Stone_2_Fence;
    public static Block Stone_3_Fence;
    public static Block Stone_4_Fence;
    public static Block Stonebrick_0_Fence;
    public static Block Stonebrick_1_Fence;
    public static Block Stonebrick_2_Fence;
    public static Block Stonebrick_3_Fence;
    public static Block Stonebrick_4_Fence;
    public static Block Stonebrick_5_Fence;
    public static Block Stonebrick_6_Fence;
    public static Block Stonebrick_7_Fence;
    public static Block Stonebrick_8_Fence;
    public static Block Stonebrick_9_Fence;
    public static Block Lamp;
    public static Block Ladder1;
    public static Block Ladder2;
    public static Block Ladder3;
    public static Block Cloth1;
    public static Block Cloth2;
    public static Block Cloth3;
    public static Block Rope;
    public static Block Grass;
    public static Block Log;
    public static Block Log1;
    public static Block Rail1;
    public static Block Rail2;
    public static Block Rail3;
    public static Block Rail4;
    public static Block Box;
    public static Block Torch1;
    public static Block Torch2;
    public static Block Torch3;
    public static Block Torch4;
    public static Block Torch5;
    public static Block Barrier;
    public static Block MagmaFlow;
    public static Block MagmaStill;
    public static Block Web;
    public static Block Fire;
    public static Block Port;
    public static Block Port2;
    public static Block Port3;
    public static Block Dirt;
    public static Block Gravel;
    public static Block GrassBlock;
    public static Block frame;
    public static Block frameAnim;
    public static BlockWorkbench Workbench;
    public static BlockSkinWorkbench SkinWorkbench;
    
    public static void registerBlocks() {
        ModBlocks.CreonitOre = new BlocksOre("CreonitOre", "mireille:creonit_ore");
        ModBlocks.SkinWorkbench = new BlockSkinWorkbench("SkinWorkbench");
        ModBlocks.Workbench = new BlockWorkbench("table", "mireille:work");
        ModBlocks.Stone = new BlocksStone("Stone", "mireille:stone/stone", 16);
        ModBlocks.Stone1 = new BlocksStone("Stone1", "mireille:stone2/stone", 4);
        ModBlocks.Stonebrick = new BlocksStone("Stonebrick", "mireille:stonebrick/stonebrick", 16);
        ModBlocks.Wood = new BlocksWood("Wood", "mireille:wood/wood", 14);
        ModBlocks.Iron = new BlocksIron("Iron", "mireille:iron/iron", 12);
        ModBlocks.Wood_2_Slab = (Block)new SlabsWood("Wood_Slab", "mireille:wood/wood_2");
        ModBlocks.Wood_3_Slab = (Block)new SlabsWood("Wood_3_Slab", "mireille:wood/wood_3");
        ModBlocks.Wood_4_Slab = (Block)new SlabsWood("Wood_4_Slab", "mireille:wood/wood_4");
        ModBlocks.Wood_5_Slab = (Block)new SlabsWood("Wood_5_Slab", "mireille:wood/wood_11");
        ModBlocks.Stone_0_Slab = (Block)new SlabsStone("Stone_0_Slab", "mireille:stone/stone_0");
        ModBlocks.Stone_1_Slab = (Block)new SlabsStone("Stone_1_Slab", "mireille:stone/stone_1");
        ModBlocks.Stone_2_Slab = (Block)new SlabsStone("Stone_2_Slab", "mireille:stone/stone_2");
        ModBlocks.Stone_3_Slab = (Block)new SlabsStone("Stone_3_Slab", "mireille:stone/stone_3");
        ModBlocks.Stone_4_Slab = (Block)new SlabsStone("Stone_4_Slab", "mireille:stone/stone_4");
        ModBlocks.Stone_5_Slab = (Block)new SlabsStone("Stone_5_Slab", "mireille:stone/stone_12");
        ModBlocks.Stone_6_Slab = (Block)new SlabsStone("Stone_6_Slab", "mireille:stone/stone_5");
        ModBlocks.Stone_7_Slab = (Block)new SlabsStone("Stone_7_Slab", "mireille:stone/stone_9");
        ModBlocks.Stonebrick_0_Slab = (Block)new SlabsStone("Stonebrick_0_Slab", "mireille:stonebrick/stonebrick_0");
        ModBlocks.Stonebrick_1_Slab = (Block)new SlabsStone("Stonebrick_1_Slab", "mireille:stonebrick/stonebrick_1");
        ModBlocks.Stonebrick_2_Slab = (Block)new SlabsStone("Stonebrick_2_Slab", "mireille:stonebrick/stonebrick_2");
        ModBlocks.Stonebrick_3_Slab = (Block)new SlabsStone("Stonebrick_3_Slab", "mireille:stonebrick/stonebrick_3");
        ModBlocks.Stonebrick_4_Slab = (Block)new SlabsStone("Stonebrick_4_Slab", "mireille:stonebrick/stonebrick_4");
        ModBlocks.Stonebrick_5_Slab = (Block)new SlabsStone("Stonebrick_5_Slab", "mireille:stonebrick/stonebrick_5");
        ModBlocks.Stonebrick_6_Slab = (Block)new SlabsStone("Stonebrick_6_Slab", "mireille:stonebrick/stonebrick_6");
        ModBlocks.Stonebrick_7_Slab = (Block)new SlabsStone("Stonebrick_7_Slab", "mireille:stonebrick/stonebrick_7");
        ModBlocks.Stonebrick_8_Slab = (Block)new SlabsStone("Stonebrick_8_Slab", "mireille:stonebrick/stonebrick_8");
        ModBlocks.Stonebrick_9_Slab = (Block)new SlabsStone("Stonebrick_9_Slab", "mireille:stonebrick/stonebrick_9");
        ModBlocks.Wood_2_Stair = (Block)new StairsWood("Wood_2_Stair", ModBlocks.Wood, 2);
        ModBlocks.Wood_3_Stair = (Block)new StairsWood("Wood_3_Stair", ModBlocks.Wood, 3);
        ModBlocks.Wood_4_Stair = (Block)new StairsWood("Wood_4_Stair", ModBlocks.Wood, 4);
        ModBlocks.Wood_5_Stair = (Block)new StairsWood("Wood_5_Stair", ModBlocks.Wood, 11);
        ModBlocks.Stone_0_Stair = (Block)new StairsStone("Stone_0_Stair", ModBlocks.Stone, 0);
        ModBlocks.Stone_1_Stair = (Block)new StairsStone("Stone_1_Stair", ModBlocks.Stone, 1);
        ModBlocks.Stone_2_Stair = (Block)new StairsStone("Stone_2_Stair", ModBlocks.Stone, 2);
        ModBlocks.Stone_3_Stair = (Block)new StairsStone("Stone_3_Stair", ModBlocks.Stone, 3);
        ModBlocks.Stone_4_Stair = (Block)new StairsStone("Stone_4_Stair", ModBlocks.Stone, 9);
        ModBlocks.Stone_5_Stair = (Block)new StairsStone("Stone_5_Stair", ModBlocks.Stone, 10);
        ModBlocks.Stone_6_Stair = (Block)new StairsStone("Stone_6_Stair", ModBlocks.Stone, 11);
        ModBlocks.Stone_7_Stair = (Block)new StairsStone("Stone_7_Stair", ModBlocks.Stone, 12);
        ModBlocks.Stonebrick_0_Stair = (Block)new StairsStone("Stonebrick_0_Stair", ModBlocks.Stonebrick, 0);
        ModBlocks.Stonebrick_1_Stair = (Block)new StairsStone("Stonebrick_1_Stair", ModBlocks.Stonebrick, 1);
        ModBlocks.Stonebrick_2_Stair = (Block)new StairsStone("Stonebrick_2_Stair", ModBlocks.Stonebrick, 2);
        ModBlocks.Stonebrick_3_Stair = (Block)new StairsStone("Stonebrick_3_Stair", ModBlocks.Stonebrick, 3);
        ModBlocks.Stonebrick_4_Stair = (Block)new StairsStone("Stonebrick_4_Stair", ModBlocks.Stonebrick, 4);
        ModBlocks.Stonebrick_5_Stair = (Block)new StairsStone("Stonebrick_5_Stair", ModBlocks.Stonebrick, 5);
        ModBlocks.Stonebrick_6_Stair = (Block)new StairsStone("Stonebrick_6_Stair", ModBlocks.Stonebrick, 6);
        ModBlocks.Stonebrick_7_Stair = (Block)new StairsStone("Stonebrick_7_Stair", ModBlocks.Stonebrick, 7);
        ModBlocks.Stonebrick_8_Stair = (Block)new StairsStone("Stonebrick_8_Stair", ModBlocks.Stonebrick, 8);
        ModBlocks.Stonebrick_9_Stair = (Block)new StairsStone("Stonebrick_9_Stair", ModBlocks.Stonebrick, 9);
        ModBlocks.Stonebrick_10_Stair = (Block)new StairsStone("Stonebrick_10_Stair", ModBlocks.Stonebrick, 13);
        ModBlocks.Stonebrick_11_Stair = (Block)new StairsStone("Stonebrick_11_Stair", ModBlocks.Stonebrick, 14);
        ModBlocks.Stonebrick_12_Stair = (Block)new StairsStone("Stonebrick_12_Stair", ModBlocks.Stonebrick, 15);
        ModBlocks.Wood_Wall = (Block)new WallsWood("Wood_Wall", "mireille:wood/wood", 11);
        ModBlocks.Stone_Wall = (Block)new WallsStone("Stone_Wall", "mireille:stone/stone", 13);
        ModBlocks.Stonebrick_Wall = (Block)new WallsStone("Stonebrick_Wall", "mireille:stonebrick/stonebrick", 12);
        ModBlocks.Wood_2_Fence = (Block)new FencesWood("Wood_Fence", "mireille:wood/wood_2");
        ModBlocks.Wood_3_Fence = (Block)new FencesWood("Wood_3_Fence", "mireille:wood/wood_3");
        ModBlocks.Wood_4_Fence = (Block)new FencesWood("Wood_4_Fence", "mireille:wood/wood_4");
        ModBlocks.Stone_0_Fence = (Block)new FencesStone("Stone_0_Fence", "mireille:stone/stone_0");
        ModBlocks.Stone_1_Fence = (Block)new FencesStone("Stone_1_Fence", "mireille:stone/stone_1");
        ModBlocks.Stone_2_Fence = (Block)new FencesStone("Stone_2_Fence", "mireille:stone/stone_2");
        ModBlocks.Stone_3_Fence = (Block)new FencesStone("Stone_3_Fence", "mireille:stone/stone_3");
        ModBlocks.Stone_4_Fence = (Block)new FencesStone("Stone_4_Fence", "mireille:stone/stone_12");
        ModBlocks.Stonebrick_0_Fence = (Block)new FencesStone("Stonebrick_0_Fence", "mireille:stonebrick/stonebrick_0");
        ModBlocks.Stonebrick_1_Fence = (Block)new FencesStone("Stonebrick_1_Fence", "mireille:stonebrick/stonebrick_1");
        ModBlocks.Stonebrick_2_Fence = (Block)new FencesStone("Stonebrick_2_Fence", "mireille:stonebrick/stonebrick_2");
        ModBlocks.Stonebrick_3_Fence = (Block)new FencesStone("Stonebrick_3_Fence", "mireille:stonebrick/stonebrick_3");
        ModBlocks.Stonebrick_4_Fence = (Block)new FencesStone("Stonebrick_4_Fence", "mireille:stonebrick/stonebrick_4");
        ModBlocks.Stonebrick_5_Fence = (Block)new FencesStone("Stonebrick_5_Fence", "mireille:stonebrick/stonebrick_5");
        ModBlocks.Stonebrick_6_Fence = (Block)new FencesStone("Stonebrick_6_Fence", "mireille:stonebrick/stonebrick_6");
        ModBlocks.Stonebrick_7_Fence = (Block)new FencesStone("Stonebrick_7_Fence", "mireille:stonebrick/stonebrick_7");
        ModBlocks.Stonebrick_8_Fence = (Block)new FencesStone("Stonebrick_8_Fence", "mireille:stonebrick/stonebrick_8");
        ModBlocks.Stonebrick_9_Fence = (Block)new FencesStone("Stonebrick_9_Fence", "mireille:stonebrick/stonebrick_9");
        ModBlocks.Lamp = new BlocksLamp("Lamp", "mireille:lamp/lamp", 7);
        ModBlocks.Ladder1 = (Block)new BlocksLadder("Ladder1", "mireille:ladder/ladder_0");
        ModBlocks.Ladder2 = (Block)new BlocksLadder("Ladder2", "mireille:ladder/ladder_1");
        ModBlocks.Ladder3 = (Block)new BlocksLadder("Ladder3", "mireille:ladder/ladder_2");
        ModBlocks.Cloth1 = (Block)new BlocksCloth("Cloth1", "mireille:cloth/cloth_0");
        ModBlocks.Cloth2 = (Block)new BlocksCloth("Cloth2", "mireille:cloth/cloth_1");
        ModBlocks.Cloth3 = (Block)new BlocksCloth("Cloth3", "mireille:cloth/cloth_2");
        ModBlocks.Rope = new BlocksRope("Rope", "mireille:rope/rope", 13);
        ModBlocks.Grass = new BlocksGrass("Grass", "mireille:grass/grass", 4);
        ModBlocks.Rail1 = (Block)new BlocksRail("Rail1", "mireille:rail/rail_0");
        ModBlocks.Rail2 = (Block)new BlocksRail("Rail2", "mireille:rail/rail_1");
        ModBlocks.Rail3 = (Block)new BlocksRail("Rail3", "mireille:rail/rail_2");
        ModBlocks.Rail4 = (Block)new BlocksRail("Rail4", "mireille:rail/rail_3");
        ModBlocks.Log = (Block)new BlocksLog("Log", "mireille:log/log", 4);
        ModBlocks.Log1 = (Block)new BlocksLog("Log1", "mireille:log2/log", 4);
        ModBlocks.Box = new BlocksBox("Barrel", "mireille:box/box", 16);
        ModBlocks.Torch1 = (Block)new BlocksTorch("Torch1", "mireille:torch/torch_0");
        ModBlocks.Torch2 = (Block)new BlocksTorch("Torch2", "mireille:torch/torch_1");
        ModBlocks.Torch3 = (Block)new BlocksTorch("Torch3", "mireille:torch/torch_2");
        ModBlocks.Torch4 = (Block)new BlocksTorch("Torch4", "mireille:torch/torch_3");
        ModBlocks.Torch5 = (Block)new BlocksTorch("Torch5", "mireille:torch/torch_4");
        ModBlocks.Web = new BlocksWeb("Web", "mireille:web/web");
        ModBlocks.Fire = new BlocksFire("Fire", "mireille:fire/fire");
        ModBlocks.Barrier = new BlocksBarrier("Barrier");
        ModBlocks.MagmaFlow = (Block)new BlocksLavaFlow("MagmaFlow");
        ModBlocks.MagmaStill = (Block)new BlocksLavaStill("MagmaStill");
        ModBlocks.Port = new BlocksPortal("Port", "mireille:port/port", 9);
        ModBlocks.Port2 = new BlocksPortal("Port2", "mireille:port/port2", 9);
        ModBlocks.Port3 = new BlocksPortal("Port3", "mireille:port/port3", 9);
        ModBlocks.Dirt = new BlocksDirt("Dirt", "mireille:dirt/dirt", 3);
        ModBlocks.Gravel = new BlocksGravel("Gravel", "mireille:gravel/gravel", 3);
        ModBlocks.GrassBlock = new BlocksGrassBlocks("GrassB", "mireille:grassblock/grass", 2);
    }
    
    static {
        ModBlocks.frame = (Block)new BlockPicFrame("opFrame", false);
        ModBlocks.frameAnim = (Block)new BlockPicFrame("opFrameAnim", true);
    }
}
