package mireille.core;

import net.minecraft.item.*;
import net.minecraftforge.common.util.*;
import mireille.common.items.*;

public class ModItems
{
    public static final Item.ToolMaterial MYTHICAL;
    public static final Item.ToolMaterial PHANTOM;
    public static ItemArmor.ArmorMaterial DW_ARMOR;
    public static Item Bat;
    public static Item Hand;
    public static Item Akvamarin;
    public static Item Amethyst;
    public static Item Granat;
    public static Item Malahit;
    public static Item Tanzanit;
    public static Item Topaz;
    public static Item Map;
    public static Item Book1;
    public static Item Book2;
    public static Item Book3;
    public static Item Book4;
    public static Item Circuit1;
    public static Item Circuit2;
    public static Item Circuit3;
    public static Item Demonic_ruby;
    public static Item Dark_mox;
    public static Item Dark_spirit;
    public static Item Matter;
    public static Item SunMatter;
    public static Item VisMatter;
    public static Item FireMatter;
    public static Item LiveMatter;
    public static Item IceMatter;
    public static Item DarkMatter;
    public static Item RadioMatter;
    public static Item Outline;
    public static Item QuantumCore;
    public static Item Cpu1;
    public static Item Cpu2;
    public static Item Dark_eye;
    public static Item Demonic_eye;
    public static Item Ender_eye;
    public static Item Mana_crystal1;
    public static Item Mana_crystal2;
    public static Item Ring;
    public static Item Quant_core;
    public static Item EnderBag;
    public static Item Loot_box_1;
    public static Item Loot_box_2;
    public static Item Loot_box_3;
    public static Item Loot_box_4;
    public static Item Flux_ingot;
    public static Item Flux_plate;
    public static Item Flux_plate2;
    public static Item Enderium_plate;
    public static Item Enderium_plate2;
    public static Item Iridium_ingot;
    public static Item Hard_glass;
    public static Item Quant_most;
    public static Item Nitroglicerin;
    public static Item Sostav;
    public static Item Powder1;
    public static Item Powder2;
    public static Item Powder3;
    public static Item Powder4;
    public static Item Powder5;
    public static Item Powder6;
    public static Item Powder7;
    public static Item Powder8;
    public static Item Powder9;
    public static Item Powder10;
    public static Item Powder11;
    public static Item Powder12;
    public static Item Powder13;
    public static Item Powder14;
    public static Item Alpha;
    public static Item Vis_dust;
    public static Item Fire_dust;
    public static Item Sky_dust;
    public static Item Live_dust;
    public static Item Dark_dust;
    public static Item IridPlast;
    public static Item Thoryi;
    public static Item Deytoriy;
    public static Item DragonShard;
    public static Item ImperialSymbol;
    public static Item Iris;
    public static Item Chupa;
    public static Item Shoco;
    public static Item Sweet_Bug;
    public static Item Halloween_Scarf;
    public static Item PAxe;
    public static Item FullThaum;
    public static Item MythicalSword;
    public static Item PhantomSword;
    public static Item MythicalPrint;
    public static Item ImmortalPrint;
    public static Item DracDust;
    public static Item HaliteIngot;
    public static Item HaliteDust;
    public static Item HalitePlast;
    public static Item Dust1;
    public static Item Dust2;
    public static Item WyvernTablet;
    public static ItemDaedraArmor DaedraHead;
    public static ItemDaedraArmor DaedraChest;
    public static ItemDaedraArmor DaedraStanci;
    public static ItemDaedraArmor DaedraBoots;
    public static ItemDarknessArmor DarknessHead;
    public static ItemDarknessArmor DarknessChest;
    public static ItemDarknessArmor DarknessLegs;
    public static ItemDarknessArmor DarknessBoots;
    public static Item DaedraAkt;
    public static Item DarknessAkt;
    public static Item Aspects;
    public static Item TempWarp;
    public static Item PermWarp;
    public static Item NanoCore;
    public static Item DraconicShard;
    public static Item IcePlate;
    public static Item DarkPlate;
    public static Item LivePlate;
    public static Item VisPlate;
    public static Item SunPlate;
    public static Item HalitePlate;
    public static Item coupon;
    public static Item sweet1;
    public static Item sweet2;
    public static Item sweet3;
    public static Item UrlPaint;
    public static Item UrlPaintAnim;
    public static Item BloodIchor;
    public static Item BloodIchorIngot;
    public static Item BloodVenok;
    public static Item Rainbow;
    public static Item Meowmere;
    public static Item Smoke;
    public static Item Tron_disk1;
    public static Item Tron_disk2;
    public static Item Tron_disk3;
    public static Item Tron_disk4;
    public static Item Tron_disk5;
    public static Item Pure_crystal;
    public static Item Devil_stone;
    public static Item Creeper_dust;
    public static Item Fairy_wing;
    public static ItemArmor Tron_head_yellow;
    public static ItemArmor Tron_chest_yellow;
    public static ItemArmor Tron_leggs_yellow;
    public static ItemArmor Tron_boots_yellow;
    public static ItemArmor Tron_head_blue;
    public static ItemArmor Tron_chest_blue;
    public static ItemArmor Tron_leggs_blue;
    public static ItemArmor Tron_boots_blue;
    public static ItemArmor Tron_head_red;
    public static ItemArmor Tron_chest_red;
    public static ItemArmor Tron_leggs_red;
    public static ItemArmor Tron_boots_red;
    public static ItemArmor Tron_head_green;
    public static ItemArmor Tron_chest_green;
    public static ItemArmor Tron_leggs_green;
    public static ItemArmor Tron_boots_green;
    public static ItemArmor Tron_head_purple;
    public static ItemArmor Tron_chest_purple;
    public static ItemArmor Tron_leggs_purple;
    public static ItemArmor Tron_boots_purple;
    public static ItemArmor CrystalArmorHead;
    public static ItemArmor CrystalArmorChest;
    public static ItemArmor CrystalArmorLegs;
    public static ItemArmor CrystalArmorBoots;
    public static ItemArmor DevilArmorHead;
    public static ItemArmor DevilArmorChest;
    public static ItemArmor DevilArmorLegs;
    public static ItemArmor DevilArmorBoots;
    public static ItemArmor CreepArmorHead;
    public static ItemArmor CreepArmorChest;
    public static ItemArmor CreepArmorLegs;
    public static ItemArmor CreepArmorBoots;
    public static ItemArmor FairyArmorHead;
    public static ItemArmor FairyArmorChest;
    public static ItemArmor FairyArmorLegs;
    public static ItemArmor FairyArmorBoots;
    public static ItemStack[] AllSkins;
    public static Item Crescent_rose_skin;
    public static Item Tenjiry_skin;
    public static Item Shinju_skin;
    public static Item ShikamaDodji_skin;
    public static Item VampireKiss_skin;
    public static Item Moon_light_skin;
    public static Item Vis_molot_skin;
    public static Item Sun_molot_skin;
    public static Item Ice_molot_skin;
    public static Item Live_molot_skin;
    public static Item Dark_molot_skin;
    public static Item CreonitCrystal;
    
    public static void registerItems() {
        ModItems.CreonitCrystal = new Items("CreonitCrystals", "mireille:creonit_crystals", 64);
        ModItems.Crescent_rose_skin = (Item)new ItemSkin("Crescent_rose_skin");
        ModItems.Tenjiry_skin = (Item)new ItemSkin("Tenjiry_skin");
        ModItems.Shinju_skin = (Item)new ItemSkin("Shinju_skin");
        ModItems.ShikamaDodji_skin = (Item)new ItemSkin("ShikamaDodji_skin");
        ModItems.VampireKiss_skin = (Item)new ItemSkin("VampireKiss_skin");
        ModItems.Vis_molot_skin = (Item)new ItemSkin("Vis_molot_skin");
        ModItems.Sun_molot_skin = (Item)new ItemSkin("Sun_molot_skin");
        ModItems.Ice_molot_skin = (Item)new ItemSkin("Ice_molot_skin");
        ModItems.Live_molot_skin = (Item)new ItemSkin("Live_molot_skin");
        ModItems.Dark_molot_skin = (Item)new ItemSkin("Dark_molot_skin");
        ModItems.Moon_light_skin = (Item)new ItemSkin("Moon_light_skin");
        ModItems.AllSkins[1] = new ItemStack(ModItems.Crescent_rose_skin);
        ModItems.AllSkins[2] = new ItemStack(ModItems.Tenjiry_skin);
        ModItems.AllSkins[3] = new ItemStack(ModItems.Shinju_skin);
        ModItems.AllSkins[4] = new ItemStack(ModItems.ShikamaDodji_skin);
        ModItems.AllSkins[5] = new ItemStack(ModItems.VampireKiss_skin);
        ModItems.AllSkins[6] = new ItemStack(ModItems.Vis_molot_skin);
        ModItems.AllSkins[7] = new ItemStack(ModItems.Sun_molot_skin);
        ModItems.AllSkins[8] = new ItemStack(ModItems.Ice_molot_skin);
        ModItems.AllSkins[9] = new ItemStack(ModItems.Live_molot_skin);
        ModItems.AllSkins[10] = new ItemStack(ModItems.Dark_molot_skin);
        ModItems.AllSkins[11] = new ItemStack(ModItems.Moon_light_skin);
        ModItems.Meowmere = (Item)new ItemMeowmere("Meowmere", "mireille:meowmere");
        ModItems.BloodVenok = new Items("BloodVenok", "mireille:venok_blood", 1);
        ModItems.BloodIchorIngot = new Items("BloodIchorIngot", "mireille:blood_ichor_ingot", 64);
        ModItems.BloodIchor = new Items("BloodIchor", "mireille:blood_ichor", 64);
        ModItems.sweet1 = new Items("sweet1", "mireille:sweet1", 64);
        ModItems.sweet2 = new Items("sweet2", "mireille:sweet2", 64);
        ModItems.sweet3 = new Items("sweet3", "mireille:sweet3", 64);
        ModItems.coupon = new Items("coupon", "mireille:coupon", 64);
        ModItems.DaedraAkt = new ItemCase("ChestDaedra", "mireille:DaedraAkt", ModCases.DaedraHeart, true, "daedra", 10);
        ModItems.DarknessAkt = new ItemCase("DarknessAkt", "mireille:DarknessAkt", ModCases.DarkStone, true, "dark", 10);
        ModItems.DaedraHead = new ItemDaedraArmor("Head", "", ItemArmor.ArmorMaterial.DIAMOND, 0);
        ModItems.DaedraChest = new ItemDaedraArmor("Chest", "", ItemArmor.ArmorMaterial.DIAMOND, 1);
        ModItems.DaedraStanci = new ItemDaedraArmor("Stanci", "", ItemArmor.ArmorMaterial.DIAMOND, 2);
        ModItems.DaedraBoots = new ItemDaedraArmor("Boots", "", ItemArmor.ArmorMaterial.DIAMOND, 3);
        ModItems.DarknessHead = new ItemDarknessArmor("DarknessHead", "", ItemArmor.ArmorMaterial.DIAMOND, 0);
        ModItems.DarknessChest = new ItemDarknessArmor("DarknessChest", "", ItemArmor.ArmorMaterial.DIAMOND, 1);
        ModItems.DarknessLegs = new ItemDarknessArmor("DarknessLegs", "", ItemArmor.ArmorMaterial.DIAMOND, 2);
        ModItems.DarknessBoots = new ItemDarknessArmor("DarknessBoots", "", ItemArmor.ArmorMaterial.DIAMOND, 3);
        ModItems.Bat = new Items("Bat", "mireille:bat", 64);
        ModItems.Hand = new Items("Hand", "mireille:hand", 64);
        ModItems.Granat = new Items("Granat", "mireille:granat", 64);
        ModItems.Tanzanit = new Items("Tanzanit", "mireille:tanzanit", 64);
        ModItems.Topaz = new Items("Topaz", "mireille:topaz", 64);
        ModItems.Malahit = new Items("Malahit", "mireille:malahit", 64);
        ModItems.Akvamarin = new Items("Akvamarin", "mireille:akvamarin", 64);
        ModItems.Amethyst = new Items("Amethyst", "mireille:amethyst", 64);
        ModItems.Map = new Items("Map", "mireille:map", 64);
        ModItems.Book1 = new Items("Book1", "mireille:book1", 64);
        ModItems.Book2 = new Items("Book2", "mireille:book2", 64);
        ModItems.Book3 = new Items("Book3", "mireille:book3", 64);
        ModItems.Book4 = new Items("Book4", "mireille:book4", 64);
        ModItems.Circuit1 = new Items("Circuit1", "mireille:circuit1", 64);
        ModItems.Circuit2 = new Items("Circuit2", "mireille:circuit2", 64);
        ModItems.Circuit3 = new Items("Circuit3", "mireille:circuit3", 64);
        ModItems.Demonic_ruby = new Items("Demonic_ruby", "mireille:demonic_ruby", 64);
        ModItems.Dark_mox = new Items("Dark_mox", "mireille:dark_mox", 64);
        ModItems.Dark_spirit = new Items("Dark_spirit", "mireille:dark_spirit", 64);
        ModItems.Matter = new Items("Matter", "mireille:materia", 64);
        ModItems.SunMatter = new Items("SunMatter", "mireille:sun_materia", 64);
        ModItems.VisMatter = new Items("VisMatter", "mireille:vis_materia", 64);
        ModItems.FireMatter = new Items("FireMatter", "mireille:fire_materia", 64);
        ModItems.LiveMatter = new Items("LiveMatter", "mireille:live_materia", 64);
        ModItems.IceMatter = new Items("IceMatter", "mireille:sky_materia", 64);
        ModItems.DarkMatter = new Items("DarkMatter", "mireille:dark_materia", 64);
        ModItems.RadioMatter = new Items("RadioMatter", "mireille:rmatter", 64);
        ModItems.Outline = new Items("Outline", "mireille:outline", 64);
        ModItems.QuantumCore = new Items("QuantumCore", "mireille:realm_quantum", 64);
        ModItems.Cpu1 = new Items("Cpu1", "mireille:cpu1", 64);
        ModItems.Cpu2 = new Items("Cpu2", "mireille:cpu2", 64);
        ModItems.Dark_eye = new Items("Dark_eye", "mireille:dark_eye", 64);
        ModItems.Demonic_eye = new Items("Demonic_eye", "mireille:demonic_eye", 64);
        ModItems.Ender_eye = new Items("Ender_eye", "mireille:ender_eye", 64);
        ModItems.Mana_crystal1 = new Items("Mana_crystal1", "mireille:mana_crystal1", 64);
        ModItems.Mana_crystal2 = new Items("Mana_crystal2", "mireille:mana_crystal2", 64);
        ModItems.Ring = new Items("Ring", "mireille:ring", 1);
        ModItems.EnderBag = new EnderBag("EnderBag", "mireille:ender_box", 1);
        ModItems.Quant_core = new Items("Quant_core", "mireille:quant_core", 64);
        ModItems.Loot_box_1 = new Fortune("Loot_box_1", "mireille:loot_box_1", 1);
        ModItems.Loot_box_2 = new Items("Loot_box_2", "mireille:loot_box_2", 64);
        ModItems.Loot_box_3 = new Items("Loot_box_3", "mireille:loot_box_3", 64);
        ModItems.Loot_box_4 = new Items("Loot_box_4", "mireille:loot_box_4", 64);
        ModItems.Flux_ingot = new Items("Flux_ingot", "mireille:flux_ingot", 64);
        ModItems.Flux_plate = new Items("Flux_plate", "mireille:flux_plate", 64);
        ModItems.Flux_plate2 = new Items("Flux_plate2", "mireille:flux_plate2", 64);
        ModItems.Enderium_plate = new Items("Enderium_plate", "mireille:enderium_plate", 64);
        ModItems.Enderium_plate2 = new Items("Enderium_plate2", "mireille:enderium_plate2", 64);
        ModItems.Iridium_ingot = new Items("Iridium_ingot", "mireille:iridium_ingot", 64);
        ModItems.Hard_glass = new Items("Hard_glass", "mireille:hard_glass", 64);
        ModItems.Quant_most = new Items("Quant_most", "mireille:quant_most", 64);
        ModItems.Nitroglicerin = new Items("Nitroglicerin", "mireille:nitroglicerin", 64);
        ModItems.Sostav = new Items("Sostav", "mireille:sostav", 64);
        ModItems.Powder1 = new Items("Powder1", "mireille:powder1", 64);
        ModItems.Powder2 = new Items("Powder2", "mireille:powder2", 64);
        ModItems.Powder3 = new Items("Powder3", "mireille:powder3", 64);
        ModItems.Powder4 = new Items("Powder4", "mireille:powder4", 64);
        ModItems.Powder5 = new Items("Powder5", "mireille:powder5", 64);
        ModItems.Powder6 = new Items("Powder6", "mireille:powder6", 64);
        ModItems.Powder7 = new Items("Powder7", "mireille:powder7", 64);
        ModItems.Powder8 = new Items("Powder8", "mireille:powder8", 64);
        ModItems.Powder9 = new Items("Powder9", "mireille:powder9", 64);
        ModItems.Powder10 = new Items("Powder10", "mireille:powder10", 64);
        ModItems.Powder11 = new Items("Powder11", "mireille:powder11", 64);
        ModItems.Powder12 = new Items("Powder12", "mireille:powder12", 64);
        ModItems.Powder13 = new Items("Powder13", "mireille:powder13", 64);
        ModItems.Powder14 = new Items("Powder14", "mireille:powder14", 64);
        ModItems.Alpha = new Items("Alpha", "mireille:alpha", 64);
        ModItems.Vis_dust = new Items("Vis_dust", "mireille:dust_blaze_1", 64);
        ModItems.Fire_dust = new Items("Fire_dust", "mireille:dust_blaze_2", 64);
        ModItems.Sky_dust = new Items("Sky_dust", "mireille:dust_blaze_3", 64);
        ModItems.Live_dust = new Items("Live_dust", "mireille:dust_blaze_4", 64);
        ModItems.Dark_dust = new Items("Dark_dust", "mireille:dust_blaze_5", 64);
        ModItems.IridPlast = new Items("IridPlast", "mireille:IridPlast", 64);
        ModItems.Thoryi = new Items("Thoriy", "mireille:Thoriy", 64);
        ModItems.Deytoriy = new Items("Deytoriy", "mireille:Deytor", 64);
        ModItems.DragonShard = new Items("DragonShard", "mireille:Dragon", 64);
        ModItems.ImperialSymbol = new Items("ImperialSymbol", "mireille:ImpS", 64);
        ModItems.Iris = new Items("Iris", "mireille:iris", 64);
        ModItems.Chupa = new Items("Chupa", "mireille:chupa_chups", 64);
        ModItems.Shoco = new Items("Chocolate", "mireille:chocolate", 64);
        ModItems.Sweet_Bug = new Items("Sweet_Bug", "mireille:sweet_bag", 64);
        ModItems.Halloween_Scarf = new Items("Halloween_Scarf", "mireille:Halloween_Scarf", 64);
        ModItems.PAxe = (Item)new ItemsSword("PAxe", "mireille:PAxe");
        ModItems.FullThaum = new ThaumFull("FullThaum", "mireille:thaumfull", 1);
        ModItems.Aspects = new Aspects("Aspects", "mireille:aspects", 64);
        ModItems.PermWarp = new PermWarp("PermWarp", "mireille:PermWarp", 1);
        ModItems.TempWarp = new TempWarp("TempWarp", "mireille:TempWarp", 64);
        ModItems.PhantomSword = (Item)new PhantomSword("PhantomSword", "mireille:sword/Phantom");
        ModItems.MythicalSword = (Item)new MythicalSword("MythicalSword", "mireille:sword/Mythical");
        ModItems.MythicalPrint = new Items("MythicalPrint", "mireille:Mythicalprint", 64);
        ModItems.ImmortalPrint = new Items("ImmortalPrint", "mireille:Immortalprint", 64);
        ModItems.DracDust = new Items("DracDust", "mireille:DracDust", 64);
        ModItems.HaliteDust = new Items("HaliteDust", "mireille:halitedust", 64);
        ModItems.HaliteIngot = new Items("HaliteIngot", "mireille:haliteing", 64);
        ModItems.HalitePlast = new Items("HalitePlast", "mireille:haliteplast", 64);
        ModItems.Dust1 = new Items("Dust1", "mireille:dust1", 64);
        ModItems.Dust2 = new Items("Dust2", "mireille:dust2", 64);
        ModItems.WyvernTablet = new Items("WyvernTablet", "mireille:wyverntablet", 64);
        ModItems.NanoCore = new Items("NanoCore", "mireille:nano_core", 64);
        ModItems.DraconicShard = new Items("DraconicShard", "mireille:dragon_shard", 64);
        ModItems.VisPlate = new Items("VisPlate", "mireille:vis_plate", 64);
        ModItems.SunPlate = new Items("SunPlate", "mireille:sun_plate", 64);
        ModItems.LivePlate = new Items("LivePlate", "mireille:live_plate", 64);
        ModItems.IcePlate = new Items("IcePlate", "mireille:ice_plate", 64);
        ModItems.DarkPlate = new Items("DarkPlate", "mireille:dark_plate", 64);
        ModItems.HalitePlate = new Items("HalitePlate", "mireille:halit_plate2", 64);
        ModItems.Smoke = (Item)new ItemSmoke("Smoke", "mireille:smoke");
        ModItems.Tron_disk1 = new ItemCase("Tron_disk1", "mireille:tron_disk1", ModCases.Tron_disk1, true, "tron_yellow", 11);
        ModItems.Tron_disk2 = new ItemCase("Tron_disk2", "mireille:tron_disk2", ModCases.Tron_disk2, true, "tron_blue", 11);
        ModItems.Tron_disk3 = new ItemCase("Tron_disk3", "mireille:tron_disk3", ModCases.Tron_disk3, true, "tron_red", 11);
        ModItems.Tron_disk4 = new ItemCase("Tron_disk4", "mireille:tron_disk4", ModCases.Tron_disk4, true, "tron_green", 11);
        ModItems.Tron_disk5 = new ItemCase("Tron_disk5", "mireille:tron_disk5", ModCases.Tron_disk5, true, "tron_purple", 11);
        ModItems.Pure_crystal = new ItemCase("Pure_crystal", "mireille:pure_crystal", ModCases.Pure_crystal, true, "crystal", 10);
        ModItems.Devil_stone = new ItemCase("Devil_stone", "mireille:devil_stone", ModCases.Devil_stone, true, "devil", 10);
        ModItems.Creeper_dust = new ItemCase("Creeper_dust", "mireille:creeper_dust", ModCases.Creeper_dust, true, "creep", 10);
        ModItems.Fairy_wing = new ItemCase("Fairy_wing", "mireille:fairy_wing", ModCases.Fairy_wing, true, "fairy", 10);
        ModItems.Tron_head_yellow = new ItemVoxelArmor(ModItems.DW_ARMOR, 0, "Tron_head_yellow", "tron_yellow", 2, 5);
        ModItems.Tron_chest_yellow = new ItemVoxelArmor(ModItems.DW_ARMOR, 1, "Tron_chest_yellow", "tron_yellow", 2, 5);
        ModItems.Tron_leggs_yellow = new ItemVoxelArmor(ModItems.DW_ARMOR, 2, "Tron_leggs_yellow", "tron_yellow", 2, 5);
        ModItems.Tron_boots_yellow = new ItemVoxelArmor(ModItems.DW_ARMOR, 3, "Tron_boots_yellow", "tron_yellow", 2, 5);
        ModItems.Tron_head_blue = new ItemVoxelArmor(ModItems.DW_ARMOR, 0, "Tron_head_blue", "tron_blue", 2, 5);
        ModItems.Tron_chest_blue = new ItemVoxelArmor(ModItems.DW_ARMOR, 1, "Tron_chest_blue", "tron_blue", 2, 5);
        ModItems.Tron_leggs_blue = new ItemVoxelArmor(ModItems.DW_ARMOR, 2, "Tron_leggs_blue", "tron_blue", 2, 5);
        ModItems.Tron_boots_blue = new ItemVoxelArmor(ModItems.DW_ARMOR, 3, "Tron_boots_blue", "tron_blue", 2, 5);
        ModItems.Tron_head_red = new ItemVoxelArmor(ModItems.DW_ARMOR, 0, "Tron_head_red", "tron_red", 2, 5);
        ModItems.Tron_chest_red = new ItemVoxelArmor(ModItems.DW_ARMOR, 1, "Tron_chest_red", "tron_red", 2, 5);
        ModItems.Tron_leggs_red = new ItemVoxelArmor(ModItems.DW_ARMOR, 2, "Tron_leggs_red", "tron_red", 2, 5);
        ModItems.Tron_boots_red = new ItemVoxelArmor(ModItems.DW_ARMOR, 3, "Tron_boots_red", "tron_red", 2, 5);
        ModItems.Tron_head_green = new ItemVoxelArmor(ModItems.DW_ARMOR, 0, "Tron_head_green", "tron_green", 2, 5);
        ModItems.Tron_chest_green = new ItemVoxelArmor(ModItems.DW_ARMOR, 1, "Tron_chest_green", "tron_green", 2, 5);
        ModItems.Tron_leggs_green = new ItemVoxelArmor(ModItems.DW_ARMOR, 2, "Tron_leggs_green", "tron_green", 2, 5);
        ModItems.Tron_boots_green = new ItemVoxelArmor(ModItems.DW_ARMOR, 3, "Tron_boots_green", "tron_green", 2, 5);
        ModItems.Tron_head_purple = new ItemVoxelArmor(ModItems.DW_ARMOR, 0, "Tron_head_purple", "tron_purple", 2, 5);
        ModItems.Tron_chest_purple = new ItemVoxelArmor(ModItems.DW_ARMOR, 1, "Tron_chest_purple", "tron_purple", 2, 5);
        ModItems.Tron_leggs_purple = new ItemVoxelArmor(ModItems.DW_ARMOR, 2, "Tron_leggs_purple", "tron_purple", 2, 5);
        ModItems.Tron_boots_purple = new ItemVoxelArmor(ModItems.DW_ARMOR, 3, "Tron_boots_purple", "tron_purple", 2, 5);
        ModItems.CrystalArmorHead = new ItemVoxelArmor(ModItems.DW_ARMOR, 0, "CrystalArmorHead", "crystal", 2, 4);
        ModItems.CrystalArmorChest = new ItemVoxelArmor(ModItems.DW_ARMOR, 1, "CrystalArmorChest", "crystal", 2, 4);
        ModItems.CrystalArmorLegs = new ItemVoxelArmor(ModItems.DW_ARMOR, 2, "CrystalArmorLegs", "crystal", 2, 4);
        ModItems.CrystalArmorBoots = new ItemVoxelArmor(ModItems.DW_ARMOR, 3, "CrystalArmorBoots", "crystal", 2, 4);
        ModItems.DevilArmorHead = new ItemVoxelArmor(ModItems.DW_ARMOR, 0, "DevilArmorHead", "devil", 2, 4);
        ModItems.DevilArmorChest = new ItemVoxelArmor(ModItems.DW_ARMOR, 1, "DevilArmorChest", "devil", 2, 4);
        ModItems.DevilArmorLegs = new ItemVoxelArmor(ModItems.DW_ARMOR, 2, "DevilArmorLegs", "devil", 2, 4);
        ModItems.DevilArmorBoots = new ItemVoxelArmor(ModItems.DW_ARMOR, 3, "DevilArmorBoots", "devil", 2, 4);
        ModItems.CreepArmorHead = new ItemVoxelArmor(ModItems.DW_ARMOR, 0, "CreepArmorHead", "creep", 2, 4);
        ModItems.CreepArmorChest = new ItemVoxelArmor(ModItems.DW_ARMOR, 1, "CreepArmorChest", "creep", 2, 4);
        ModItems.CreepArmorLegs = new ItemVoxelArmor(ModItems.DW_ARMOR, 2, "CreepArmorLegs", "creep", 2, 4);
        ModItems.CreepArmorBoots = new ItemVoxelArmor(ModItems.DW_ARMOR, 3, "CreepArmorBoots", "creep", 2, 4);
        ModItems.FairyArmorHead = new ItemVoxelArmor(ModItems.DW_ARMOR, 0, "FairyArmorHead", "fairy", 2, 4);
        ModItems.FairyArmorChest = new ItemVoxelArmor(ModItems.DW_ARMOR, 1, "FairyArmorChest", "fairy", 2, 4);
        ModItems.FairyArmorLegs = new ItemVoxelArmor(ModItems.DW_ARMOR, 2, "FairyArmorLegs", "fairy", 2, 4);
        ModItems.FairyArmorBoots = new ItemVoxelArmor(ModItems.DW_ARMOR, 3, "FairyArmorBoots", "fairy", 2, 4);
    }
    
    static {
        MYTHICAL = EnumHelper.addToolMaterial("MYTHICAL", 0, 10000, 0.0f, 75.0f, 50);
        PHANTOM = EnumHelper.addToolMaterial("PHANTOM", 0, 10000, 0.0f, 44.0f, 50);
        ModItems.DW_ARMOR = EnumHelper.addArmorMaterial("STMIND_ARMOR", -1, new int[] { 3, 8, 6, 3 }, 30);
        ModItems.AllSkins = new ItemStack[12];
        ModItems.UrlPaint = (Item)new ItemReedSt(ModBlocks.frame, "UrlPaint", "mireille:url_paint");
        ModItems.UrlPaintAnim = (Item)new ItemReedSt(ModBlocks.frameAnim, "UrlPaintAnim", "mireille:url_paint_anim");
        ModItems.Rainbow = new Items("Rainbow", "mireille:rainbow", 1);
    }
}
