/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.MathHelper
 */
package net.divinerpg.client.render.entity.twilight.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelEnchantedArcher
extends ModelBase {
    ModelRenderer head;
    ModelRenderer body1;
    ModelRenderer rightarmext;
    ModelRenderer leftfoot;
    ModelRenderer bodymain;
    ModelRenderer body2;
    ModelRenderer body3;
    ModelRenderer body4;
    ModelRenderer body6;
    ModelRenderer body5;
    public ModelRenderer rightarm;
    ModelRenderer rightarmcap;
    ModelRenderer leftarm;
    ModelRenderer leftarmext;
    ModelRenderer leftarmcap;
    ModelRenderer leftleg;
    ModelRenderer leftlegcap;
    ModelRenderer rightfoot;
    ModelRenderer rightleg;
    ModelRenderer rightlegcap;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;

    public ModelEnchantedArcher() {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.head = new ModelRenderer((ModelBase)this, 0, 0);
        this.head.addBox(-4.0f, -8.0f, -4.0f, 8, 8, 8);
        this.head.setRotationPoint(0.0f, -16.0f, -19.0f);
        this.head.setTextureSize(64, 32);
        this.head.mirror = true;
        this.setRotation(this.head, 0.0f, 0.0f, 0.0f);
        this.body1 = new ModelRenderer((ModelBase)this, 0, 22);
        this.body1.addBox(-4.0f, 0.0f, -2.0f, 8, 6, 4);
        this.body1.setRotationPoint(0.0f, -12.0f, -2.0f);
        this.body1.setTextureSize(64, 32);
        this.body1.mirror = true;
        this.setRotation(this.body1, 0.2617994f, 0.0f, 0.0f);
        this.rightarmext = new ModelRenderer((ModelBase)this, 40, 10);
        this.rightarmext.addBox(-7.0f, -2.0f, -2.0f, 8, 4, 4);
        this.rightarmext.setRotationPoint(-5.0f, -16.0f, -6.0f);
        this.rightarmext.setTextureSize(64, 32);
        this.rightarmext.mirror = true;
        this.setRotation(this.rightarmext, 0.0f, 0.0f, 0.0f);
        this.leftfoot = new ModelRenderer((ModelBase)this, 28, 15);
        this.leftfoot.addBox(-3.0f, 17.0f, -9.0f, 6, 5, 12);
        this.leftfoot.setRotationPoint(10.0f, 2.0f, 0.0f);
        this.leftfoot.setTextureSize(64, 32);
        this.leftfoot.mirror = true;
        this.setRotation(this.leftfoot, 0.0f, 0.0f, 0.0f);
        this.bodymain = new ModelRenderer((ModelBase)this, 28, 10);
        this.bodymain.addBox(-4.0f, 0.0f, -2.0f, 14, 18, 4);
        this.bodymain.setRotationPoint(-3.0f, -6.0f, 0.0f);
        this.bodymain.setTextureSize(64, 32);
        this.bodymain.mirror = true;
        this.setRotation(this.bodymain, 0.0f, 0.0f, 0.0f);
        this.body2 = new ModelRenderer((ModelBase)this, 0, 22);
        this.body2.addBox(-4.0f, 0.0f, -2.0f, 8, 6, 4);
        this.body2.setRotationPoint(0.0f, -21.0f, -14.0f);
        this.body2.setTextureSize(64, 32);
        this.body2.mirror = true;
        this.setRotation(this.body2, 1.308997f, 0.0f, 0.0f);
        this.body3 = new ModelRenderer((ModelBase)this, 16, 16);
        this.body3.addBox(-4.0f, 0.0f, -2.0f, 4, 3, 4);
        this.body3.setRotationPoint(2.0f, -21.0f, -16.0f);
        this.body3.setTextureSize(64, 32);
        this.body3.mirror = true;
        this.setRotation(this.body3, 1.570796f, 0.0f, 0.0f);
        this.body4 = new ModelRenderer((ModelBase)this, 0, 22);
        this.body4.addBox(-4.0f, 0.0f, -2.0f, 4, 3, 4);
        this.body4.setRotationPoint(2.0f, -14.0f, -3.0f);
        this.body4.setTextureSize(64, 32);
        this.body4.mirror = true;
        this.setRotation(this.body4, 0.5235988f, 0.0f, 0.0f);
        this.body6 = new ModelRenderer((ModelBase)this, 0, 22);
        this.body6.addBox(-4.0f, 0.0f, -2.0f, 8, 6, 4);
        this.body6.setRotationPoint(0.0f, -18.0f, -7.0f);
        this.body6.setTextureSize(64, 32);
        this.body6.mirror = true;
        this.setRotation(this.body6, 0.7853982f, 0.0f, 0.0f);
        this.body5 = new ModelRenderer((ModelBase)this, 0, 22);
        this.body5.addBox(-4.0f, 0.0f, -2.0f, 4, 3, 4);
        this.body5.setRotationPoint(2.0f, -19.0f, -9.0f);
        this.body5.setTextureSize(64, 32);
        this.body5.mirror = true;
        this.setRotation(this.body5, 1.047198f, 0.0f, 0.0f);
        this.rightarm = new ModelRenderer((ModelBase)this, 40, 10);
        this.rightarm.addBox(-11.0f, -2.0f, -2.0f, 4, 18, 4);
        this.rightarm.setRotationPoint(-5.0f, -16.0f, -6.0f);
        this.rightarm.setTextureSize(64, 32);
        this.rightarm.mirror = true;
        this.setRotation(this.rightarm, 0.0f, 0.0f, 0.0f);
        this.rightarmcap = new ModelRenderer((ModelBase)this, 40, 10);
        this.rightarmcap.addBox(-12.0f, -3.0f, -3.0f, 6, 6, 6);
        this.rightarmcap.setRotationPoint(-5.0f, -16.0f, -6.0f);
        this.rightarmcap.setTextureSize(64, 32);
        this.rightarmcap.mirror = true;
        this.setRotation(this.rightarmcap, 0.0f, 0.0f, 0.0f);
        this.leftarm = new ModelRenderer((ModelBase)this, 40, 10);
        this.leftarm.addBox(7.0f, -2.0f, -2.0f, 4, 18, 4);
        this.leftarm.setRotationPoint(5.0f, -16.0f, -6.0f);
        this.leftarm.setTextureSize(64, 32);
        this.leftarm.mirror = true;
        this.setRotation(this.leftarm, 0.0f, 0.0f, 0.0f);
        this.leftarmext = new ModelRenderer((ModelBase)this, 40, 10);
        this.leftarmext.addBox(-1.0f, -2.0f, -2.0f, 8, 4, 4);
        this.leftarmext.setRotationPoint(5.0f, -16.0f, -6.0f);
        this.leftarmext.setTextureSize(64, 32);
        this.leftarmext.mirror = true;
        this.setRotation(this.leftarmext, 0.0f, 0.0f, 0.0f);
        this.leftarmcap = new ModelRenderer((ModelBase)this, 40, 10);
        this.leftarmcap.addBox(6.0f, -3.0f, -3.0f, 6, 6, 6);
        this.leftarmcap.setRotationPoint(5.0f, -16.0f, -6.0f);
        this.leftarmcap.setTextureSize(64, 32);
        this.leftarmcap.mirror = true;
        this.setRotation(this.leftarmcap, 0.0f, 0.0f, 0.0f);
        this.leftleg = new ModelRenderer((ModelBase)this, 37, 6);
        this.leftleg.addBox(-2.0f, 0.0f, -2.0f, 4, 22, 4);
        this.leftleg.setRotationPoint(10.0f, 2.0f, 0.0f);
        this.leftleg.setTextureSize(64, 32);
        this.leftleg.mirror = true;
        this.setRotation(this.leftleg, 0.0f, 0.0f, 0.0f);
        this.leftlegcap = new ModelRenderer((ModelBase)this, 37, 6);
        this.leftlegcap.addBox(-3.0f, -2.0f, -3.0f, 6, 5, 6);
        this.leftlegcap.setRotationPoint(10.0f, 2.0f, 0.0f);
        this.leftlegcap.setTextureSize(64, 32);
        this.leftlegcap.mirror = true;
        this.setRotation(this.leftlegcap, 0.0f, 0.0f, 0.0f);
        this.rightfoot = new ModelRenderer((ModelBase)this, 28, 15);
        this.rightfoot.addBox(-3.0f, 17.0f, -9.0f, 6, 5, 12);
        this.rightfoot.setRotationPoint(-10.0f, 2.0f, 0.0f);
        this.rightfoot.setTextureSize(64, 32);
        this.rightfoot.mirror = true;
        this.setRotation(this.rightfoot, 0.0f, 0.0f, 0.0f);
        this.rightleg = new ModelRenderer((ModelBase)this, 37, 6);
        this.rightleg.addBox(-2.0f, 0.0f, -2.0f, 4, 22, 4);
        this.rightleg.setRotationPoint(-10.0f, 2.0f, 0.0f);
        this.rightleg.setTextureSize(64, 32);
        this.rightleg.mirror = true;
        this.setRotation(this.rightleg, 0.0f, 0.0f, 0.0f);
        this.rightlegcap = new ModelRenderer((ModelBase)this, 37, 6);
        this.rightlegcap.addBox(-3.0f, -2.0f, -3.0f, 6, 5, 6);
        this.rightlegcap.setRotationPoint(-10.0f, 2.0f, 0.0f);
        this.rightlegcap.setTextureSize(64, 32);
        this.rightlegcap.mirror = true;
        this.setRotation(this.rightlegcap, 0.0f, 0.0f, 0.0f);
        this.Shape1 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape1.addBox(0.0f, 0.0f, 0.0f, 4, 9, 1);
        this.Shape1.setRotationPoint(-2.0f, -31.0f, -13.0f);
        this.Shape1.setTextureSize(64, 32);
        this.Shape1.mirror = true;
        this.setRotation(this.Shape1, 0.0f, 0.0f, 0.0f);
        this.Shape2 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape2.addBox(0.0f, 0.0f, 0.0f, 4, 9, 1);
        this.Shape2.setRotationPoint(-2.0f, -29.0f, -11.0f);
        this.Shape2.setTextureSize(64, 32);
        this.Shape2.mirror = true;
        this.setRotation(this.Shape2, 0.0f, 0.0f, 0.0f);
        this.Shape3 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape3.addBox(0.0f, 0.0f, 0.0f, 4, 9, 1);
        this.Shape3.setRotationPoint(-2.0f, -27.0f, -9.0f);
        this.Shape3.setTextureSize(64, 32);
        this.Shape3.mirror = true;
        this.setRotation(this.Shape3, 0.0f, 0.0f, 0.0f);
        this.Shape4 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape4.addBox(0.0f, 0.0f, 0.0f, 4, 9, 1);
        this.Shape4.setRotationPoint(-2.0f, -8.0f, 8.0f);
        this.Shape4.setTextureSize(64, 32);
        this.Shape4.mirror = true;
        this.setRotation(this.Shape4, -1.047198f, 0.0f, 0.0f);
        this.Shape5 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape5.addBox(0.0f, 0.0f, 0.0f, 4, 9, 1);
        this.Shape5.setRotationPoint(-2.0f, -5.0f, 10.0f);
        this.Shape5.setTextureSize(64, 32);
        this.Shape5.mirror = true;
        this.setRotation(this.Shape5, -1.308997f, 0.0f, 0.0f);
        this.Shape6 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape6.addBox(0.0f, 0.0f, 0.0f, 4, 9, 1);
        this.Shape6.setRotationPoint(-2.0f, -24.0f, -2.0f);
        this.Shape6.setTextureSize(64, 32);
        this.Shape6.mirror = true;
        this.setRotation(this.Shape6, -0.2617994f, 0.0f, 0.0f);
        this.Shape7 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape7.addBox(0.0f, 0.0f, 0.0f, 4, 9, 1);
        this.Shape7.setRotationPoint(-2.0f, -25.0f, -4.0f);
        this.Shape7.setTextureSize(64, 32);
        this.Shape7.mirror = true;
        this.setRotation(this.Shape7, -0.2617994f, 0.0f, 0.0f);
        this.Shape8 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape8.addBox(1.0f, 0.0f, 0.0f, 2, 9, 1);
        this.Shape8.setRotationPoint(-2.0f, -20.0f, 3.0f);
        this.Shape8.setTextureSize(64, 32);
        this.Shape8.mirror = true;
        this.setRotation(this.Shape8, -0.5235988f, 0.0f, 0.0f);
        this.Shape9 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape9.addBox(0.0f, 0.0f, 0.0f, 4, 9, 1);
        this.Shape9.setRotationPoint(-2.0f, -12.0f, 7.0f);
        this.Shape9.setTextureSize(64, 32);
        this.Shape9.mirror = true;
        this.setRotation(this.Shape9, -0.7853982f, 0.0f, 0.0f);
        this.Shape10 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape10.addBox(0.0f, 0.0f, 0.0f, 4, 9, 1);
        this.Shape10.setRotationPoint(-2.0f, -15.0f, 6.0f);
        this.Shape10.setTextureSize(64, 32);
        this.Shape10.mirror = true;
        this.setRotation(this.Shape10, -0.7853982f, 0.0f, 0.0f);
        this.Shape11 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape11.addBox(0.0f, 0.0f, 0.0f, 2, 9, 1);
        this.Shape11.setRotationPoint(-1.0f, -18.0f, 5.0f);
        this.Shape11.setTextureSize(64, 32);
        this.Shape11.mirror = true;
        this.setRotation(this.Shape11, -0.7853982f, 0.0f, 0.0f);
        this.Shape12 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape12.addBox(0.0f, 0.0f, 0.0f, 4, 9, 1);
        this.Shape12.setRotationPoint(-2.0f, 10.0f, 10.0f);
        this.Shape12.setTextureSize(64, 32);
        this.Shape12.mirror = true;
        this.setRotation(this.Shape12, -1.570796f, 0.0f, 0.0f);
        this.Shape13 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape13.addBox(0.0f, 0.0f, 0.0f, 4, 9, 1);
        this.Shape13.setRotationPoint(-2.0f, 8.0f, 10.0f);
        this.Shape13.setTextureSize(64, 32);
        this.Shape13.mirror = true;
        this.setRotation(this.Shape13, -1.570796f, 0.0f, 0.0f);
        this.Shape14 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape14.addBox(0.0f, 0.0f, 0.0f, 4, 9, 1);
        this.Shape14.setRotationPoint(-2.0f, 6.0f, 10.0f);
        this.Shape14.setTextureSize(64, 32);
        this.Shape14.mirror = true;
        this.setRotation(this.Shape14, -1.570796f, 0.0f, 0.0f);
        this.Shape15 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape15.addBox(0.0f, 0.0f, 0.0f, 4, 9, 1);
        this.Shape15.setRotationPoint(-2.0f, 4.0f, 10.0f);
        this.Shape15.setTextureSize(64, 32);
        this.Shape15.mirror = true;
        this.setRotation(this.Shape15, -1.570796f, 0.0f, 0.0f);
        this.Shape16 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape16.addBox(0.0f, 0.0f, 0.0f, 4, 9, 1);
        this.Shape16.setRotationPoint(-2.0f, 2.0f, 10.0f);
        this.Shape16.setTextureSize(64, 32);
        this.Shape16.mirror = true;
        this.setRotation(this.Shape16, -1.570796f, 0.0f, 0.0f);
        this.Shape17 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape17.addBox(0.0f, 0.0f, 0.0f, 4, 9, 1);
        this.Shape17.setRotationPoint(-2.0f, 0.0f, 10.0f);
        this.Shape17.setTextureSize(64, 32);
        this.Shape17.mirror = true;
        this.setRotation(this.Shape17, -1.570796f, 0.0f, 0.0f);
        this.Shape18 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape18.addBox(0.0f, 0.0f, 0.0f, 4, 9, 1);
        this.Shape18.setRotationPoint(-2.0f, -2.0f, 10.0f);
        this.Shape18.setTextureSize(64, 32);
        this.Shape18.mirror = true;
        this.setRotation(this.Shape18, -1.570796f, 0.0f, 0.0f);
        this.Shape19 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape19.addBox(1.0f, 0.0f, 0.0f, 2, 9, 1);
        this.Shape19.setRotationPoint(-2.0f, -26.0f, -6.0f);
        this.Shape19.setTextureSize(64, 32);
        this.Shape19.mirror = true;
        this.setRotation(this.Shape19, -0.2617994f, 0.0f, 0.0f);
        this.Shape20 = new ModelRenderer((ModelBase)this, 35, 14);
        this.Shape20.addBox(1.0f, 0.0f, 0.0f, 2, 9, 1);
        this.Shape20.setRotationPoint(-2.0f, -22.0f, 1.0f);
        this.Shape20.setTextureSize(64, 32);
        this.Shape20.mirror = true;
        this.setRotation(this.Shape20, -0.5235988f, 0.0f, 0.0f);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5);
        this.head.render(f5);
        this.body1.render(f5);
        this.rightarmext.render(f5);
        this.leftfoot.render(f5);
        this.bodymain.render(f5);
        this.body2.render(f5);
        this.body3.render(f5);
        this.body4.render(f5);
        this.body6.render(f5);
        this.body5.render(f5);
        this.rightarm.render(f5);
        this.rightarmcap.render(f5);
        this.leftarm.render(f5);
        this.leftarmext.render(f5);
        this.leftarmcap.render(f5);
        this.leftleg.render(f5);
        this.leftlegcap.render(f5);
        this.rightfoot.render(f5);
        this.rightleg.render(f5);
        this.rightlegcap.render(f5);
        this.Shape1.render(f5);
        this.Shape2.render(f5);
        this.Shape3.render(f5);
        this.Shape4.render(f5);
        this.Shape5.render(f5);
        this.Shape6.render(f5);
        this.Shape7.render(f5);
        this.Shape8.render(f5);
        this.Shape9.render(f5);
        this.Shape10.render(f5);
        this.Shape11.render(f5);
        this.Shape12.render(f5);
        this.Shape13.render(f5);
        this.Shape14.render(f5);
        this.Shape15.render(f5);
        this.Shape16.render(f5);
        this.Shape17.render(f5);
        this.Shape18.render(f5);
        this.Shape19.render(f5);
        this.Shape20.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float var1, float var2, float var3, float var4, float var5, float var6) {
        this.head.rotateAngleY = var4 / 57.295776f;
        this.head.rotateAngleX = var5 / 57.295776f;
        this.rightarm.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f + (float)Math.PI)) * 2.0f * var2 * 0.5f;
        this.rightarmcap.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f + (float)Math.PI)) * 2.0f * var2 * 0.5f;
        this.rightarmext.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f + (float)Math.PI)) * 2.0f * var2 * 0.5f;
        this.leftarm.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 2.0f * var2 * 0.5f;
        this.leftarmcap.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 2.0f * var2 * 0.5f;
        this.leftarmext.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 2.0f * var2 * 0.5f;
        this.rightarm.rotateAngleZ = 0.0f;
        this.rightarmcap.rotateAngleZ = 0.0f;
        this.rightarmext.rotateAngleZ = 0.0f;
        this.leftarm.rotateAngleZ = 0.0f;
        this.leftarmcap.rotateAngleZ = 0.0f;
        this.leftarmext.rotateAngleZ = 0.0f;
        this.rightleg.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.rightlegcap.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.rightfoot.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.leftleg.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.leftlegcap.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.leftfoot.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.rightleg.rotateAngleY = 0.0f;
        this.rightlegcap.rotateAngleY = 0.0f;
        this.rightfoot.rotateAngleY = 0.0f;
        this.leftleg.rotateAngleY = 0.0f;
        this.leftlegcap.rotateAngleY = 0.0f;
        this.leftfoot.rotateAngleY = 0.0f;
        this.rightarm.rotateAngleY = 0.0f;
        this.rightarmcap.rotateAngleY = 0.0f;
        this.rightarmext.rotateAngleY = 0.0f;
        this.leftarm.rotateAngleY = 0.0f;
        this.leftarmcap.rotateAngleY = 0.0f;
        this.leftarmext.rotateAngleY = 0.0f;
        this.rightarm.rotateAngleZ += MathHelper.cos((float)(var3 * 0.09f)) * 0.05f + 0.05f;
        this.rightarmcap.rotateAngleZ += MathHelper.cos((float)(var3 * 0.09f)) * 0.05f + 0.05f;
        this.rightarmext.rotateAngleZ += MathHelper.cos((float)(var3 * 0.09f)) * 0.05f + 0.05f;
        this.leftarm.rotateAngleZ -= MathHelper.cos((float)(var3 * 0.09f)) * 0.05f + 0.05f;
        this.leftarmcap.rotateAngleZ -= MathHelper.cos((float)(var3 * 0.09f)) * 0.05f + 0.05f;
        this.leftarmext.rotateAngleZ -= MathHelper.cos((float)(var3 * 0.09f)) * 0.05f + 0.05f;
        this.rightarm.rotateAngleX += MathHelper.sin((float)(var3 * 0.067f)) * 0.05f;
        this.rightarmcap.rotateAngleX += MathHelper.sin((float)(var3 * 0.067f)) * 0.05f;
        this.rightarmext.rotateAngleX += MathHelper.sin((float)(var3 * 0.067f)) * 0.05f;
        this.leftarm.rotateAngleX -= MathHelper.sin((float)(var3 * 0.067f)) * 0.05f;
        this.leftarmcap.rotateAngleX -= MathHelper.sin((float)(var3 * 0.067f)) * 0.05f;
        this.leftarmext.rotateAngleX -= MathHelper.sin((float)(var3 * 0.067f)) * 0.05f;
    }
}

