/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.MathHelper
 */
package net.divinerpg.client.render.entity.vanilla.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelEye
extends ModelBase {
    ModelRenderer ear1;
    ModelRenderer body1;
    ModelRenderer ext1;
    ModelRenderer body2;
    ModelRenderer body3;
    ModelRenderer body4;
    ModelRenderer leftbackfoot;
    ModelRenderer eye1;
    ModelRenderer cap1;
    ModelRenderer leftbackleg;
    ModelRenderer leftfrontfoot;
    ModelRenderer leftfrontleg;
    ModelRenderer eye2;
    ModelRenderer ext2;
    ModelRenderer cap2;
    ModelRenderer rightbackfoot;
    ModelRenderer rightbackleg;
    ModelRenderer ext3;
    ModelRenderer eye3;
    ModelRenderer cap3;
    ModelRenderer ext4;
    ModelRenderer cap4;
    ModelRenderer eye4;
    ModelRenderer rightfrontleg;
    ModelRenderer rightfrontfoot;
    ModelRenderer head;
    ModelRenderer ear2;
    ModelRenderer ear3;
    ModelRenderer ear4;

    public ModelEye() {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.ear1 = new ModelRenderer((ModelBase)this, 0, 22);
        this.ear1.addBox(4.0f, -4.0f, 6.0f, 1, 2, 7);
        this.ear1.setRotationPoint(0.0f, 1.0f, 0.0f);
        this.ear1.setTextureSize(64, 32);
        this.ear1.mirror = true;
        this.setRotation(this.ear1, 1.047198f, 0.0f, 0.0f);
        this.body1 = new ModelRenderer((ModelBase)this, 32, 12);
        this.body1.addBox(-4.0f, 0.0f, -2.0f, 8, 12, 8);
        this.body1.setRotationPoint(-4.0f, 0.0f, -6.0f);
        this.body1.setTextureSize(64, 32);
        this.body1.mirror = true;
        this.setRotation(this.body1, 0.0f, 0.0f, 0.0f);
        this.ext1 = new ModelRenderer((ModelBase)this, 24, 0);
        this.ext1.addBox(-2.0f, -2.0f, -2.0f, 4, 2, 8);
        this.ext1.setRotationPoint(10.0f, 12.0f, 9.0f);
        this.ext1.setTextureSize(64, 32);
        this.ext1.mirror = true;
        this.setRotation(this.ext1, 0.0f, 0.7853982f, 0.0f);
        this.body2 = new ModelRenderer((ModelBase)this, 32, 12);
        this.body2.addBox(-4.0f, 0.0f, -2.0f, 8, 12, 8);
        this.body2.setRotationPoint(-4.0f, 0.0f, 2.0f);
        this.body2.setTextureSize(64, 32);
        this.body2.mirror = true;
        this.setRotation(this.body2, 0.0f, 0.0f, 0.0f);
        this.body3 = new ModelRenderer((ModelBase)this, 32, 12);
        this.body3.addBox(-4.0f, 0.0f, -2.0f, 8, 12, 8);
        this.body3.setRotationPoint(4.0f, 0.0f, -6.0f);
        this.body3.setTextureSize(64, 32);
        this.body3.mirror = true;
        this.setRotation(this.body3, 0.0f, 0.0f, 0.0f);
        this.body4 = new ModelRenderer((ModelBase)this, 32, 12);
        this.body4.addBox(-4.0f, 0.0f, -2.0f, 8, 12, 8);
        this.body4.setRotationPoint(4.0f, 0.0f, 2.0f);
        this.body4.setTextureSize(64, 32);
        this.body4.mirror = true;
        this.setRotation(this.body4, 0.0f, 0.0f, 0.0f);
        this.leftbackfoot = new ModelRenderer((ModelBase)this, 0, 24);
        this.leftbackfoot.addBox(-3.0f, 10.0f, -3.0f, 6, 2, 6);
        this.leftbackfoot.setRotationPoint(14.0f, 12.0f, 13.0f);
        this.leftbackfoot.setTextureSize(64, 32);
        this.leftbackfoot.mirror = true;
        this.setRotation(this.leftbackfoot, 0.0f, 0.0f, 0.0f);
        this.eye1 = new ModelRenderer((ModelBase)this, 48, 0);
        this.eye1.addBox(0.0f, 0.0f, 0.0f, 4, 4, 4);
        this.eye1.setRotationPoint(12.0f, 8.0f, 11.0f);
        this.eye1.setTextureSize(64, 32);
        this.eye1.mirror = true;
        this.setRotation(this.eye1, 0.0f, 0.0f, 0.0f);
        this.cap1 = new ModelRenderer((ModelBase)this, 48, 0);
        this.cap1.addBox(0.0f, 0.0f, 0.0f, 4, 4, 4);
        this.cap1.setRotationPoint(7.0f, 8.0f, 6.0f);
        this.cap1.setTextureSize(64, 32);
        this.cap1.mirror = true;
        this.setRotation(this.cap1, 0.0f, 0.0f, 0.0f);
        this.leftbackleg = new ModelRenderer((ModelBase)this, 0, 16);
        this.leftbackleg.addBox(-2.0f, 0.0f, -2.0f, 4, 12, 4);
        this.leftbackleg.setRotationPoint(14.0f, 12.0f, 13.0f);
        this.leftbackleg.setTextureSize(64, 32);
        this.leftbackleg.mirror = true;
        this.setRotation(this.leftbackleg, 0.0f, 0.0f, 0.0f);
        this.leftfrontfoot = new ModelRenderer((ModelBase)this, 0, 24);
        this.leftfrontfoot.addBox(-3.0f, 10.0f, -3.0f, 6, 2, 6);
        this.leftfrontfoot.setRotationPoint(14.0f, 12.0f, -13.0f);
        this.leftfrontfoot.setTextureSize(64, 32);
        this.leftfrontfoot.mirror = true;
        this.setRotation(this.leftfrontfoot, 0.0f, 0.0f, 0.0f);
        this.leftfrontleg = new ModelRenderer((ModelBase)this, 0, 16);
        this.leftfrontleg.addBox(-2.0f, 0.0f, -2.0f, 4, 12, 4);
        this.leftfrontleg.setRotationPoint(14.0f, 12.0f, -13.0f);
        this.leftfrontleg.setTextureSize(64, 32);
        this.leftfrontleg.mirror = true;
        this.setRotation(this.leftfrontleg, 0.0f, 0.0f, 0.0f);
        this.eye2 = new ModelRenderer((ModelBase)this, 48, 0);
        this.eye2.addBox(0.0f, 0.0f, 0.0f, 4, 4, 4);
        this.eye2.setRotationPoint(12.0f, 8.0f, -15.0f);
        this.eye2.setTextureSize(64, 32);
        this.eye2.mirror = true;
        this.setRotation(this.eye2, 0.0f, 0.0f, 0.0f);
        this.ext2 = new ModelRenderer((ModelBase)this, 24, 0);
        this.ext2.addBox(-2.0f, -2.0f, -2.0f, 4, 2, 8);
        this.ext2.setRotationPoint(13.0f, 12.0f, -12.0f);
        this.ext2.setTextureSize(64, 32);
        this.ext2.mirror = true;
        this.setRotation(this.ext2, 0.0f, -0.7853982f, 0.0f);
        this.cap2 = new ModelRenderer((ModelBase)this, 48, 0);
        this.cap2.addBox(0.0f, 0.0f, 0.0f, 4, 4, 4);
        this.cap2.setRotationPoint(7.0f, 8.0f, -10.0f);
        this.cap2.setTextureSize(64, 32);
        this.cap2.mirror = true;
        this.setRotation(this.cap2, 0.0f, 0.0f, 0.0f);
        this.rightbackfoot = new ModelRenderer((ModelBase)this, 0, 24);
        this.rightbackfoot.addBox(-3.0f, 10.0f, -3.0f, 6, 2, 6);
        this.rightbackfoot.setRotationPoint(-13.0f, 12.0f, 13.0f);
        this.rightbackfoot.setTextureSize(64, 32);
        this.rightbackfoot.mirror = true;
        this.setRotation(this.rightbackfoot, 0.0f, 0.0f, 0.0f);
        this.rightbackleg = new ModelRenderer((ModelBase)this, 0, 16);
        this.rightbackleg.addBox(-2.0f, 0.0f, -2.0f, 4, 12, 4);
        this.rightbackleg.setRotationPoint(-13.0f, 12.0f, 13.0f);
        this.rightbackleg.setTextureSize(64, 32);
        this.rightbackleg.mirror = true;
        this.setRotation(this.rightbackleg, 0.0f, 0.0f, 0.0f);
        this.ext3 = new ModelRenderer((ModelBase)this, 24, 0);
        this.ext3.addBox(-2.0f, -2.0f, -2.0f, 4, 2, 8);
        this.ext3.setRotationPoint(-9.0f, 12.0f, 9.0f);
        this.ext3.setTextureSize(64, 32);
        this.ext3.mirror = true;
        this.setRotation(this.ext3, 0.0f, -0.7853982f, 0.0f);
        this.eye3 = new ModelRenderer((ModelBase)this, 48, 0);
        this.eye3.addBox(0.0f, 0.0f, 0.0f, 4, 4, 4);
        this.eye3.setRotationPoint(-15.0f, 8.0f, 11.0f);
        this.eye3.setTextureSize(64, 32);
        this.eye3.mirror = true;
        this.setRotation(this.eye3, 0.0f, 0.0f, 0.0f);
        this.cap3 = new ModelRenderer((ModelBase)this, 48, 0);
        this.cap3.addBox(0.0f, 0.0f, 0.0f, 4, 4, 4);
        this.cap3.setRotationPoint(-10.0f, 8.0f, 6.0f);
        this.cap3.setTextureSize(64, 32);
        this.cap3.mirror = true;
        this.setRotation(this.cap3, 0.0f, 0.0f, 0.0f);
        this.ext4 = new ModelRenderer((ModelBase)this, 24, 0);
        this.ext4.addBox(-2.0f, -2.0f, -2.0f, 4, 2, 8);
        this.ext4.setRotationPoint(-12.0f, 12.0f, -12.0f);
        this.ext4.setTextureSize(64, 32);
        this.ext4.mirror = true;
        this.setRotation(this.ext4, 0.0f, 0.7853982f, 0.0f);
        this.cap4 = new ModelRenderer((ModelBase)this, 48, 0);
        this.cap4.addBox(0.0f, 0.0f, 0.0f, 4, 4, 4);
        this.cap4.setRotationPoint(-10.0f, 8.0f, -10.0f);
        this.cap4.setTextureSize(64, 32);
        this.cap4.mirror = true;
        this.setRotation(this.cap4, 0.0f, 0.0f, 0.0f);
        this.eye4 = new ModelRenderer((ModelBase)this, 48, 0);
        this.eye4.addBox(0.0f, 0.0f, 0.0f, 4, 4, 4);
        this.eye4.setRotationPoint(-15.0f, 8.0f, -15.0f);
        this.eye4.setTextureSize(64, 32);
        this.eye4.mirror = true;
        this.setRotation(this.eye4, 0.0f, 0.0f, 0.0f);
        this.rightfrontleg = new ModelRenderer((ModelBase)this, 0, 16);
        this.rightfrontleg.addBox(-2.0f, 0.0f, -2.0f, 4, 12, 4);
        this.rightfrontleg.setRotationPoint(-13.0f, 12.0f, -13.0f);
        this.rightfrontleg.setTextureSize(64, 32);
        this.rightfrontleg.mirror = true;
        this.setRotation(this.rightfrontleg, 0.0f, 0.0f, 0.0f);
        this.rightfrontfoot = new ModelRenderer((ModelBase)this, 0, 24);
        this.rightfrontfoot.addBox(-3.0f, 10.0f, -3.0f, 6, 2, 6);
        this.rightfrontfoot.setRotationPoint(-13.0f, 12.0f, -13.0f);
        this.rightfrontfoot.setTextureSize(64, 32);
        this.rightfrontfoot.mirror = true;
        this.setRotation(this.rightfrontfoot, 0.0f, 0.0f, 0.0f);
        this.head = new ModelRenderer((ModelBase)this, 0, 0);
        this.head.addBox(-4.0f, -9.0f, -4.0f, 8, 8, 8);
        this.head.setRotationPoint(0.0f, 1.0f, 0.0f);
        this.head.setTextureSize(64, 32);
        this.head.mirror = true;
        this.setRotation(this.head, 0.0f, 0.0f, 0.0f);
        this.ear2 = new ModelRenderer((ModelBase)this, 0, 22);
        this.ear2.addBox(4.0f, -7.0f, 5.0f, 1, 2, 7);
        this.ear2.setRotationPoint(0.0f, 1.0f, 0.0f);
        this.ear2.setTextureSize(64, 32);
        this.ear2.mirror = true;
        this.setRotation(this.ear2, 1.047198f, 0.0f, 0.0f);
        this.ear3 = new ModelRenderer((ModelBase)this, 0, 22);
        this.ear3.addBox(-5.0f, -4.0f, 6.0f, 1, 2, 7);
        this.ear3.setRotationPoint(0.0f, 1.0f, 0.0f);
        this.ear3.setTextureSize(64, 32);
        this.ear3.mirror = true;
        this.setRotation(this.ear3, 1.047198f, 0.0f, 0.0f);
        this.ear4 = new ModelRenderer((ModelBase)this, 0, 22);
        this.ear4.addBox(-5.0f, -7.0f, 5.0f, 1, 2, 7);
        this.ear4.setRotationPoint(0.0f, 1.0f, 0.0f);
        this.ear4.setTextureSize(64, 32);
        this.ear4.mirror = true;
        this.setRotation(this.ear4, 1.047198f, 0.0f, 0.0f);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5);
        this.ear1.render(f5);
        this.body1.render(f5);
        this.ext1.render(f5);
        this.body2.render(f5);
        this.body3.render(f5);
        this.body4.render(f5);
        this.leftbackfoot.render(f5);
        this.eye1.render(f5);
        this.cap1.render(f5);
        this.leftbackleg.render(f5);
        this.leftfrontfoot.render(f5);
        this.leftfrontleg.render(f5);
        this.eye2.render(f5);
        this.ext2.render(f5);
        this.cap2.render(f5);
        this.rightbackfoot.render(f5);
        this.rightbackleg.render(f5);
        this.ext3.render(f5);
        this.eye3.render(f5);
        this.cap3.render(f5);
        this.ext4.render(f5);
        this.cap4.render(f5);
        this.eye4.render(f5);
        this.rightfrontleg.render(f5);
        this.rightfrontfoot.render(f5);
        this.head.render(f5);
        this.ear2.render(f5);
        this.ear3.render(f5);
        this.ear4.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float var1, float var2, float var3, float var4, float var5, float var6) {
        this.head.rotateAngleY = var4 / 57.295776f;
        this.head.rotateAngleX = var5 / 57.295776f;
        this.ear1.rotateAngleY = var4 / 57.295776f;
        this.ear1.rotateAngleX = var5 / 57.295776f;
        this.ear2.rotateAngleY = var4 / 57.295776f;
        this.ear2.rotateAngleX = var5 / 57.295776f;
        this.ear3.rotateAngleY = var4 / 57.295776f;
        this.ear3.rotateAngleX = var5 / 57.295776f;
        this.ear4.rotateAngleY = var4 / 57.295776f;
        this.ear4.rotateAngleX = var5 / 57.295776f;
        this.rightfrontleg.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.rightbackleg.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.rightfrontfoot.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.rightbackfoot.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.leftfrontleg.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.leftbackleg.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.leftfrontfoot.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.leftbackfoot.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.rightfrontleg.rotateAngleY = 0.0f;
        this.rightbackleg.rotateAngleY = 0.0f;
        this.rightfrontfoot.rotateAngleY = 0.0f;
        this.rightbackfoot.rotateAngleY = 0.0f;
        this.leftfrontleg.rotateAngleY = 0.0f;
        this.leftbackleg.rotateAngleY = 0.0f;
        this.leftfrontfoot.rotateAngleY = 0.0f;
        this.leftbackfoot.rotateAngleY = 0.0f;
    }
}

