package ru.simplemc.senergetics;

import cpw.mods.fml.common.registry.GameRegistry;
import ru.simplemc.senergetics.common.block.electicity.BlockSmartSolarPanel;
import ru.simplemc.senergetics.common.block.electicity.BlockSmartTransformer;
import ru.simplemc.senergetics.common.block.machine.BlockMachineLavaGenerator;
import ru.simplemc.senergetics.common.block.machine.BlockMachineSmartCompressor;
import ru.simplemc.senergetics.common.block.machine.BlockMachineSmartCrusher;
import ru.simplemc.senergetics.common.block.machine.BlockMachineSmartExtractor;
import ru.simplemc.senergetics.common.block.machine.BlockMachineSmartFurnace;
import ru.simplemc.senergetics.common.block.machine.BlockMachineSmartMetalFormer;
import ru.simplemc.senergetics.common.block.machine.BlockMachineSmartRecycler;
import ru.simplemc.senergetics.common.block.machine.BlockMolecularCollector;
import ru.simplemc.senergetics.common.block.machine.BlockNetherStarCollector;
import ru.simplemc.senergetics.common.block.machine.BlockSpawner;
import ru.simplemc.senergetics.common.block.machine.BlockSpawnerStandalone;
import ru.simplemc.senergetics.common.block.standalone.BlockChunkLoader;
import ru.simplemc.senergetics.common.item.electicity.panel.ItemPanelParticleCollector;
import ru.simplemc.senergetics.common.item.electicity.panel.ItemPanelParticleCollectorScheme;
import ru.simplemc.senergetics.common.item.electicity.panel.ItemPanelParticleCore;
import ru.simplemc.senergetics.common.item.machine.ItemBlockChunkLoader;
import ru.simplemc.senergetics.common.item.machine.upgrade.ItemMachineUpgradeOverclock;
import ru.simplemc.senergetics.common.item.tool.ItemChunkLoaderTicket;
import ru.simplemc.senergetics.common.item.tool.ItemMobDebug;
import ru.simplemc.senergetics.common.item.tool.ItemMobScanner;
import ru.simplemc.senergetics.common.item.tool.ItemSpawnerLevelUp;
import ru.simplemc.senergetics.common.item.tool.spawner.ItemSpawnerUpgradeScheme;
import ru.simplemc.senergetics.common.item.tool.spawner.upgrades.ItemSpawnerUpgradeExperience;
import ru.simplemc.senergetics.common.item.tool.spawner.upgrades.ItemSpawnerUpgradeLooting;
import ru.simplemc.senergetics.common.item.tool.spawner.upgrades.ItemSpawnerUpgradeSpeed;
import ru.simplemc.senergetics.common.item.tool.spawner.upgrades.ItemSpawnerUpgradeSuper;
import ru.simplemc.senergetics.common.tileentity.electricity.TileEntitySmartTransformer;
import ru.simplemc.senergetics.common.tileentity.electricity.TileEntitySolarPanel;
import ru.simplemc.senergetics.common.tileentity.machine.TileEntityChunkLoader;
import ru.simplemc.senergetics.common.tileentity.machine.TileEntityLavaGenerator;
import ru.simplemc.senergetics.common.tileentity.machine.TileEntityMolecularCollector;
import ru.simplemc.senergetics.common.tileentity.machine.TileEntityNetherStarCollector;
import ru.simplemc.senergetics.common.tileentity.machine.TileEntitySpawner;
import ru.simplemc.senergetics.common.tileentity.machine.smart.TileEntitySmartCompressor;
import ru.simplemc.senergetics.common.tileentity.machine.smart.TileEntitySmartCrusher;
import ru.simplemc.senergetics.common.tileentity.machine.smart.TileEntitySmartExtractor;
import ru.simplemc.senergetics.common.tileentity.machine.smart.TileEntitySmartFurnace;
import ru.simplemc.senergetics.common.tileentity.machine.smart.TileEntitySmartMetalFormer;
import ru.simplemc.senergetics.common.tileentity.machine.smart.TileEntitySmartRecycler;

public class SEnergeticsRegistry {
    public static BlockSpawner blockSpawner;
    public static BlockSpawnerStandalone blockSilentSpawnerStandalone;
    public static BlockChunkLoader blockChunkLoader;
    public static BlockSmartSolarPanel blockSmartSolarPanel;
    public static BlockSmartTransformer blockSmartTransformer;
    public static BlockMachineSmartCompressor blockMachineSmartCompressor;
    public static BlockMachineSmartExtractor blockMachineSmartExtractor;
    public static BlockMachineSmartCrusher blockMachineSmartCrusher;
    public static BlockMachineSmartFurnace blockMachineSmartFurnace;
    public static BlockMachineSmartRecycler blockMachineSmartRecycler;
    public static BlockMachineSmartMetalFormer blockMachineSmartMetalFormer;
    public static BlockMachineLavaGenerator blockMachineLavaGenerator;
    public static BlockMolecularCollector blockMolecularCollector;
    public static BlockNetherStarCollector blockNetherStarCollector;
    public static ItemMobDebug itemMobDebug;
    public static ItemMobScanner itemMobScanner;
    public static ItemSpawnerUpgradeSpeed itemSpawnerUpgradeSpeed;
    public static ItemSpawnerUpgradeLooting itemSpawnerUpgradeLooting;
    public static ItemSpawnerUpgradeExperience itemSpawnerUpgradeExperience;
    public static ItemSpawnerUpgradeSuper itemSpawnerUpgradeSuper;
    public static ItemSpawnerLevelUp itemSpawnerLevelUp_2;
    public static ItemSpawnerLevelUp itemSpawnerLevelUp_3;
    public static ItemBlockChunkLoader itemBlockChunkLoader;
    public static ItemChunkLoaderTicket itemChunkLoaderTicketLevel1;
    public static ItemChunkLoaderTicket itemChunkLoaderTicketLevel2;
    public static ItemChunkLoaderTicket itemChunkLoaderTicketLevel3;
    public static ItemChunkLoaderTicket itemChunkLoaderTicketLevel4;
    public static ItemPanelParticleCollectorScheme itemPanelParticleCollectorScheme;
    public static ItemPanelParticleCollector itemPanelParticleCollectorPhoton;
    public static ItemPanelParticleCollector itemPanelParticleCollectorQuark;
    public static ItemPanelParticleCollector itemPanelParticleCollectorBarion;
    public static ItemPanelParticleCollector itemPanelParticleCollectorGluon;
    public static ItemPanelParticleCollector itemPanelParticleCollectorFermion;
    public static ItemPanelParticleCollector itemPanelParticleCollectorBoson;
    public static ItemPanelParticleCollector itemPanelParticleCollectorQuantum;
    public static ItemPanelParticleCollector itemPanelParticleCollectorNeutron;
    public static ItemPanelParticleCore itemPanelParticleCorePhoton;
    public static ItemPanelParticleCore itemPanelParticleCoreQuark;
    public static ItemPanelParticleCore itemPanelParticleCoreBarion;
    public static ItemPanelParticleCore itemPanelParticleCoreGluon;
    public static ItemPanelParticleCore itemPanelParticleCoreFermion;
    public static ItemPanelParticleCore itemPanelParticleCoreBoson;
    public static ItemPanelParticleCore itemPanelParticleCoreQuantum;
    public static ItemPanelParticleCore itemPanelParticleCoreNeutron;
    public static ItemMachineUpgradeOverclock itemMachineUpgradeOverclock;
    public static ItemSpawnerUpgradeScheme itemSpawnerUpgradeScheme;

    public static void init() {
        blockSpawner = new BlockSpawner("block_silent_spawner");
        blockSilentSpawnerStandalone = new BlockSpawnerStandalone();
        blockChunkLoader = new BlockChunkLoader();
        blockSmartSolarPanel = new BlockSmartSolarPanel();
        blockSmartTransformer = new BlockSmartTransformer();
        blockMachineSmartCompressor = new BlockMachineSmartCompressor();
        blockMachineSmartExtractor = new BlockMachineSmartExtractor();
        blockMachineSmartCrusher = new BlockMachineSmartCrusher();
        blockMachineSmartFurnace = new BlockMachineSmartFurnace();
        blockMachineSmartRecycler = new BlockMachineSmartRecycler();
        blockMachineSmartMetalFormer = new BlockMachineSmartMetalFormer();
        blockMachineLavaGenerator = new BlockMachineLavaGenerator();
        blockMolecularCollector = new BlockMolecularCollector();
        blockNetherStarCollector = new BlockNetherStarCollector();
        GameRegistry.registerTileEntity(TileEntitySpawner.class, (String)"TileEntitySpawner");
        GameRegistry.registerTileEntity(TileEntityChunkLoader.class, (String)"TileEntityChunkLoader");
        GameRegistry.registerTileEntity(TileEntitySolarPanel.class, (String)"TileEntitySolarPanel");
        GameRegistry.registerTileEntity(TileEntitySmartTransformer.class, (String)"TileEntitySmartTransformer");
        GameRegistry.registerTileEntity(TileEntitySmartFurnace.class, (String)"TileEntitySmartFurnace");
        GameRegistry.registerTileEntity(TileEntitySmartCompressor.class, (String)"TileEntitySmartCompressor");
        GameRegistry.registerTileEntity(TileEntitySmartCrusher.class, (String)"TileEntitySmartCrusher");
        GameRegistry.registerTileEntity(TileEntitySmartExtractor.class, (String)"TileEntitySmartExtractor");
        GameRegistry.registerTileEntity(TileEntitySmartRecycler.class, (String)"TileEntitySmartRecycler");
        GameRegistry.registerTileEntity(TileEntitySmartMetalFormer.class, (String)"TileEntitySmartMetalFormer");
        GameRegistry.registerTileEntity(TileEntityLavaGenerator.class, (String)"TileEntityLavaGenerator");
        GameRegistry.registerTileEntity(TileEntityMolecularCollector.class, (String)"TileEntityMolecularCollector");
        GameRegistry.registerTileEntity(TileEntityNetherStarCollector.class, (String)"TileEntityNetherStarCollector");
        itemMobDebug = new ItemMobDebug();
        itemMobScanner = new ItemMobScanner();
        itemSpawnerUpgradeSpeed = new ItemSpawnerUpgradeSpeed();
        itemSpawnerUpgradeLooting = new ItemSpawnerUpgradeLooting();
        itemSpawnerUpgradeExperience = new ItemSpawnerUpgradeExperience();
        itemSpawnerUpgradeSuper = new ItemSpawnerUpgradeSuper();
        itemSpawnerLevelUp_2 = new ItemSpawnerLevelUp("lvl_2", 1);
        itemSpawnerLevelUp_3 = new ItemSpawnerLevelUp("lvl_3", 2);
        itemChunkLoaderTicketLevel1 = new ItemChunkLoaderTicket(1);
        itemChunkLoaderTicketLevel2 = new ItemChunkLoaderTicket(2);
        itemChunkLoaderTicketLevel3 = new ItemChunkLoaderTicket(3);
        itemChunkLoaderTicketLevel4 = new ItemChunkLoaderTicket(4);
        itemPanelParticleCollectorScheme = new ItemPanelParticleCollectorScheme();
        itemPanelParticleCorePhoton = new ItemPanelParticleCore("photon");
        itemPanelParticleCoreQuark = new ItemPanelParticleCore("quark");
        itemPanelParticleCoreBarion = new ItemPanelParticleCore("barion");
        itemPanelParticleCoreGluon = new ItemPanelParticleCore("gluon");
        itemPanelParticleCoreFermion = new ItemPanelParticleCore("fermion");
        itemPanelParticleCoreBoson = new ItemPanelParticleCore("boson");
        itemPanelParticleCoreQuantum = new ItemPanelParticleCore("quantum");
        itemPanelParticleCoreNeutron = new ItemPanelParticleCore("neutron");
        itemPanelParticleCollectorPhoton = new ItemPanelParticleCollector("photon", 1);
        itemPanelParticleCollectorQuark = new ItemPanelParticleCollector("quark", 2);
        itemPanelParticleCollectorBarion = new ItemPanelParticleCollector("barion", 3);
        itemPanelParticleCollectorGluon = new ItemPanelParticleCollector("gluon", 4);
        itemPanelParticleCollectorFermion = new ItemPanelParticleCollector("fermion", 5);
        itemPanelParticleCollectorBoson = new ItemPanelParticleCollector("boson", 6);
        itemPanelParticleCollectorQuantum = new ItemPanelParticleCollector("quantum", 7);
        itemPanelParticleCollectorNeutron = new ItemPanelParticleCollector("neutron", 8);
        itemMachineUpgradeOverclock = new ItemMachineUpgradeOverclock();
        itemSpawnerUpgradeScheme = new ItemSpawnerUpgradeScheme();
    }
}

