/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.MathHelper
 */
package net.divinerpg.client.render.entity.vanilla.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelRotatick
extends ModelBase {
    ModelRenderer Box8;
    ModelRenderer Body;
    ModelRenderer LegRBT;
    ModelRenderer LegLBT;
    ModelRenderer LegRFT;
    ModelRenderer LegLFT;
    ModelRenderer LegRMT;
    ModelRenderer LegLMT;
    ModelRenderer LegRF;
    ModelRenderer LegLF;
    ModelRenderer LegLM;
    ModelRenderer LegLB;
    ModelRenderer LegRM;
    ModelRenderer LegRB;
    ModelRenderer LegRFB;
    ModelRenderer LegLFB;
    ModelRenderer LegRMB;
    ModelRenderer LegRBB;
    ModelRenderer LegLMB;
    ModelRenderer LegLBB;
    ModelRenderer LegLFC;
    ModelRenderer LegLMC;
    ModelRenderer LegLBC;
    ModelRenderer LegRBC;
    ModelRenderer LegRMC;
    ModelRenderer LegRFC;
    ModelRenderer Box1;
    ModelRenderer Box2;
    ModelRenderer Box3;
    ModelRenderer Box4;
    ModelRenderer Box5;
    ModelRenderer Box6;
    ModelRenderer Box7;
    ModelRenderer Box9;
    ModelRenderer Head;
    ModelRenderer Box10;

    public ModelRotatick() {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.Box8 = new ModelRenderer((ModelBase)this, 41, 13);
        this.Box8.addBox(-4.0f, -3.0f, -1.0f, 3, 3, 1);
        this.Box8.setRotationPoint(5.0f, 19.0f, -10.0f);
        this.Box8.setTextureSize(64, 32);
        this.Box8.mirror = true;
        this.setRotation(this.Box8, 0.6320364f, 0.0f, 0.0f);
        this.Body = new ModelRenderer((ModelBase)this, 40, 7);
        this.Body.addBox(-4.0f, -2.0f, -3.0f, 6, 19, 6);
        this.Body.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.Body.setTextureSize(64, 32);
        this.Body.mirror = true;
        this.setRotation(this.Body, 1.570796f, 0.0f, 0.0f);
        this.LegRBT = new ModelRenderer((ModelBase)this, 42, 15);
        this.LegRBT.addBox(-2.0f, -1.0f, -2.0f, 4, 2, 4);
        this.LegRBT.setRotationPoint(-4.5f, 16.0f, 12.0f);
        this.LegRBT.setTextureSize(64, 32);
        this.LegRBT.mirror = true;
        this.setRotation(this.LegRBT, 0.0f, 0.0f, 0.0f);
        this.LegLBT = new ModelRenderer((ModelBase)this, 42, 15);
        this.LegLBT.addBox(-2.0f, -1.0f, -2.0f, 4, 2, 4);
        this.LegLBT.setRotationPoint(2.5f, 16.0f, 12.0f);
        this.LegLBT.setTextureSize(64, 32);
        this.LegLBT.mirror = true;
        this.setRotation(this.LegLBT, 0.0f, 0.0f, 0.0f);
        this.LegRFT = new ModelRenderer((ModelBase)this, 42, 15);
        this.LegRFT.addBox(-2.0f, -1.0f, -2.0f, 4, 2, 4);
        this.LegRFT.setRotationPoint(-4.5f, 16.0f, -4.0f);
        this.LegRFT.setTextureSize(64, 32);
        this.LegRFT.mirror = true;
        this.setRotation(this.LegRFT, 0.0f, 0.0f, 0.0f);
        this.LegLFT = new ModelRenderer((ModelBase)this, 42, 15);
        this.LegLFT.addBox(-2.0f, -1.0f, -2.0f, 4, 2, 4);
        this.LegLFT.setRotationPoint(2.5f, 16.0f, -4.0f);
        this.LegLFT.setTextureSize(64, 32);
        this.LegLFT.mirror = true;
        this.setRotation(this.LegLFT, 0.0f, 0.0f, 0.0f);
        this.LegRMT = new ModelRenderer((ModelBase)this, 42, 15);
        this.LegRMT.addBox(-2.0f, -1.0f, -1.0f, 4, 2, 4);
        this.LegRMT.setRotationPoint(-4.5f, 16.0f, 2.0f);
        this.LegRMT.setTextureSize(64, 32);
        this.LegRMT.mirror = true;
        this.setRotation(this.LegRMT, 0.0f, 0.0f, 0.0f);
        this.LegLMT = new ModelRenderer((ModelBase)this, 42, 15);
        this.LegLMT.addBox(-2.0f, -1.0f, -1.0f, 4, 2, 4);
        this.LegLMT.setRotationPoint(2.5f, 16.0f, 2.0f);
        this.LegLMT.setTextureSize(64, 32);
        this.LegLMT.mirror = true;
        this.setRotation(this.LegLMT, 0.0f, 0.0f, 0.0f);
        this.LegRF = new ModelRenderer((ModelBase)this, 0, 18);
        this.LegRF.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2);
        this.LegRF.setRotationPoint(-4.5f, 16.0f, -4.0f);
        this.LegRF.setTextureSize(64, 32);
        this.LegRF.mirror = true;
        this.setRotation(this.LegRF, 0.0f, 0.0f, 0.0f);
        this.LegLF = new ModelRenderer((ModelBase)this, 0, 18);
        this.LegLF.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2);
        this.LegLF.setRotationPoint(2.5f, 16.0f, -4.0f);
        this.LegLF.setTextureSize(64, 32);
        this.LegLF.mirror = true;
        this.setRotation(this.LegLF, 0.0f, 0.0f, 0.0f);
        this.LegLM = new ModelRenderer((ModelBase)this, 0, 18);
        this.LegLM.addBox(-1.0f, 0.0f, 0.0f, 2, 8, 2);
        this.LegLM.setRotationPoint(-4.5f, 16.0f, 2.0f);
        this.LegLM.setTextureSize(64, 32);
        this.LegLM.mirror = true;
        this.setRotation(this.LegLM, 0.0f, 0.0f, 0.0f);
        this.LegLB = new ModelRenderer((ModelBase)this, 0, 18);
        this.LegLB.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2);
        this.LegLB.setRotationPoint(-4.5f, 16.0f, 12.0f);
        this.LegLB.setTextureSize(64, 32);
        this.LegLB.mirror = true;
        this.setRotation(this.LegLB, 0.0f, 0.0f, 0.0f);
        this.LegRM = new ModelRenderer((ModelBase)this, 0, 18);
        this.LegRM.addBox(-1.0f, 0.0f, 0.0f, 2, 8, 2);
        this.LegRM.setRotationPoint(2.5f, 16.0f, 2.0f);
        this.LegRM.setTextureSize(64, 32);
        this.LegRM.mirror = true;
        this.setRotation(this.LegRM, 0.0f, 0.0f, 0.0f);
        this.LegRB = new ModelRenderer((ModelBase)this, 0, 18);
        this.LegRB.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2);
        this.LegRB.setRotationPoint(2.5f, 16.0f, 12.0f);
        this.LegRB.setTextureSize(64, 32);
        this.LegRB.mirror = true;
        this.setRotation(this.LegRB, 0.0f, 0.0f, 0.0f);
        this.LegRFB = new ModelRenderer((ModelBase)this, 14, 26);
        this.LegRFB.addBox(-2.0f, 6.0f, -2.0f, 4, 2, 4);
        this.LegRFB.setRotationPoint(-4.5f, 16.0f, -4.0f);
        this.LegRFB.setTextureSize(64, 32);
        this.LegRFB.mirror = true;
        this.setRotation(this.LegRFB, 0.0f, 0.0f, 0.0f);
        this.LegLFB = new ModelRenderer((ModelBase)this, 14, 26);
        this.LegLFB.addBox(-2.0f, 6.0f, -2.0f, 4, 2, 4);
        this.LegLFB.setRotationPoint(2.5f, 16.0f, -4.0f);
        this.LegLFB.setTextureSize(64, 32);
        this.LegLFB.mirror = true;
        this.setRotation(this.LegLFB, 0.0f, 0.0f, 0.0f);
        this.LegRMB = new ModelRenderer((ModelBase)this, 14, 26);
        this.LegRMB.addBox(-2.0f, 6.0f, -1.0f, 4, 2, 4);
        this.LegRMB.setRotationPoint(-4.5f, 16.0f, 2.0f);
        this.LegRMB.setTextureSize(64, 32);
        this.LegRMB.mirror = true;
        this.setRotation(this.LegRMB, 0.0f, 0.0f, 0.0f);
        this.LegRBB = new ModelRenderer((ModelBase)this, 14, 26);
        this.LegRBB.addBox(-2.0f, 6.0f, -2.0f, 4, 2, 4);
        this.LegRBB.setRotationPoint(-4.5f, 16.0f, 12.0f);
        this.LegRBB.setTextureSize(64, 32);
        this.LegRBB.mirror = true;
        this.setRotation(this.LegRBB, 0.0f, 0.0f, 0.0f);
        this.LegLMB = new ModelRenderer((ModelBase)this, 14, 26);
        this.LegLMB.addBox(-2.0f, 6.0f, -1.0f, 4, 2, 4);
        this.LegLMB.setRotationPoint(2.5f, 16.0f, 2.0f);
        this.LegLMB.setTextureSize(64, 32);
        this.LegLMB.mirror = true;
        this.setRotation(this.LegLMB, 0.0f, 0.0f, 0.0f);
        this.LegLBB = new ModelRenderer((ModelBase)this, 14, 26);
        this.LegLBB.addBox(-2.0f, 6.0f, -2.0f, 4, 2, 4);
        this.LegLBB.setRotationPoint(2.5f, 16.0f, 12.0f);
        this.LegLBB.setTextureSize(64, 32);
        this.LegLBB.mirror = true;
        this.setRotation(this.LegLBB, 0.0f, 0.0f, 0.0f);
        this.LegLFC = new ModelRenderer((ModelBase)this, 14, 18);
        this.LegLFC.addBox(-2.0f, 3.0f, -2.0f, 4, 1, 4);
        this.LegLFC.setRotationPoint(2.5f, 16.0f, -4.0f);
        this.LegLFC.setTextureSize(64, 32);
        this.LegLFC.mirror = true;
        this.setRotation(this.LegLFC, 0.0f, 0.0f, 0.0f);
        this.LegLMC = new ModelRenderer((ModelBase)this, 14, 18);
        this.LegLMC.addBox(-2.0f, 3.0f, -1.0f, 4, 1, 4);
        this.LegLMC.setRotationPoint(2.5f, 16.0f, 2.0f);
        this.LegLMC.setTextureSize(64, 32);
        this.LegLMC.mirror = true;
        this.setRotation(this.LegLMC, 0.0f, 0.0f, 0.0f);
        this.LegLBC = new ModelRenderer((ModelBase)this, 14, 18);
        this.LegLBC.addBox(-2.0f, 3.0f, -2.0f, 4, 1, 4);
        this.LegLBC.setRotationPoint(2.5f, 16.0f, 12.0f);
        this.LegLBC.setTextureSize(64, 32);
        this.LegLBC.mirror = true;
        this.setRotation(this.LegLBC, 0.0f, 0.0f, 0.0f);
        this.LegRBC = new ModelRenderer((ModelBase)this, 14, 18);
        this.LegRBC.addBox(-2.0f, 3.0f, -2.0f, 4, 1, 4);
        this.LegRBC.setRotationPoint(-4.5f, 16.0f, 12.0f);
        this.LegRBC.setTextureSize(64, 32);
        this.LegRBC.mirror = true;
        this.setRotation(this.LegRBC, 0.0f, 0.0f, 0.0f);
        this.LegRMC = new ModelRenderer((ModelBase)this, 14, 18);
        this.LegRMC.addBox(-2.0f, 3.0f, -1.0f, 4, 1, 4);
        this.LegRMC.setRotationPoint(-4.5f, 16.0f, 2.0f);
        this.LegRMC.setTextureSize(64, 32);
        this.LegRMC.mirror = true;
        this.setRotation(this.LegRMC, 0.0f, 0.0f, 0.0f);
        this.LegRFC = new ModelRenderer((ModelBase)this, 14, 18);
        this.LegRFC.addBox(-2.0f, 3.0f, -2.0f, 4, 1, 4);
        this.LegRFC.setRotationPoint(-4.5f, 16.0f, -4.0f);
        this.LegRFC.setTextureSize(64, 32);
        this.LegRFC.mirror = true;
        this.setRotation(this.LegRFC, 0.0f, 0.0f, 0.0f);
        this.Box1 = new ModelRenderer((ModelBase)this, 42, 21);
        this.Box1.addBox(-2.0f, -3.0f, 3.0f, 4, 4, 4);
        this.Box1.setRotationPoint(-1.0f, 11.0f, 7.0f);
        this.Box1.setTextureSize(64, 32);
        this.Box1.mirror = true;
        this.setRotation(this.Box1, 0.0f, 0.0f, 0.0f);
        this.Box2 = new ModelRenderer((ModelBase)this, 41, 13);
        this.Box2.addBox(-4.0f, -3.0f, -1.0f, 3, 3, 1);
        this.Box2.setRotationPoint(-2.0f, 19.0f, -10.0f);
        this.Box2.setTextureSize(64, 32);
        this.Box2.mirror = true;
        this.setRotation(this.Box2, 0.6320364f, 0.0f, 0.0f);
        this.Box3 = new ModelRenderer((ModelBase)this, 45, 16);
        this.Box3.addBox(-3.0f, 0.0f, -2.0f, 2, 2, 2);
        this.Box3.setRotationPoint(5.0f, 13.5f, -6.0f);
        this.Box3.setTextureSize(64, 32);
        this.Box3.mirror = true;
        this.setRotation(this.Box3, 0.0f, 0.0f, 0.0f);
        this.Box4 = new ModelRenderer((ModelBase)this, 42, 12);
        this.Box4.addBox(-2.0f, -3.0f, -2.0f, 4, 7, 4);
        this.Box4.setRotationPoint(-1.0f, 11.5f, -3.0f);
        this.Box4.setTextureSize(64, 32);
        this.Box4.mirror = true;
        this.setRotation(this.Box4, 0.0f, 0.0f, 0.0f);
        this.Box5 = new ModelRenderer((ModelBase)this, 42, 12);
        this.Box5.addBox(-2.0f, -3.0f, -2.0f, 4, 6, 4);
        this.Box5.setRotationPoint(-1.0f, 11.5f, 2.0f);
        this.Box5.setTextureSize(64, 32);
        this.Box5.mirror = true;
        this.setRotation(this.Box5, 0.0f, 0.0f, 0.0f);
        this.Box6 = new ModelRenderer((ModelBase)this, 42, 21);
        this.Box6.addBox(-2.0f, -3.0f, -2.0f, 4, 6, 4);
        this.Box6.setRotationPoint(-1.0f, 11.5f, 7.0f);
        this.Box6.setTextureSize(64, 32);
        this.Box6.mirror = true;
        this.setRotation(this.Box6, 0.0f, 0.0f, 0.0f);
        this.Box7 = new ModelRenderer((ModelBase)this, 41, 13);
        this.Box7.addBox(-4.0f, -3.0f, -1.0f, 1, 1, 6);
        this.Box7.setRotationPoint(6.0f, 19.5f, -9.0f);
        this.Box7.setTextureSize(64, 32);
        this.Box7.mirror = true;
        this.setRotation(this.Box7, 0.6320364f, 0.0f, 0.0f);
        this.Box9 = new ModelRenderer((ModelBase)this, 41, 13);
        this.Box9.addBox(-4.0f, -3.0f, -1.0f, 1, 1, 6);
        this.Box9.setRotationPoint(-1.0f, 19.5f, -9.0f);
        this.Box9.setTextureSize(64, 32);
        this.Box9.mirror = true;
        this.setRotation(this.Box9, 0.6320364f, 0.0f, 0.0f);
        this.Head = new ModelRenderer((ModelBase)this, 0, 0);
        this.Head.addBox(-3.0f, -3.0f, -2.0f, 6, 6, 4);
        this.Head.setRotationPoint(-1.0f, 13.5f, -7.0f);
        this.Head.setTextureSize(64, 32);
        this.Head.mirror = true;
        this.setRotation(this.Head, 0.0f, 0.0f, 0.0f);
        this.Box10 = new ModelRenderer((ModelBase)this, 45, 16);
        this.Box10.addBox(-3.0f, 0.0f, -2.0f, 2, 2, 2);
        this.Box10.setRotationPoint(-3.0f, 13.5f, -6.0f);
        this.Box10.setTextureSize(64, 32);
        this.Box10.mirror = true;
        this.setRotation(this.Box10, 0.0f, 0.0f, 0.0f);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5);
        this.Box8.render(f5);
        this.Body.render(f5);
        this.LegRBT.render(f5);
        this.LegLBT.render(f5);
        this.LegRFT.render(f5);
        this.LegLFT.render(f5);
        this.LegRMT.render(f5);
        this.LegLMT.render(f5);
        this.LegRF.render(f5);
        this.LegLF.render(f5);
        this.LegLM.render(f5);
        this.LegLB.render(f5);
        this.LegRM.render(f5);
        this.LegRB.render(f5);
        this.LegRFB.render(f5);
        this.LegLFB.render(f5);
        this.LegRMB.render(f5);
        this.LegRBB.render(f5);
        this.LegLMB.render(f5);
        this.LegLBB.render(f5);
        this.LegLFC.render(f5);
        this.LegLMC.render(f5);
        this.LegLBC.render(f5);
        this.LegRBC.render(f5);
        this.LegRMC.render(f5);
        this.LegRFC.render(f5);
        this.Box1.render(f5);
        this.Box2.render(f5);
        this.Box3.render(f5);
        this.Box4.render(f5);
        this.Box5.render(f5);
        this.Box6.render(f5);
        this.Box7.render(f5);
        this.Box9.render(f5);
        this.Head.render(f5);
        this.Box10.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float var1, float var2, float var3, float var4, float var5, float var6) {
        this.Head.rotateAngleY = var4 / 57.295776f;
        this.Head.rotateAngleX = var5 / 57.295776f;
        this.LegRBT.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.LegLB.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.LegRBB.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.LegRMT.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.LegLM.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.LegRMB.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.LegRFT.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.LegLF.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.LegRFB.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.LegRFC.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.LegRMC.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.LegRBC.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.LegLBT.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.LegRB.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.LegLBB.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.LegLMT.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.LegRM.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.LegLMB.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.LegLFT.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.LegRF.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.LegLFB.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.LegLFC.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.LegLMC.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.LegLFC.rotateAngleX = MathHelper.cos((float)((float)((double)(var1 * 0.6662f) + Math.PI))) * 1.4f * var2;
        this.LegRBT.rotateAngleY = 0.0f;
        this.LegRB.rotateAngleY = 0.0f;
        this.LegRBB.rotateAngleY = 0.0f;
        this.LegRMT.rotateAngleY = 0.0f;
        this.LegRM.rotateAngleY = 0.0f;
        this.LegRMB.rotateAngleY = 0.0f;
        this.LegRFT.rotateAngleY = 0.0f;
        this.LegRF.rotateAngleY = 0.0f;
        this.LegRFB.rotateAngleY = 0.0f;
        this.LegLBT.rotateAngleY = 0.0f;
        this.LegLB.rotateAngleY = 0.0f;
        this.LegLBB.rotateAngleY = 0.0f;
        this.LegLMT.rotateAngleY = 0.0f;
        this.LegLM.rotateAngleY = 0.0f;
        this.LegLMB.rotateAngleY = 0.0f;
        this.LegLFT.rotateAngleY = 0.0f;
        this.LegLF.rotateAngleY = 0.0f;
        this.LegLFB.rotateAngleY = 0.0f;
    }
}

