/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.MathHelper
 */
package net.divinerpg.client.render.entity.vanilla.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelAyeraco
extends ModelBase {
    ModelRenderer BodyLower;
    ModelRenderer Neck;
    ModelRenderer Head;
    ModelRenderer Tail;
    ModelRenderer WingLB;
    ModelRenderer Tail2;
    ModelRenderer Tail3;
    ModelRenderer Shape1;
    ModelRenderer WingRB;
    ModelRenderer WingRF;
    ModelRenderer WingLF;
    ModelRenderer WingRExtB;
    ModelRenderer WingLExtB;
    ModelRenderer WingLExtF;
    ModelRenderer WingRExtF;
    ModelRenderer WingRExt;
    ModelRenderer WingRM;
    ModelRenderer WingLM;
    ModelRenderer WingLExtM;
    ModelRenderer Mouth1;
    ModelRenderer Butt;
    ModelRenderer Head2;
    ModelRenderer Mouth2;
    ModelRenderer Body;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;

    public ModelAyeraco() {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.BodyLower = new ModelRenderer((ModelBase)this, 0, 0);
        this.BodyLower.addBox(0.0f, -1.0f, 0.0f, 10, 1, 12);
        this.BodyLower.setRotationPoint(-5.0f, 18.0f, -6.0f);
        this.BodyLower.setTextureSize(64, 32);
        this.BodyLower.mirror = true;
        this.setRotation(this.BodyLower, 0.0f, 0.0f, 0.0f);
        this.Neck = new ModelRenderer((ModelBase)this, 13, 16);
        this.Neck.addBox(0.0f, -1.0f, 0.0f, 12, 4, 2);
        this.Neck.setRotationPoint(-6.0f, 13.0f, -10.0f);
        this.Neck.setTextureSize(64, 32);
        this.Neck.mirror = true;
        this.setRotation(this.Neck, 0.0f, 0.0f, 0.0f);
        this.Head = new ModelRenderer((ModelBase)this, 0, 19);
        this.Head.addBox(0.0f, -1.0f, 0.0f, 6, 6, 7);
        this.Head.setRotationPoint(3.0f, 12.0f, -17.0f);
        this.Head.setTextureSize(64, 32);
        this.Head.mirror = true;
        this.setRotation(this.Head, 0.0f, 0.0f, 0.0f);
        this.Tail = new ModelRenderer((ModelBase)this, 40, 0);
        this.Tail.addBox(-1.0f, 0.0f, 0.0f, 2, 1, 10);
        this.Tail.setRotationPoint(3.0f, 14.0f, 14.0f);
        this.Tail.setTextureSize(64, 32);
        this.Tail.mirror = true;
        this.setRotation(this.Tail, 0.0f, 0.0f, 0.0f);
        this.WingLB = new ModelRenderer((ModelBase)this, 28, 27);
        this.WingLB.addBox(0.0f, 0.0f, 2.0f, 8, 1, 4);
        this.WingLB.setRotationPoint(5.0f, 13.0f, 1.0f);
        this.WingLB.setTextureSize(64, 32);
        this.WingLB.mirror = true;
        this.setRotation(this.WingLB, 0.0f, 0.0f, 0.0f);
        this.Tail2 = new ModelRenderer((ModelBase)this, 40, 0);
        this.Tail2.addBox(-1.0f, 0.0f, 0.0f, 2, 1, 10);
        this.Tail2.setRotationPoint(0.0f, 14.0f, 14.0f);
        this.Tail2.setTextureSize(64, 32);
        this.Tail2.mirror = true;
        this.setRotation(this.Tail2, 0.0f, 0.0f, 0.0f);
        this.Tail3 = new ModelRenderer((ModelBase)this, 40, 0);
        this.Tail3.addBox(-1.0f, 0.0f, 0.0f, 2, 1, 10);
        this.Tail3.setRotationPoint(-3.0f, 14.0f, 14.0f);
        this.Tail3.setTextureSize(64, 32);
        this.Tail3.mirror = true;
        this.setRotation(this.Tail3, 0.0f, 0.0f, 0.0f);
        this.Shape1 = new ModelRenderer((ModelBase)this, 44, 20);
        this.Shape1.addBox(0.0f, -1.0f, 0.0f, 4, 1, 6);
        this.Shape1.setRotationPoint(-2.0f, 9.0f, 14.0f);
        this.Shape1.setTextureSize(64, 32);
        this.Shape1.mirror = true;
        this.setRotation(this.Shape1, 0.4089647f, 0.0f, 0.0f);
        this.WingRB = new ModelRenderer((ModelBase)this, 28, 27);
        this.WingRB.addBox(-7.0f, 0.0f, 2.0f, 8, 1, 4);
        this.WingRB.setRotationPoint(-6.0f, 13.0f, 1.0f);
        this.WingRB.setTextureSize(64, 32);
        this.WingRB.mirror = true;
        this.setRotation(this.WingRB, 0.0f, 0.0f, 0.0f);
        this.WingRF = new ModelRenderer((ModelBase)this, 28, 27);
        this.WingRF.addBox(-7.0f, 0.0f, -2.0f, 8, 1, 4);
        this.WingRF.setRotationPoint(-6.0f, 13.0f, -3.0f);
        this.WingRF.setTextureSize(64, 32);
        this.WingRF.mirror = true;
        this.setRotation(this.WingRF, 0.0f, 0.0f, 0.0f);
        this.WingLF = new ModelRenderer((ModelBase)this, 28, 27);
        this.WingLF.addBox(0.0f, 0.0f, -2.0f, 8, 1, 4);
        this.WingLF.setRotationPoint(5.0f, 13.0f, -3.0f);
        this.WingLF.setTextureSize(64, 32);
        this.WingLF.mirror = true;
        this.setRotation(this.WingLF, 0.0f, 0.0f, 0.0f);
        this.WingRExtB = new ModelRenderer((ModelBase)this, 28, 27);
        this.WingRExtB.addBox(-15.0f, 0.0f, 3.0f, 8, 1, 2);
        this.WingRExtB.setRotationPoint(-6.0f, 13.0f, 1.0f);
        this.WingRExtB.setTextureSize(64, 32);
        this.WingRExtB.mirror = true;
        this.setRotation(this.WingRExtB, 0.0f, 0.0f, 0.0f);
        this.WingLExtB = new ModelRenderer((ModelBase)this, 28, 27);
        this.WingLExtB.addBox(8.0f, 0.0f, 3.0f, 8, 1, 2);
        this.WingLExtB.setRotationPoint(5.0f, 13.0f, 1.0f);
        this.WingLExtB.setTextureSize(64, 32);
        this.WingLExtB.mirror = true;
        this.setRotation(this.WingLExtB, 0.0f, 0.0f, 0.0f);
        this.WingLExtF = new ModelRenderer((ModelBase)this, 28, 27);
        this.WingLExtF.addBox(8.0f, 0.0f, -1.0f, 8, 1, 2);
        this.WingLExtF.setRotationPoint(5.0f, 13.0f, -3.0f);
        this.WingLExtF.setTextureSize(64, 32);
        this.WingLExtF.mirror = true;
        this.setRotation(this.WingLExtF, 0.0f, 0.0f, 0.0f);
        this.WingRExtF = new ModelRenderer((ModelBase)this, 28, 27);
        this.WingRExtF.addBox(-15.0f, 0.0f, -1.0f, 8, 1, 2);
        this.WingRExtF.setRotationPoint(-6.0f, 13.0f, -3.0f);
        this.WingRExtF.setTextureSize(64, 32);
        this.WingRExtF.mirror = true;
        this.setRotation(this.WingRExtF, 0.0f, 0.0f, 0.0f);
        this.WingRExt = new ModelRenderer((ModelBase)this, 28, 27);
        this.WingRExt.addBox(-15.0f, 0.0f, 3.0f, 8, 1, 2);
        this.WingRExt.setRotationPoint(-6.0f, 13.0f, -3.0f);
        this.WingRExt.setTextureSize(64, 32);
        this.WingRExt.mirror = true;
        this.setRotation(this.WingRExt, 0.0f, 0.0f, 0.0f);
        this.WingRM = new ModelRenderer((ModelBase)this, 28, 27);
        this.WingRM.addBox(-7.0f, 0.0f, 2.0f, 8, 1, 4);
        this.WingRM.setRotationPoint(-6.0f, 13.0f, -3.0f);
        this.WingRM.setTextureSize(64, 32);
        this.WingRM.mirror = true;
        this.setRotation(this.WingRM, 0.0f, 0.0f, 0.0f);
        this.WingLM = new ModelRenderer((ModelBase)this, 28, 27);
        this.WingLM.addBox(0.0f, 0.0f, 2.0f, 8, 1, 4);
        this.WingLM.setRotationPoint(5.0f, 13.0f, -3.0f);
        this.WingLM.setTextureSize(64, 32);
        this.WingLM.mirror = true;
        this.setRotation(this.WingLM, 0.0f, 0.0f, 0.0f);
        this.WingLExtM = new ModelRenderer((ModelBase)this, 28, 27);
        this.WingLExtM.addBox(8.0f, 0.0f, 3.0f, 8, 1, 2);
        this.WingLExtM.setRotationPoint(5.0f, 13.0f, -3.0f);
        this.WingLExtM.setTextureSize(64, 32);
        this.WingLExtM.mirror = true;
        this.setRotation(this.WingLExtM, 0.0f, 0.0f, 0.0f);
        this.Mouth1 = new ModelRenderer((ModelBase)this, 0, 19);
        this.Mouth1.addBox(0.0f, -1.0f, -7.0f, 6, 1, 7);
        this.Mouth1.setRotationPoint(3.0f, 18.0f, -10.0f);
        this.Mouth1.setTextureSize(64, 32);
        this.Mouth1.mirror = true;
        this.setRotation(this.Mouth1, 0.0743572f, 0.0f, 0.0f);
        this.Butt = new ModelRenderer((ModelBase)this, 10, 12);
        this.Butt.addBox(0.0f, -1.0f, 0.0f, 10, 4, 6);
        this.Butt.setRotationPoint(-5.0f, 13.0f, 8.0f);
        this.Butt.setTextureSize(64, 32);
        this.Butt.mirror = true;
        this.setRotation(this.Butt, 0.0f, 0.0f, 0.0f);
        this.Head2 = new ModelRenderer((ModelBase)this, 0, 19);
        this.Head2.addBox(0.0f, -1.0f, 0.0f, 6, 6, 7);
        this.Head2.setRotationPoint(-9.0f, 12.0f, -17.0f);
        this.Head2.setTextureSize(64, 32);
        this.Head2.mirror = true;
        this.setRotation(this.Head2, 0.0f, 0.0f, 0.0f);
        this.Mouth2 = new ModelRenderer((ModelBase)this, 0, 19);
        this.Mouth2.addBox(0.0f, -1.0f, -7.0f, 6, 1, 7);
        this.Mouth2.setRotationPoint(-9.0f, 18.0f, -10.0f);
        this.Mouth2.setTextureSize(64, 32);
        this.Mouth2.mirror = true;
        this.setRotation(this.Mouth2, 0.0743572f, 0.0f, 0.0f);
        this.Body = new ModelRenderer((ModelBase)this, 0, 0);
        this.Body.addBox(0.0f, -1.0f, 0.0f, 10, 6, 16);
        this.Body.setRotationPoint(-5.0f, 12.0f, -8.0f);
        this.Body.setTextureSize(64, 32);
        this.Body.mirror = true;
        this.setRotation(this.Body, 0.0f, 0.0f, 0.0f);
        this.Shape2 = new ModelRenderer((ModelBase)this, 44, 20);
        this.Shape2.addBox(0.0f, -1.0f, 0.0f, 4, 1, 6);
        this.Shape2.setRotationPoint(-2.0f, 13.0f, 10.0f);
        this.Shape2.setTextureSize(64, 32);
        this.Shape2.mirror = true;
        this.setRotation(this.Shape2, 0.7807508f, 0.0f, 0.0f);
        this.Shape3 = new ModelRenderer((ModelBase)this, 46, 20);
        this.Shape3.addBox(0.0f, -1.0f, 0.0f, 2, 1, 6);
        this.Shape3.setRotationPoint(5.0f, 12.0f, -16.0f);
        this.Shape3.setTextureSize(64, 32);
        this.Shape3.mirror = true;
        this.setRotation(this.Shape3, 0.7807508f, 0.0f, 0.0f);
        this.Shape4 = new ModelRenderer((ModelBase)this, 46, 20);
        this.Shape4.addBox(0.0f, -1.0f, 0.0f, 2, 1, 6);
        this.Shape4.setRotationPoint(5.0f, 8.0f, -12.0f);
        this.Shape4.setTextureSize(64, 32);
        this.Shape4.mirror = true;
        this.setRotation(this.Shape4, 0.4089647f, 0.0f, 0.0f);
        this.Shape5 = new ModelRenderer((ModelBase)this, 44, 20);
        this.Shape5.addBox(0.0f, -1.0f, 0.0f, 4, 1, 6);
        this.Shape5.setRotationPoint(-2.0f, 12.0f, -2.0f);
        this.Shape5.setTextureSize(64, 32);
        this.Shape5.mirror = true;
        this.setRotation(this.Shape5, 0.7807508f, 0.0f, 0.0f);
        this.Shape6 = new ModelRenderer((ModelBase)this, 44, 20);
        this.Shape6.addBox(0.0f, -1.0f, 0.0f, 4, 1, 6);
        this.Shape6.setRotationPoint(-2.0f, 8.0f, 2.0f);
        this.Shape6.setTextureSize(64, 32);
        this.Shape6.mirror = true;
        this.setRotation(this.Shape6, 0.4089647f, 0.0f, 0.0f);
        this.Shape7 = new ModelRenderer((ModelBase)this, 44, 20);
        this.Shape7.addBox(0.0f, -1.0f, 0.0f, 4, 1, 6);
        this.Shape7.setRotationPoint(-2.0f, 12.0f, 3.0f);
        this.Shape7.setTextureSize(64, 32);
        this.Shape7.mirror = true;
        this.setRotation(this.Shape7, 0.7807508f, 0.0f, 0.0f);
        this.Shape8 = new ModelRenderer((ModelBase)this, 44, 20);
        this.Shape8.addBox(0.0f, -1.0f, 0.0f, 4, 1, 6);
        this.Shape8.setRotationPoint(-2.0f, 8.0f, 7.0f);
        this.Shape8.setTextureSize(64, 32);
        this.Shape8.mirror = true;
        this.setRotation(this.Shape8, 0.4089647f, 0.0f, 0.0f);
        this.Shape9 = new ModelRenderer((ModelBase)this, 44, 20);
        this.Shape9.addBox(0.0f, -1.0f, 0.0f, 4, 1, 6);
        this.Shape9.setRotationPoint(-2.0f, 12.0f, 7.0f);
        this.Shape9.setTextureSize(64, 32);
        this.Shape9.mirror = true;
        this.setRotation(this.Shape9, 0.7807508f, 0.0f, 0.0f);
        this.Shape10 = new ModelRenderer((ModelBase)this, 44, 20);
        this.Shape10.addBox(0.0f, -1.0f, 0.0f, 4, 1, 6);
        this.Shape10.setRotationPoint(-2.0f, 8.0f, 11.0f);
        this.Shape10.setTextureSize(64, 32);
        this.Shape10.mirror = true;
        this.setRotation(this.Shape10, 0.4089647f, 0.0f, 0.0f);
        this.Shape11 = new ModelRenderer((ModelBase)this, 44, 20);
        this.Shape11.addBox(0.0f, -1.0f, 0.0f, 4, 1, 6);
        this.Shape11.setRotationPoint(-2.0f, 12.0f, -7.0f);
        this.Shape11.setTextureSize(64, 32);
        this.Shape11.mirror = true;
        this.setRotation(this.Shape11, 0.7807508f, 0.0f, 0.0f);
        this.Shape12 = new ModelRenderer((ModelBase)this, 44, 20);
        this.Shape12.addBox(0.0f, -1.0f, 0.0f, 4, 1, 6);
        this.Shape12.setRotationPoint(-2.0f, 8.0f, -3.0f);
        this.Shape12.setTextureSize(64, 32);
        this.Shape12.mirror = true;
        this.setRotation(this.Shape12, 0.4089647f, 0.0f, 0.0f);
        this.Shape13 = new ModelRenderer((ModelBase)this, 46, 20);
        this.Shape13.addBox(0.0f, -1.0f, 0.0f, 2, 1, 6);
        this.Shape13.setRotationPoint(-7.0f, 12.0f, -16.0f);
        this.Shape13.setTextureSize(64, 32);
        this.Shape13.mirror = true;
        this.setRotation(this.Shape13, 0.7807508f, 0.0f, 0.0f);
        this.Shape14 = new ModelRenderer((ModelBase)this, 46, 20);
        this.Shape14.addBox(0.0f, -1.0f, 0.0f, 2, 1, 6);
        this.Shape14.setRotationPoint(-7.0f, 8.0f, -12.0f);
        this.Shape14.setTextureSize(64, 32);
        this.Shape14.mirror = true;
        this.setRotation(this.Shape14, 0.4089647f, 0.0f, 0.0f);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5);
        this.BodyLower.render(f5);
        this.Neck.render(f5);
        this.Head.render(f5);
        this.Tail.render(f5);
        this.WingLB.render(f5);
        this.Tail2.render(f5);
        this.Tail3.render(f5);
        this.Shape1.render(f5);
        this.WingRB.render(f5);
        this.WingRF.render(f5);
        this.WingLF.render(f5);
        this.WingRExtB.render(f5);
        this.WingLExtB.render(f5);
        this.WingLExtF.render(f5);
        this.WingRExtF.render(f5);
        this.WingRExt.render(f5);
        this.WingRM.render(f5);
        this.WingLM.render(f5);
        this.WingLExtM.render(f5);
        this.Mouth1.render(f5);
        this.Butt.render(f5);
        this.Head2.render(f5);
        this.Mouth2.render(f5);
        this.Body.render(f5);
        this.Shape2.render(f5);
        this.Shape3.render(f5);
        this.Shape4.render(f5);
        this.Shape5.render(f5);
        this.Shape6.render(f5);
        this.Shape7.render(f5);
        this.Shape8.render(f5);
        this.Shape9.render(f5);
        this.Shape10.render(f5);
        this.Shape11.render(f5);
        this.Shape12.render(f5);
        this.Shape13.render(f5);
        this.Shape14.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float par2, float par3, float par4, float par5, float par6, float par7) {
        this.WingRF.rotateAngleZ = MathHelper.cos((float)(par4 * 0.1f)) * (float)Math.PI * 0.15f;
        this.WingRM.rotateAngleZ = MathHelper.cos((float)(par4 * 0.1f)) * (float)Math.PI * 0.15f;
        this.WingRB.rotateAngleZ = MathHelper.cos((float)(par4 * 0.1f)) * (float)Math.PI * 0.15f;
        this.WingRExtF.rotateAngleZ = MathHelper.cos((float)(par4 * 0.1f)) * (float)Math.PI * 0.15f;
        this.WingRExt.rotateAngleZ = MathHelper.cos((float)(par4 * 0.1f)) * (float)Math.PI * 0.15f;
        this.WingRExtB.rotateAngleZ = MathHelper.cos((float)(par4 * 0.1f)) * (float)Math.PI * 0.15f;
        this.WingLF.rotateAngleZ = -this.WingRF.rotateAngleZ;
        this.WingLM.rotateAngleZ = -this.WingRF.rotateAngleZ;
        this.WingLB.rotateAngleZ = -this.WingRF.rotateAngleZ;
        this.WingLExtF.rotateAngleZ = -this.WingRF.rotateAngleZ;
        this.WingLExtM.rotateAngleZ = -this.WingRF.rotateAngleZ;
        this.WingLExtB.rotateAngleZ = -this.WingRF.rotateAngleZ;
        this.Tail.rotateAngleX = MathHelper.cos((float)(par4 * 0.1f)) * (float)Math.PI * 0.15f;
        this.Tail2.rotateAngleX = MathHelper.cos((float)(par4 * 0.1f)) * (float)Math.PI * 0.15f;
        this.Tail3.rotateAngleX = MathHelper.cos((float)(par4 * 0.1f)) * (float)Math.PI * 0.15f;
    }
}

