/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.block.Block
 *  net.minecraft.init.Blocks
 *  net.minecraft.init.Items
 *  net.minecraft.item.Item
 *  net.minecraft.item.Item$ToolMaterial
 */
package net.divinerpg.utils.material;

import net.divinerpg.utils.Util;
import net.divinerpg.utils.items.IceikaItems;
import net.divinerpg.utils.items.JourneyItemsOther;
import net.divinerpg.utils.items.TwilightItemsOther;
import net.divinerpg.utils.items.VanillaItemsOther;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;

public class ToolMaterialMod {
    public static Item.ToolMaterial demonicSword = Util.addMeleeMaterial(3750, 42.0f, 15, null);
    public static Item.ToolMaterial charredKnife = Util.addMeleeMaterial(1750, 37.0f, 15, null);
    public static Item.ToolMaterial IcicleBane = Util.addMeleeMaterial(10.0f, 15);
    public static Item.ToolMaterial Icine = Util.addMeleeMaterial(16.0f, 15);
    public static Item.ToolMaterial Dark = Util.addMeleeMaterial(1150, 37.0f, 32, VanillaItemsOther.darkStone);
    public static Item.ToolMaterial Light = Util.addMeleeMaterial(1350, 38.0f, 32, VanillaItemsOther.orbOfLight);
    public static Item.ToolMaterial EnderFlame = Util.addMeleeMaterial(1950, 46.0f, 32, null);
    public static Item.ToolMaterial Heritage = Util.addMeleeMaterial(2700, 46.0f, 62, VanillaItemsOther.netherSoul);
    public static Item.ToolMaterial Enderice = Util.addMeleeMaterial(11.0f, 15);
    public static Item.ToolMaterial Snowslash = Util.addMeleeMaterial(150, 14.0f, 15, IceikaItems.snowflake);
    public static Item.ToolMaterial Glacier = Util.addMeleeMaterial(1000, 15.0f, 15, IceikaItems.snowflake);
    public static Item.ToolMaterial Frostking = Util.addMeleeMaterial(6000, 16.0f, 15, IceikaItems.snowflake);
    public static Item.ToolMaterial FrozenMaul = Util.addMeleeMaterial(12.0f, 15);
    public static Item.ToolMaterial Slime = Util.addMeleeMaterial(1000, 12.0f, 22, Items.diamond_sword);
    public static Item.ToolMaterial OceanKnife = Util.addMeleeMaterial(2000, 12.0f, 10, VanillaItemsOther.aquaticIngot);
    public static Item.ToolMaterial JungleKnife = Util.addMeleeMaterial(2000, 13.0f, 10, VanillaItemsOther.jungleStone);
    public static Item.ToolMaterial JungleRapier = Util.addMeleeMaterial(1200, 14.0f, 10, VanillaItemsOther.jungleStone);
    public static Item.ToolMaterial Bedrock = Util.addMeleeMaterial(1400, 20.0f, 22, Item.getItemFromBlock((Block)Blocks.bedrock));
    public static Item.ToolMaterial BedrockMaul = Util.addMeleeMaterial(13.0f, 22);
    public static Item.ToolMaterial Ender = Util.addMeleeMaterial(17.0f, 16);
    public static Item.ToolMaterial Divine = Util.addMeleeMaterial(35.0f, 120);
    public static Item.ToolMaterial AquaMaul = Util.addMeleeMaterial(4000, 22.0f, 10, VanillaItemsOther.aquaticIngot);
    public static Item.ToolMaterial AquaDagger = Util.addMeleeMaterial(2000, 16.0f, 15, VanillaItemsOther.aquaticIngot);
    public static Item.ToolMaterial AquaTrident = Util.addMeleeMaterial(3000, 16.0f, 15, VanillaItemsOther.aquaticIngot);
    public static Item.ToolMaterial Aquaton = Util.addMeleeMaterial(3000, 16.0f, 15, VanillaItemsOther.aquaticIngot);
    public static Item.ToolMaterial Frost = Util.addMeleeMaterial(3000, 15.0f, 15, IceikaItems.iceStone);
    public static Item.ToolMaterial Molten = Util.addMeleeMaterial(5000, 13.0f, 15, VanillaItemsOther.moltenStone);
    public static Item.ToolMaterial Shark = Util.addMeleeMaterial(2000, 17.0f, 15, VanillaItemsOther.aquaticIngot);
    public static Item.ToolMaterial DeathBringer = Util.addMeleeMaterial(6000, 17.0f, 15, VanillaItemsOther.corruptedStone);
    public static Item.ToolMaterial CrabclawMaul = Util.addMeleeMaterial(4000, 16.0f, 15, VanillaItemsOther.crabClaw);
    public static Item.ToolMaterial PoisonSaber = Util.addMeleeMaterial(3000, 21.0f, 15, VanillaItemsOther.jungleStone);
    public static Item.ToolMaterial FuryMaul = Util.addMeleeMaterial(4000, 25.0f, 15, Item.getItemFromBlock((Block)Blocks.bedrock));
    public static Item.ToolMaterial Scorching = Util.addMeleeMaterial(500, 26.0f, 15, VanillaItemsOther.purpleBlaze);
    public static Item.ToolMaterial Bluefire = Util.addMeleeMaterial(3000, 27.0f, 15, VanillaItemsOther.shadowBar);
    public static Item.ToolMaterial CorruptedMaul = Util.addMeleeMaterial(3000, 17.0f, 15, VanillaItemsOther.corruptedStone);
    public static Item.ToolMaterial Halite = Util.addMeleeMaterial(2300, 35.0f, 22, TwilightItemsOther.mortumGem);
    public static Item.ToolMaterial Skythern = Util.addMeleeMaterial(2000, 31.0f, 22, TwilightItemsOther.skythernGem);
    public static Item.ToolMaterial Eden = Util.addMeleeMaterial(2000, 25.0f, 22, TwilightItemsOther.edenGem);
    public static Item.ToolMaterial Wildwood = Util.addMeleeMaterial(2000, 27.0f, 22, TwilightItemsOther.wildwoodGem);
    public static Item.ToolMaterial Apalachia = Util.addMeleeMaterial(2000, 29.0f, 22, TwilightItemsOther.apalachiaGem);
    public static Item.ToolMaterial Mortum = Util.addMeleeMaterial(2000, 33.0f, 22, TwilightItemsOther.mortumGem);
    public static Item.ToolMaterial Arlemite = Util.addMeleeMaterial(4000, 14.0f, 10, VanillaItemsOther.arlemiteIngot);
    public static Item.ToolMaterial Sandslash = Util.addMeleeMaterial(100, 16.0f, 22, VanillaItemsOther.shadowBar);
    public static Item.ToolMaterial Rupee = Util.addMeleeMaterial(2500, 12.0f, 15, VanillaItemsOther.rupeeIngot);
    public static Item.ToolMaterial Inferno = Util.addMeleeMaterial(10.0f, 22);
    public static Item.ToolMaterial Cyclops = Util.addMeleeMaterial(1000, 10.0f, 10, VanillaItemsOther.cyclopsEye);
    public static Item.ToolMaterial Bloodgem = Util.addMeleeMaterial(9.0f, 15);
    public static Item.ToolMaterial Realmite = Util.addMeleeMaterial(1000, 10.0f, 10, VanillaItemsOther.realmiteIngot);
    public static Item.ToolMaterial Storm = Util.addMeleeMaterial(12.0f, 22);
    public static Item.ToolMaterial Saber = Util.addMeleeMaterial(17.0f, 22);
    public static Item.ToolMaterial ShadowSaber = Util.addMeleeMaterial(21.0f, 22);
    public static Item.ToolMaterial LiviciaSword = Util.addMeleeMaterial(100, 21.0f, 22, VanillaItemsOther.shadowStone);
    public static Item.ToolMaterial Palavence = Util.addMeleeMaterial(330, 1.0f, 0, null);
    public static Item.ToolMaterial Massivence = Util.addMeleeMaterial(550, 1.0f, 0, null);
    public static Item.ToolMaterial Frossivence = Util.addMeleeMaterial(1150, 1.0f, 0, IceikaItems.snowflake);
    public static Item.ToolMaterial FlamingFury = Util.addMeleeMaterial(6000, 27.0f, 15, VanillaItemsOther.moltenStone);
    public static Item.ToolMaterial ArcaniteBlade = Util.addMeleeMaterial(2000, 36.0f, 15, null);
    public static Item.ToolMaterial DualClaw = Util.addMeleeMaterial(4000, 17.0f, 15, VanillaItemsOther.crabClaw);
    public static Item.ToolMaterial TerranDagger = Util.addMeleeMaterial(350, 19.0f, 10, VanillaItemsOther.terranStone);
    public static Item.ToolMaterial TerranKnife = Util.addMeleeMaterial(750, 18.0f, 10, VanillaItemsOther.terranStone);
    public static Item.ToolMaterial TerranMaul = Util.addMeleeMaterial(1200, 17.0f, 10, VanillaItemsOther.terranStone);
    public static Item.ToolMaterial AquatoothSword = Util.addMeleeMaterial(3500, 18.0f, 10, VanillaItemsOther.liopleurodonSkull);
    public static Item.ToolMaterial AquatoothMaul = Util.addMeleeMaterial(3500, 19.0f, 10, VanillaItemsOther.liopleurodonSkull);
    public static Item.ToolMaterial everlight = Util.addMeleeMaterial(3500, 33.0f, 10, null);
    public static Item.ToolMaterial godly = Util.addMeleeMaterial(3000, 45.0f, 15, null);
    public static Item.ToolMaterial godlyDagger = Util.addMeleeMaterial(1500, 39.0f, 75, null);
    public static Item.ToolMaterial karos = Util.addMeleeMaterial(2500, 39.0f, 10, null);
    public static Item.ToolMaterial admin = Util.addMeleeMaterial(1, 2000.0f, 15, null);
    public static Item.ToolMaterial arcana = Util.addMeleeMaterial(2000, 34.0f, 10, null);
    public static Item.ToolMaterial aoesword = Util.addMeleeMaterial(3500, 37.0f, 15, null);
    public static Item.ToolMaterial hitheal = Util.addMeleeMaterial(3000, 41.0f, 15, null);
    public static Item.ToolMaterial fastsword = Util.addMeleeMaterial(2200, 35.0f, 15, VanillaItemsOther.greenChunk);
    public static Item.ToolMaterial regensword = Util.addMeleeMaterial(3000, 45.0f, 15, null);
    public static Item.ToolMaterial premregensword = Util.addMeleeMaterial(3000, 46.0f, 15, null);
    public static Item.ToolMaterial irondagger = Util.addMeleeMaterial(150, 12.0f, 15, null);
    public static Item.ToolMaterial griefdagger = Util.addMeleeMaterial(400, 23.0f, 15, null);
    public static Item.ToolMaterial magmadagger = Util.addMeleeMaterial(450, 28.0f, 15, null);
    public static Item.ToolMaterial poisondagger = Util.addMeleeMaterial(350, 31.0f, 15, null);
    public static Item.ToolMaterial regenerationdagger = Util.addMeleeMaterial(250, 31.0f, 15, null);
    public static Item.ToolMaterial HeavySwordD = Util.addMeleeMaterial(2500, 12.0f, 10, null);
    public static Item.ToolMaterial amazonite = Util.addMeleeMaterial(1000, 13.0f, 22, VanillaItemsOther.amazonite);
    public static Item.ToolMaterial copperSword = Util.addMeleeMaterial(300, 9.0f, 8, VanillaItemsOther.copperIngot);
    public static Item.ToolMaterial copperHeavySword = Util.addMeleeMaterial(1000, 9.0f, 10, null);
    public static Item.ToolMaterial ironHeavySword = Util.addMeleeMaterial(1500, 12.0f, 10, null);
    public static Item.ToolMaterial nightmareSword = Util.addMeleeMaterial(8000, 14.0f, 12, VanillaItemsOther.nightmareSteel);
    public static Item.ToolMaterial netherium = Util.addMeleeMaterial(3500, 38.0f, 29, VanillaItemsOther.netheriumIngot);
    public static Item.ToolMaterial amazoniteAxe = Util.addAxeMaterial(10, 5200, 18.0f, 7.0f, 0, VanillaItemsOther.amazonite);
    public static Item.ToolMaterial copperAxe = Util.addAxeMaterial(2, 200, 8.0f, 3.0f, 0, VanillaItemsOther.copperIngot);
    public static Item.ToolMaterial nightmareAxe = Util.addAxeMaterial(25, 2000, 19.0f, 3.0f, 0, VanillaItemsOther.nightmareSteel);
    public static Item.ToolMaterial netheriumAxe = Util.addAxeMaterial(100, 2000, 30.0f, 3.0f, 0, VanillaItemsOther.netheriumIngot);
    public static Item.ToolMaterial amazonitePick = Util.addPickMaterial(10, 5200, 18.0f, 7.0f, 0, VanillaItemsOther.amazonite);
    public static Item.ToolMaterial copperPick = Util.addPickMaterial(2, 200, 8.0f, 3.0f, 0, VanillaItemsOther.copperIngot);
    public static Item.ToolMaterial nightmarePick = Util.addAxeMaterial(25, 5000, 19.0f, 3.0f, 0, VanillaItemsOther.nightmareSteel);
    public static Item.ToolMaterial netheriumPick = Util.addAxeMaterial(100, 11000, 30.0f, 3.0f, 0, VanillaItemsOther.netheriumIngot);
    public static Item.ToolMaterial amazoniteShovel = Util.addSpadeMaterial(10, 5200, 18.0f, 7.0f, 0, VanillaItemsOther.amazonite);
    public static Item.ToolMaterial copperShovel = Util.addSpadeMaterial(2, 200, 8.0f, 3.0f, 0, VanillaItemsOther.copperIngot);
    public static Item.ToolMaterial nightmareShovel = Util.addAxeMaterial(25, 5000, 19.0f, 3.0f, 0, VanillaItemsOther.nightmareSteel);
    public static Item.ToolMaterial netheriumShovel = Util.addAxeMaterial(100, 11000, 30.0f, 3.0f, 0, VanillaItemsOther.netheriumIngot);
    public static Item.ToolMaterial sapphireSword = Util.addMeleeMaterial(800, 14.0f, 50, JourneyItemsOther.sapphire);
    public static Item.ToolMaterial shadiumSword = Util.addMeleeMaterial(1000, 14.0f, 10, JourneyItemsOther.shadiumIngot);
    public static Item.ToolMaterial luniumSword = Util.addMeleeMaterial(2000, 14.0f, 10, JourneyItemsOther.luniumIngot);
    public static Item.ToolMaterial bloodcrustSword = Util.addMeleeMaterial(2500, 23.0f, 23, JourneyItemsOther.bloodcrustIngot);
    public static Item.ToolMaterial withicBlade = Util.addMeleeMaterial(70, 15.0f, 10, null);
    public static Item.ToolMaterial celestiumSword = Util.addMeleeMaterial(1500, 42.0f, 10, null);
    public static Item.ToolMaterial premcelestiumSword = Util.addMeleeMaterial(2500, 44.0f, 30, null);
    public static Item.ToolMaterial cloudSlicer = Util.addMeleeMaterial(400, 25.0f, 10, null);
    public static Item.ToolMaterial poisonSword = Util.addMeleeMaterial(1600, 21.0f, 10, null);
    public static Item.ToolMaterial dragonsTooth = Util.addMeleeMaterial(2250, 21.0f, 10, null);
    public static Item.ToolMaterial royalBlade = Util.addMeleeMaterial(1250, 25.0f, 5, null);
    public static Item.ToolMaterial coreMender = Util.addMeleeMaterial(2450, 39.0f, 5, null);
    public static Item.ToolMaterial netherBeastSword = Util.addMeleeMaterial(1850, 40.0f, 5, null);
    public static Item.ToolMaterial koriteSword = Util.addMeleeMaterial(850, 21.0f, 10, null);
    public static Item.ToolMaterial mekyumSword = Util.addMeleeMaterial(1850, 23.0f, 10, null);
    public static Item.ToolMaterial RupeeShick = Util.addShickMaterial(6, 16.0f, 8.0f, 15);
    public static Item.ToolMaterial ArlemiteShick = Util.addShickMaterial(6, 12000, 13.0f, 8.0f, 15, VanillaItemsOther.arlemiteIngot);
    public static Item.ToolMaterial DivineShick = Util.addShickMaterial(8, 20.0f, 9.0f, 10);
    public static Item.ToolMaterial CelestiumShick = Util.addShickMaterial(8, 40.0f, 16.0f, 30);
    public static Item.ToolMaterial MekyumShick = Util.addShickMaterial(8, 6500, 26.0f, 12.0f, 25, JourneyItemsOther.mekyumIngot);
    public static Item.ToolMaterial KoriteShick = Util.addShickMaterial(8, 8000, 30.0f, 12.0f, 25, JourneyItemsOther.koriteIngot);
    public static Item.ToolMaterial StoronShick = Util.addShickMaterial(8, 4500, 42.0f, 8.0f, 25, JourneyItemsOther.storonIngot);
    public static Item.ToolMaterial RupeeAxe = Util.addAxeMaterial(6, 2500, 16.0f, 7.0f, 0, VanillaItemsOther.rupeeIngot);
    public static Item.ToolMaterial ArlemiteAxe = Util.addAxeMaterial(3, 3000, 13.0f, 7.0f, 10, VanillaItemsOther.arlemiteIngot);
    public static Item.ToolMaterial RealmiteAxe = Util.addAxeMaterial(3, 4000, 12.0f, 6.0f, 10, VanillaItemsOther.realmiteIngot);
    public static Item.ToolMaterial CyclopsAxe = Util.addAxeMaterial(0, 1000, 8.0f, 6.0f, 10, VanillaItemsOther.cyclopsEye);
    public static Item.ToolMaterial BedrockAxe = Util.addAxeMaterial(3, 20.0f, 6.0f, 10);
    public static Item.ToolMaterial CorruptedAxe = Util.addAxeMaterial(3, 6000, 16.0f, 7.0f, 10, VanillaItemsOther.corruptedStone);
    public static Item.ToolMaterial SkythernAxe = Util.addAxeMaterial(100, 6000, 48.0f, 10.0f, 22, TwilightItemsOther.skythernGem);
    public static Item.ToolMaterial EdenAxe = Util.addAxeMaterial(100, 6000, 20.0f, 7.0f, 22, TwilightItemsOther.edenGem);
    public static Item.ToolMaterial WildwoodAxe = Util.addAxeMaterial(100, 6000, 28.0f, 8.0f, 22, TwilightItemsOther.wildwoodGem);
    public static Item.ToolMaterial ApalachiaAxe = Util.addAxeMaterial(100, 6000, 40.0f, 9.0f, 22, TwilightItemsOther.apalachiaGem);
    public static Item.ToolMaterial MortumAxe = Util.addAxeMaterial(100, 6000, 55.0f, 11.0f, 22, TwilightItemsOther.mortumGem);
    public static Item.ToolMaterial DivineAxe = Util.addAxeMaterial(8, 35000, 20.0f, 8.0f, 10, VanillaItemsOther.divineStone);
    public static Item.ToolMaterial SapphireAxe = Util.addAxeMaterial(6, 650, 16.0f, 5.0f, 10, JourneyItemsOther.sapphire);
    public static Item.ToolMaterial ShadiumAxe = Util.addAxeMaterial(7, 1000, 22.0f, 8.0f, 10, JourneyItemsOther.shadiumIngot);
    public static Item.ToolMaterial LuniumAxe = Util.addAxeMaterial(6, 800, 18.0f, 6.0f, 10, JourneyItemsOther.luniumIngot);
    public static Item.ToolMaterial BloodcrustAxe = Util.addAxeMaterial(7, 400, 18.0f, 2.0f, 10, JourneyItemsOther.bloodcrustIngot);
    public static Item.ToolMaterial CelestiumAxe = Util.addAxeMaterial(100, 3000, 70.0f, 16.0f, 30, JourneyItemsOther.celestiumIngot);
    public static Item.ToolMaterial MekyumAxe = Util.addAxeMaterial(100, 2000, 60.0f, 12.0f, 25, JourneyItemsOther.mekyumIngot);
    public static Item.ToolMaterial KoriteAxe = Util.addAxeMaterial(100, 2650, 58.0f, 12.0f, 25, JourneyItemsOther.koriteIngot);
    public static Item.ToolMaterial StoronAxe = Util.addAxeMaterial(100, 800, 62.0f, 8.0f, 25, JourneyItemsOther.storonIngot);
    public static Item.ToolMaterial RupeePick = Util.addPickMaterial(6, 2500, 16.0f, 5.0f, 0, VanillaItemsOther.rupeeIngot);
    public static Item.ToolMaterial ArlemitePick = Util.addPickMaterial(3, 3000, 13.0f, 5.0f, 10, VanillaItemsOther.arlemiteIngot);
    public static Item.ToolMaterial RealmitePick = Util.addPickMaterial(3, 4000, 12.0f, 4.0f, 10, VanillaItemsOther.realmiteIngot);
    public static Item.ToolMaterial CyclopsPick = Util.addPickMaterial(0, 1000, 8.0f, 4.0f, 10, VanillaItemsOther.cyclopsEye);
    public static Item.ToolMaterial BedrockPick = Util.addPickMaterial(3, 9.0f, 4.0f, 10);
    public static Item.ToolMaterial CorruptedPick = Util.addPickMaterial(3, 6000, 16.0f, 5.0f, 10, VanillaItemsOther.corruptedStone);
    public static Item.ToolMaterial SkythernPick = Util.addPickMaterial(100, 6000, 48.0f, 8.0f, 22, TwilightItemsOther.skythernGem);
    public static Item.ToolMaterial EdenPick = Util.addPickMaterial(100, 6000, 20.0f, 5.0f, 22, TwilightItemsOther.edenGem);
    public static Item.ToolMaterial WildwoodPick = Util.addPickMaterial(100, 6000, 28.0f, 6.0f, 22, TwilightItemsOther.wildwoodGem);
    public static Item.ToolMaterial ApalachiaPick = Util.addPickMaterial(100, 6000, 40.0f, 7.0f, 22, TwilightItemsOther.apalachiaGem);
    public static Item.ToolMaterial MortumPick = Util.addPickMaterial(100, 6000, 55.0f, 9.0f, 22, TwilightItemsOther.mortumGem);
    public static Item.ToolMaterial DivinePick = Util.addPickMaterial(8, 35000, 20.0f, 6.0f, 10, VanillaItemsOther.divineStone);
    public static Item.ToolMaterial SapphirePick = Util.addPickMaterial(6, 650, 16.0f, 3.0f, 10, JourneyItemsOther.sapphire);
    public static Item.ToolMaterial ShadiumPick = Util.addPickMaterial(7, 1000, 22.0f, 6.0f, 10, JourneyItemsOther.shadiumIngot);
    public static Item.ToolMaterial LuniumPick = Util.addPickMaterial(6, 800, 18.0f, 4.0f, 10, JourneyItemsOther.luniumIngot);
    public static Item.ToolMaterial BloodcrustPick = Util.addPickMaterial(7, 400, 18.0f, 2.0f, 10, JourneyItemsOther.bloodcrustIngot);
    public static Item.ToolMaterial CelestiumPick = Util.addPickMaterial(100, 3000, 70.0f, 14.0f, 30, JourneyItemsOther.celestiumIngot);
    public static Item.ToolMaterial MekyumPick = Util.addPickMaterial(100, 2000, 60.0f, 10.0f, 25, JourneyItemsOther.mekyumIngot);
    public static Item.ToolMaterial KoritePick = Util.addPickMaterial(100, 2650, 58.0f, 10.0f, 25, JourneyItemsOther.koriteIngot);
    public static Item.ToolMaterial StoronPick = Util.addPickMaterial(100, 800, 62.0f, 6.0f, 25, JourneyItemsOther.storonIngot);
    public static Item.ToolMaterial RupeeSpade = Util.addSpadeMaterial(6, 2500, 16.0f, 5.0f, 0, VanillaItemsOther.rupeeIngot);
    public static Item.ToolMaterial ArlemiteSpade = Util.addSpadeMaterial(3, 3000, 13.0f, 5.0f, 10, VanillaItemsOther.arlemiteIngot);
    public static Item.ToolMaterial RealmiteSpade = Util.addSpadeMaterial(3, 4000, 12.0f, 4.0f, 10, VanillaItemsOther.realmiteIngot);
    public static Item.ToolMaterial CyclopsSpade = Util.addSpadeMaterial(0, 1000, 8.0f, 4.0f, 10, VanillaItemsOther.cyclopsEye);
    public static Item.ToolMaterial BedrockSpade = Util.addSpadeMaterial(3, 20.0f, 4.0f, 10);
    public static Item.ToolMaterial CorruptedSpade = Util.addSpadeMaterial(3, 6000, 16.0f, 5.0f, 10, VanillaItemsOther.corruptedStone);
    public static Item.ToolMaterial SkythernSpade = Util.addSpadeMaterial(100, 6000, 48.0f, 8.0f, 22, TwilightItemsOther.skythernGem);
    public static Item.ToolMaterial EdenSpade = Util.addSpadeMaterial(100, 6000, 20.0f, 5.0f, 22, TwilightItemsOther.edenGem);
    public static Item.ToolMaterial WildwoodSpade = Util.addSpadeMaterial(100, 6000, 28.0f, 6.0f, 22, TwilightItemsOther.wildwoodGem);
    public static Item.ToolMaterial ApalachiaSpade = Util.addSpadeMaterial(100, 6000, 40.0f, 7.0f, 22, TwilightItemsOther.apalachiaGem);
    public static Item.ToolMaterial MortumSpade = Util.addSpadeMaterial(100, 6000, 55.0f, 9.0f, 22, TwilightItemsOther.mortumGem);
    public static Item.ToolMaterial DivineSpade = Util.addSpadeMaterial(8, 35000, 20.0f, 6.0f, 10, VanillaItemsOther.divineStone);
    public static Item.ToolMaterial SapphireSpade = Util.addSpadeMaterial(6, 450, 16.0f, 5.0f, 10, JourneyItemsOther.sapphire);
    public static Item.ToolMaterial ShadiumSpade = Util.addSpadeMaterial(7, 800, 22.0f, 8.0f, 10, JourneyItemsOther.shadiumIngot);
    public static Item.ToolMaterial LuniumSpade = Util.addSpadeMaterial(6, 600, 18.0f, 6.0f, 10, JourneyItemsOther.luniumIngot);
    public static Item.ToolMaterial BloodcrustSpade = Util.addSpadeMaterial(7, 300, 18.0f, 2.0f, 10, JourneyItemsOther.bloodcrustIngot);
    public static Item.ToolMaterial CelestiumSpade = Util.addSpadeMaterial(100, 2600, 70.0f, 16.0f, 30, JourneyItemsOther.celestiumIngot);
    public static Item.ToolMaterial MekyumSpade = Util.addSpadeMaterial(100, 1800, 60.0f, 12.0f, 25, JourneyItemsOther.mekyumIngot);
    public static Item.ToolMaterial KoriteSpade = Util.addSpadeMaterial(100, 2250, 58.0f, 12.0f, 25, JourneyItemsOther.koriteIngot);
    public static Item.ToolMaterial StoronSpade = Util.addSpadeMaterial(100, 800, 62.0f, 8.0f, 25, JourneyItemsOther.storonIngot);
    public static Item.ToolMaterial spectralSword = Util.addMeleeMaterial(4700, 48.0f, 62, JourneyItemsOther.SpectralStone);
    public static Item.ToolMaterial swordcoll = Util.addMeleeMaterial(9500, 38.0f, 62, JourneyItemsOther.CutaliisStone);
}

