/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.MathHelper
 */
package net.divinerpg.client.render.entity.twilight.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelSoulFiend
extends ModelBase {
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarmext;
    ModelRenderer leftarmext;
    ModelRenderer rightlegcap;
    ModelRenderer leftlegcap;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer back;
    ModelRenderer back2;
    ModelRenderer back3;
    ModelRenderer back4;
    ModelRenderer leftleg;
    ModelRenderer rightleg;
    ModelRenderer leftarm;
    ModelRenderer rightarm;
    ModelRenderer leftfoot;
    ModelRenderer rightfoot;
    ModelRenderer back5;
    ModelRenderer back6;
    ModelRenderer back7;
    ModelRenderer back8;
    ModelRenderer back9;
    ModelRenderer back10;
    ModelRenderer back11;
    ModelRenderer back12;

    public ModelSoulFiend() {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.head = new ModelRenderer((ModelBase)this, 0, 0);
        this.head.addBox(-4.0f, -8.0f, -4.0f, 8, 8, 8);
        this.head.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.head.setTextureSize(64, 32);
        this.head.mirror = true;
        this.setRotation(this.head, 0.0f, 0.0f, 0.0f);
        this.body = new ModelRenderer((ModelBase)this, 16, 16);
        this.body.addBox(-4.0f, 0.0f, -2.0f, 8, 12, 4);
        this.body.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.body.setTextureSize(64, 32);
        this.body.mirror = true;
        this.setRotation(this.body, 0.0f, 0.0f, 0.0f);
        this.rightarmext = new ModelRenderer((ModelBase)this, 40, 16);
        this.rightarmext.addBox(1.0f, -2.0f, -2.0f, 3, 3, 4);
        this.rightarmext.setRotationPoint(-8.0f, 2.0f, 0.0f);
        this.rightarmext.setTextureSize(64, 32);
        this.rightarmext.mirror = true;
        this.setRotation(this.rightarmext, 0.0f, 0.0f, 0.0f);
        this.leftarmext = new ModelRenderer((ModelBase)this, 40, 16);
        this.leftarmext.addBox(-4.0f, -2.0f, -2.0f, 3, 3, 4);
        this.leftarmext.setRotationPoint(8.0f, 2.0f, 0.0f);
        this.leftarmext.setTextureSize(64, 32);
        this.leftarmext.mirror = true;
        this.setRotation(this.leftarmext, 0.0f, 0.0f, 0.0f);
        this.rightlegcap = new ModelRenderer((ModelBase)this, 0, 16);
        this.rightlegcap.addBox(-3.0f, -4.0f, -3.0f, 6, 5, 6);
        this.rightlegcap.setRotationPoint(-4.0f, 12.0f, 0.0f);
        this.rightlegcap.setTextureSize(64, 32);
        this.rightlegcap.mirror = true;
        this.setRotation(this.rightlegcap, 0.0f, 0.0f, 0.0f);
        this.leftlegcap = new ModelRenderer((ModelBase)this, 0, 16);
        this.leftlegcap.addBox(-3.0f, -4.0f, -3.0f, 6, 5, 6);
        this.leftlegcap.setRotationPoint(4.0f, 12.0f, 0.0f);
        this.leftlegcap.setTextureSize(64, 32);
        this.leftlegcap.mirror = true;
        this.setRotation(this.leftlegcap, 0.0f, 0.0f, 0.0f);
        this.Shape1 = new ModelRenderer((ModelBase)this, 8, 0);
        this.Shape1.addBox(0.0f, 0.0f, 0.0f, 2, 2, 5);
        this.Shape1.setRotationPoint(2.0f, -8.0f, -9.0f);
        this.Shape1.setTextureSize(64, 32);
        this.Shape1.mirror = true;
        this.setRotation(this.Shape1, 0.0f, 0.0f, 0.0f);
        this.Shape2 = new ModelRenderer((ModelBase)this, 8, 0);
        this.Shape2.addBox(0.0f, 0.0f, 0.0f, 2, 2, 5);
        this.Shape2.setRotationPoint(-4.0f, -8.0f, -9.0f);
        this.Shape2.setTextureSize(64, 32);
        this.Shape2.mirror = true;
        this.setRotation(this.Shape2, 0.0f, 0.0f, 0.0f);
        this.Shape3 = new ModelRenderer((ModelBase)this, 9, 0);
        this.Shape3.addBox(0.0f, 0.0f, 0.0f, 4, 2, 2);
        this.Shape3.setRotationPoint(4.0f, -6.0f, -4.0f);
        this.Shape3.setTextureSize(64, 32);
        this.Shape3.mirror = true;
        this.setRotation(this.Shape3, 0.0f, 0.0f, 0.0f);
        this.Shape4 = new ModelRenderer((ModelBase)this, 9, 0);
        this.Shape4.addBox(0.0f, 0.0f, 0.0f, 4, 2, 2);
        this.Shape4.setRotationPoint(-8.0f, -6.0f, -4.0f);
        this.Shape4.setTextureSize(64, 32);
        this.Shape4.mirror = true;
        this.setRotation(this.Shape4, 0.0f, 0.0f, 0.0f);
        this.Shape5 = new ModelRenderer((ModelBase)this, 9, 0);
        this.Shape5.addBox(0.0f, 0.0f, 0.0f, 4, 2, 2);
        this.Shape5.setRotationPoint(4.0f, -3.0f, -4.0f);
        this.Shape5.setTextureSize(64, 32);
        this.Shape5.mirror = true;
        this.setRotation(this.Shape5, 0.0f, 0.0f, 0.0f);
        this.Shape6 = new ModelRenderer((ModelBase)this, 9, 0);
        this.Shape6.addBox(0.0f, 0.0f, 0.0f, 4, 2, 2);
        this.Shape6.setRotationPoint(-8.0f, -3.0f, -4.0f);
        this.Shape6.setTextureSize(64, 32);
        this.Shape6.mirror = true;
        this.setRotation(this.Shape6, 0.0f, 0.0f, 0.0f);
        this.Shape7 = new ModelRenderer((ModelBase)this, 8, 0);
        this.Shape7.addBox(0.0f, 0.0f, 0.0f, 2, 2, 5);
        this.Shape7.setRotationPoint(6.0f, -6.0f, -9.0f);
        this.Shape7.setTextureSize(64, 32);
        this.Shape7.mirror = true;
        this.setRotation(this.Shape7, 0.0f, 0.0f, 0.0f);
        this.Shape8 = new ModelRenderer((ModelBase)this, 8, 0);
        this.Shape8.addBox(0.0f, 0.0f, 0.0f, 2, 2, 5);
        this.Shape8.setRotationPoint(6.0f, -3.0f, -9.0f);
        this.Shape8.setTextureSize(64, 32);
        this.Shape8.mirror = true;
        this.setRotation(this.Shape8, 0.0f, 0.0f, 0.0f);
        this.Shape9 = new ModelRenderer((ModelBase)this, 8, 0);
        this.Shape9.addBox(0.0f, 0.0f, 0.0f, 2, 2, 5);
        this.Shape9.setRotationPoint(-8.0f, -6.0f, -9.0f);
        this.Shape9.setTextureSize(64, 32);
        this.Shape9.mirror = true;
        this.setRotation(this.Shape9, 0.0f, 0.0f, 0.0f);
        this.Shape10 = new ModelRenderer((ModelBase)this, 8, 0);
        this.Shape10.addBox(0.0f, 0.0f, 0.0f, 2, 2, 5);
        this.Shape10.setRotationPoint(-8.0f, -3.0f, -9.0f);
        this.Shape10.setTextureSize(64, 32);
        this.Shape10.mirror = true;
        this.setRotation(this.Shape10, 0.0f, 0.0f, 0.0f);
        this.back = new ModelRenderer((ModelBase)this, 4, 0);
        this.back.addBox(0.0f, 0.0f, 0.0f, 4, 4, 5);
        this.back.setRotationPoint(-2.0f, 4.0f, 2.0f);
        this.back.setTextureSize(64, 32);
        this.back.mirror = true;
        this.setRotation(this.back, 0.0f, 0.0f, 0.0f);
        this.back2 = new ModelRenderer((ModelBase)this, 34, 26);
        this.back2.addBox(0.0f, 0.0f, 0.0f, 12, 2, 2);
        this.back2.setRotationPoint(-12.0f, 13.0f, 4.0f);
        this.back2.setTextureSize(64, 32);
        this.back2.mirror = true;
        this.setRotation(this.back2, 0.0f, 0.0f, -0.6108652f);
        this.back3 = new ModelRenderer((ModelBase)this, 15, 25);
        this.back3.addBox(0.0f, 0.0f, 0.0f, 9, 2, 2);
        this.back3.setRotationPoint(8.0f, 4.0f, 5.0f);
        this.back3.setTextureSize(64, 32);
        this.back3.mirror = true;
        this.setRotation(this.back3, 0.0f, 0.0f, -1.570796f);
        this.back4 = new ModelRenderer((ModelBase)this, 15, 25);
        this.back4.addBox(0.0f, -1.0f, 0.0f, 9, 2, 2);
        this.back4.setRotationPoint(-9.0f, 4.0f, 5.0f);
        this.back4.setTextureSize(64, 32);
        this.back4.mirror = true;
        this.setRotation(this.back4, 0.0f, 0.0f, -1.570796f);
        this.leftleg = new ModelRenderer((ModelBase)this, 0, 16);
        this.leftleg.addBox(-2.0f, 0.0f, -2.0f, 4, 12, 4);
        this.leftleg.setRotationPoint(4.0f, 12.0f, 0.0f);
        this.leftleg.setTextureSize(64, 32);
        this.leftleg.mirror = true;
        this.setRotation(this.leftleg, 0.0f, 0.0f, 0.0f);
        this.rightleg = new ModelRenderer((ModelBase)this, 0, 16);
        this.rightleg.addBox(-2.0f, 0.0f, -2.0f, 4, 12, 4);
        this.rightleg.setRotationPoint(-4.0f, 12.0f, 0.0f);
        this.rightleg.setTextureSize(64, 32);
        this.rightleg.mirror = true;
        this.setRotation(this.rightleg, 0.0f, 0.0f, 0.0f);
        this.leftarm = new ModelRenderer((ModelBase)this, 40, 3);
        this.leftarm.addBox(-1.0f, -2.0f, -2.0f, 4, 20, 4);
        this.leftarm.setRotationPoint(8.0f, 2.0f, 0.0f);
        this.leftarm.setTextureSize(64, 32);
        this.leftarm.mirror = true;
        this.setRotation(this.leftarm, 0.0f, 0.0f, 0.0f);
        this.rightarm = new ModelRenderer((ModelBase)this, 40, 3);
        this.rightarm.addBox(-3.0f, -2.0f, -2.0f, 4, 20, 4);
        this.rightarm.setRotationPoint(-8.0f, 2.0f, 0.0f);
        this.rightarm.setTextureSize(64, 32);
        this.rightarm.mirror = true;
        this.setRotation(this.rightarm, 0.0f, 0.0f, 0.0f);
        this.leftfoot = new ModelRenderer((ModelBase)this, 0, 16);
        this.leftfoot.addBox(-3.0f, 9.0f, -3.0f, 6, 3, 6);
        this.leftfoot.setRotationPoint(4.0f, 12.0f, 0.0f);
        this.leftfoot.setTextureSize(64, 32);
        this.leftfoot.mirror = true;
        this.setRotation(this.leftfoot, 0.0f, 0.0f, 0.0f);
        this.rightfoot = new ModelRenderer((ModelBase)this, 0, 16);
        this.rightfoot.addBox(-3.0f, 9.0f, -3.0f, 6, 3, 6);
        this.rightfoot.setRotationPoint(-4.0f, 12.0f, 0.0f);
        this.rightfoot.setTextureSize(64, 32);
        this.rightfoot.mirror = true;
        this.setRotation(this.rightfoot, 0.0f, 0.0f, 0.0f);
        this.back5 = new ModelRenderer((ModelBase)this, 4, 0);
        this.back5.addBox(0.0f, 0.0f, 0.0f, 4, 4, 5);
        this.back5.setRotationPoint(-2.0f, 0.0f, 2.0f);
        this.back5.setTextureSize(64, 32);
        this.back5.mirror = true;
        this.setRotation(this.back5, 0.0f, 0.0f, 0.0f);
        this.back6 = new ModelRenderer((ModelBase)this, 8, 0);
        this.back6.addBox(0.0f, 0.0f, 0.0f, 5, 2, 2);
        this.back6.setRotationPoint(2.0f, 0.0f, 5.0f);
        this.back6.setTextureSize(64, 32);
        this.back6.mirror = true;
        this.setRotation(this.back6, 0.0f, 0.0f, 0.0f);
        this.back7 = new ModelRenderer((ModelBase)this, 15, 25);
        this.back7.addBox(0.0f, 0.0f, 0.0f, 9, 2, 2);
        this.back7.setRotationPoint(5.0f, 0.0f, 5.0f);
        this.back7.setTextureSize(64, 32);
        this.back7.mirror = true;
        this.setRotation(this.back7, 0.0f, 0.0f, -1.570796f);
        this.back8 = new ModelRenderer((ModelBase)this, 8, 0);
        this.back8.addBox(0.0f, 0.0f, 0.0f, 5, 2, 2);
        this.back8.setRotationPoint(-7.0f, 0.0f, 5.0f);
        this.back8.setTextureSize(64, 32);
        this.back8.mirror = true;
        this.setRotation(this.back8, 0.0f, 0.0f, 0.0f);
        this.back9 = new ModelRenderer((ModelBase)this, 15, 25);
        this.back9.addBox(0.0f, -1.0f, 0.0f, 9, 2, 2);
        this.back9.setRotationPoint(-6.0f, 0.0f, 5.0f);
        this.back9.setTextureSize(64, 32);
        this.back9.mirror = true;
        this.setRotation(this.back9, 0.0f, 0.0f, -1.570796f);
        this.back10 = new ModelRenderer((ModelBase)this, 42, 5);
        this.back10.addBox(0.0f, 0.0f, 0.0f, 8, 2, 2);
        this.back10.setRotationPoint(-10.0f, 4.0f, 5.0f);
        this.back10.setTextureSize(64, 32);
        this.back10.mirror = true;
        this.setRotation(this.back10, 0.0f, 0.0f, 0.0f);
        this.back11 = new ModelRenderer((ModelBase)this, 42, 5);
        this.back11.addBox(0.0f, 0.0f, 0.0f, 8, 2, 2);
        this.back11.setRotationPoint(2.0f, 4.0f, 5.0f);
        this.back11.setTextureSize(64, 32);
        this.back11.mirror = true;
        this.setRotation(this.back11, 0.0f, 0.0f, 0.0f);
        this.back12 = new ModelRenderer((ModelBase)this, 34, 26);
        this.back12.addBox(0.0f, 0.0f, 0.0f, 12, 2, 2);
        this.back12.setRotationPoint(2.0f, 6.0f, 4.0f);
        this.back12.setTextureSize(64, 32);
        this.back12.mirror = true;
        this.setRotation(this.back12, 0.0f, 0.0f, 0.6108652f);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5);
        this.head.render(f5);
        this.body.render(f5);
        this.rightarmext.render(f5);
        this.leftarmext.render(f5);
        this.rightlegcap.render(f5);
        this.leftlegcap.render(f5);
        this.Shape1.render(f5);
        this.Shape2.render(f5);
        this.Shape3.render(f5);
        this.Shape4.render(f5);
        this.Shape5.render(f5);
        this.Shape6.render(f5);
        this.Shape7.render(f5);
        this.Shape8.render(f5);
        this.Shape9.render(f5);
        this.Shape10.render(f5);
        this.back.render(f5);
        this.back2.render(f5);
        this.back3.render(f5);
        this.back4.render(f5);
        this.leftleg.render(f5);
        this.rightleg.render(f5);
        this.leftarm.render(f5);
        this.rightarm.render(f5);
        this.leftfoot.render(f5);
        this.rightfoot.render(f5);
        this.back5.render(f5);
        this.back6.render(f5);
        this.back7.render(f5);
        this.back8.render(f5);
        this.back9.render(f5);
        this.back10.render(f5);
        this.back11.render(f5);
        this.back12.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float var1, float var2, float var3, float var4, float var5, float var6) {
        this.rightarm.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f + (float)Math.PI)) * 2.0f * var2 * 0.5f;
        this.rightarmext.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f + (float)Math.PI)) * 2.0f * var2 * 0.5f;
        this.leftarm.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 2.0f * var2 * 0.5f;
        this.leftarmext.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 2.0f * var2 * 0.5f;
        this.rightarm.rotateAngleZ = 0.0f;
        this.leftarm.rotateAngleZ = 0.0f;
        this.rightleg.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.rightfoot.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.rightlegcap.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f)) * 1.4f * var2;
        this.leftleg.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f + (float)Math.PI)) * 1.4f * var2;
        this.leftfoot.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f + (float)Math.PI)) * 1.4f * var2;
        this.leftlegcap.rotateAngleX = MathHelper.cos((float)(var1 * 0.6662f + (float)Math.PI)) * 1.4f * var2;
        this.rightleg.rotateAngleY = 0.0f;
        this.leftleg.rotateAngleY = 0.0f;
    }
}

