/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.block.Block
 *  net.minecraft.init.Blocks
 *  net.minecraft.init.Items
 *  net.minecraft.item.Item
 *  net.minecraft.item.ItemStack
 *  omegalevels.OmegaLevels
 */
package net.divinerpg.utils.recipes;

import net.divinerpg.utils.blocks.ArcanaBlocks;
import net.divinerpg.utils.blocks.IceikaBlocks;
import net.divinerpg.utils.blocks.TwilightBlocks;
import net.divinerpg.utils.blocks.VanillaBlocks;
import net.divinerpg.utils.items.ArcanaItems;
import net.divinerpg.utils.items.IceikaItems;
import net.divinerpg.utils.items.ItemsFood;
import net.divinerpg.utils.items.JourneyItemsOther;
import net.divinerpg.utils.items.JourneyItemsWeapon;
import net.divinerpg.utils.items.SkinItems;
import net.divinerpg.utils.items.TwilightItemsArmor;
import net.divinerpg.utils.items.TwilightItemsOther;
import net.divinerpg.utils.items.TwilightItemsWeapons;
import net.divinerpg.utils.items.VanillaItemsArmor;
import net.divinerpg.utils.items.VanillaItemsOther;
import net.divinerpg.utils.items.VanillaItemsTools;
import net.divinerpg.utils.items.VanillaItemsWeapons;
import net.divinerpg.utils.items.VetheaItems;
import net.divinerpg.utils.recipes.IS;
import net.divinerpg.utils.recipes.RecipeUtil;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import omegalevels.OmegaLevels;

public class VanillaRecipeHelper
extends RecipeUtil {
    public static void init() {
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.palavence, "I I", "III", " I ", Character.valueOf('I'), VanillaItemsOther.realmiteIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.massivence, "X X", "III", " I ", Character.valueOf('I'), VanillaItemsOther.netheriteIngot, Character.valueOf('X'), VanillaItemsOther.bloodgem);
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.frostSword, " I ", " I ", " S ", Character.valueOf('I'), IceikaItems.iceStone, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.bloodgemSword, " I ", " I ", " S ", Character.valueOf('I'), VanillaItemsOther.bloodgem, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.infernoSword, "BOB", "BOB", "BSB", Character.valueOf('B'), Items.blaze_powder, Character.valueOf('O'), Blocks.redstone_ore, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.moltenSword, " I ", " I ", " S ", Character.valueOf('I'), VanillaItemsOther.moltenStone, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.scorchingSword, " I ", " I ", " S ", Character.valueOf('I'), VanillaItemsOther.purpleBlaze, Character.valueOf('S'), VanillaItemsOther.netheriteIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.bluefireSword, " I ", " I ", " S ", Character.valueOf('I'), VanillaItemsOther.bluefireStone, Character.valueOf('S'), VanillaItemsOther.shadowBar);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.flamingFury, "XIX", "XIX", "XOX", Character.valueOf('I'), VanillaItemsOther.furyFire, Character.valueOf('X'), VanillaItemsWeapons.infernoSword, Character.valueOf('O'), VanillaItemsOther.shadowBar);
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.poisonSaber, " R ", "BRB", "BSB", Character.valueOf('R'), VanillaItemsOther.jungleStone, Character.valueOf('B'), VanillaItemsOther.shadowBar, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.enderSword, " L ", " L ", " S ", Character.valueOf('L'), VanillaItemsOther.legendaryEnderEye, Character.valueOf('S'), VanillaItemsOther.shadowBar);
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.arlemiteSword, " I ", " I ", " S ", Character.valueOf('I'), VanillaItemsOther.arlemiteIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.rupeeSword, " I ", " I ", " S ", Character.valueOf('I'), VanillaItemsOther.rupeeIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.realmiteSword, " I ", " I ", " S ", Character.valueOf('I'), VanillaItemsOther.realmiteIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.slimeSword, "SDS", "SDS", "SDS", Character.valueOf('D'), Items.diamond_sword, Character.valueOf('S'), Items.slime_ball);
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.oceanKnife, " I ", " I ", " S ", Character.valueOf('I'), VanillaItemsOther.aquaticIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.aquaticDagger, "   ", " I ", " S ", Character.valueOf('I'), VanillaItemsOther.aquaticIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.aquaticMaul, "III", "III", "ISI", Character.valueOf('I'), VanillaItemsOther.aquaticIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.aquaticTrident, " I ", "III", " S ", Character.valueOf('I'), VanillaItemsOther.aquaticIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.aquaton, "III", "III", " S ", Character.valueOf('I'), VanillaItemsOther.aquaticIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.sharkSword, " I ", " I ", " S ", Character.valueOf('I'), VanillaItemsOther.sharkFin, Character.valueOf('S'), VanillaItemsOther.aquaticIngot);
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.crabclawMaul, "III", "ISI", " S ", Character.valueOf('I'), VanillaItemsOther.crabClaw, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.bedrockSword, " B ", " B ", " S ", Character.valueOf('B'), Blocks.bedrock, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.divineSword, " I ", "III", " S ", Character.valueOf('I'), VanillaItemsOther.divineStone, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.furyMaul, "OBO", "BBB", "OBO", Character.valueOf('B'), Blocks.bedrock, Character.valueOf('O'), Blocks.diamond_ore);
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.deathBringer, " I ", "ISI", " S ", Character.valueOf('I'), VanillaItemsOther.corruptedStone, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.corruptedMaul, "III", "ISI", " S ", Character.valueOf('I'), VanillaItemsOther.corruptedStone, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.bedrockMaul, " B ", "BBB", " I ", Character.valueOf('B'), Blocks.bedrock, Character.valueOf('I'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.jungleKnife, " I ", " I ", " S ", Character.valueOf('I'), VanillaItemsOther.jungleStone, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.cyclopsianSword, " E ", " E ", " S ", Character.valueOf('E'), VanillaItemsOther.cyclopsEye, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.cyclopsianStaff, " E ", " S ", " S ", Character.valueOf('E'), VanillaItemsOther.cyclopsEye, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsWeapons.dualClaw), " C ", "AAA", " C ", Character.valueOf('C'), VanillaItemsOther.crabClaw, Character.valueOf('A'), VanillaItemsOther.aquaticIngot);
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.terranDagger, " T ", " S ", Character.valueOf('T'), VanillaItemsOther.terranStone, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.terranKnife, " T ", " T ", " S ", Character.valueOf('T'), VanillaItemsOther.terranStone, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.terranMaul, "TTT", " T ", " S ", Character.valueOf('T'), VanillaItemsOther.terranStone, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.aquatoothSword, " T ", "TKT", " S ", Character.valueOf('T'), VanillaItemsOther.liopleurodonTeeth, Character.valueOf('K'), VanillaItemsOther.liopleurodonSkull, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.aquatoothMaul, "TKT", "TKT", "KSK", Character.valueOf('T'), VanillaItemsOther.liopleurodonTeeth, Character.valueOf('K'), VanillaItemsOther.liopleurodonSkull, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsWeapons.jungleRapier), "S S", "SBS", " B ", Character.valueOf('S'), VanillaItemsOther.jungleStone, Character.valueOf('B'), VanillaItemsOther.shadowBar);
        VanillaRecipeHelper.addRecipe(IS.shuriken, " I ", "III", " I ", Character.valueOf('I'), Items.iron_ingot);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsWeapons.vileStorm, 8), "SSS", "SJS", "SSS", Character.valueOf('J'), VanillaItemsOther.jungleShards, Character.valueOf('S'), VanillaItemsWeapons.shuriken);
        VanillaRecipeHelper.addRecipe(IceikaItems.soundOfMusic, "III", "IXI", "III", Character.valueOf('I'), VanillaItemsOther.purpleBlaze, Character.valueOf('X'), Items.string);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.maelstrom, "III", "IXI", "III", Character.valueOf('I'), VanillaItemsOther.purpleBlaze, Character.valueOf('X'), Items.book);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.ghastCannon, "I I", "I I", "XXX", Character.valueOf('I'), VanillaItemsOther.shadowBar, Character.valueOf('X'), VanillaItemsOther.hellstoneIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.liopleurodonAnchor, "SIS", "IXI", " X ", Character.valueOf('I'), VanillaItemsOther.liopleurodonTeeth, Character.valueOf('X'), VanillaItemsOther.aquaticIngot, Character.valueOf('S'), VanillaItemsOther.liopleurodonSkull);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.bowheadAnchor, "III", "IXI", " X ", Character.valueOf('I'), VanillaItemsOther.whaleFin, Character.valueOf('X'), VanillaItemsOther.aquaticIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.sharkAnchor, "III", "IXI", " X ", Character.valueOf('I'), VanillaItemsOther.sharkFin, Character.valueOf('X'), VanillaItemsOther.aquaticIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.crabAnchor, "III", "IXI", " X ", Character.valueOf('I'), VanillaItemsOther.crabClaw, Character.valueOf('X'), VanillaItemsOther.aquaticIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.hunterBow, " IX", "I X", " IX", Character.valueOf('I'), VanillaItemsOther.jungleStone, Character.valueOf('X'), Items.string);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.shadowBow, " IX", "I X", " IX", Character.valueOf('I'), VanillaItemsOther.shadowBar, Character.valueOf('X'), Items.string);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.enderBow, " IX", "E X", " IX", Character.valueOf('I'), VanillaItemsOther.enderStone, Character.valueOf('X'), Items.string, Character.valueOf('E'), VanillaItemsOther.watchingEye);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.bluefireBow, " IX", "I X", " IX", Character.valueOf('I'), VanillaItemsOther.aquaticBlazeRod, Character.valueOf('X'), VanillaItemsOther.bluefireStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.infernoBow, " IX", "I X", " IX", Character.valueOf('I'), VanillaItemsOther.moltenStone, Character.valueOf('X'), Items.blaze_powder);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.frostCannon, "I I", "I I", "XXX", Character.valueOf('I'), VanillaItemsOther.shadowBar, Character.valueOf('X'), IceikaItems.iceStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.bowheadCannon, " I ", " I ", " X ", Character.valueOf('I'), VanillaItemsOther.whaleFin, Character.valueOf('X'), VanillaItemsOther.aquaticIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.crabclawCannon, " I ", " I ", " X ", Character.valueOf('I'), VanillaItemsOther.crabClaw, Character.valueOf('X'), VanillaItemsOther.aquaticIngot);
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsWeapons.corruptedCannon, "III", "S S", Character.valueOf('I'), VanillaItemsOther.corruptedStone, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.goldenFury, "GGG", "GFG", "FFF", Character.valueOf('F'), VanillaItemsOther.furyFire, Character.valueOf('G'), Blocks.gold_block);
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.realmitePickaxe, "III", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.realmiteIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.realmiteShovel, " I ", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.realmiteIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.realmiteAxe, "II ", "IS ", " S ", Character.valueOf('I'), VanillaItemsOther.realmiteIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.realmiteHoe, "II ", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.realmiteIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.corruptedPickaxe, "III", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.corruptedStone, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.corruptedShovel, " I ", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.corruptedStone, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.corruptedAxe, "II ", "IS ", " S ", Character.valueOf('I'), VanillaItemsOther.corruptedStone, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.bedrockPickaxe, "III", " S ", " S ", Character.valueOf('I'), Blocks.bedrock, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.bedrockShovel, " I ", " S ", " S ", Character.valueOf('I'), Blocks.bedrock, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.bedrockAxe, "II ", "IS ", " S ", Character.valueOf('I'), Blocks.bedrock, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.arlemitePickaxe, "III", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.arlemiteIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.arlemiteShovel, " I ", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.arlemiteIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.arlemiteAxe, "II ", "IS ", " S ", Character.valueOf('I'), VanillaItemsOther.arlemiteIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.arlemiteHoe, "II ", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.arlemiteIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsTools.arlemiteShickaxe, VanillaItemsTools.arlemitePickaxe, VanillaItemsTools.arlemiteShovel, VanillaItemsTools.arlemiteAxe, VanillaItemsTools.arlemiteHoe);
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.rupeePickaxe, "III", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.rupeeIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.rupeeShovel, " I ", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.rupeeIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.rupeeAxe, "II ", "IS ", " S ", Character.valueOf('I'), VanillaItemsOther.rupeeIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.rupeeHoe, "II ", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.rupeeIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsTools.rupeeShickaxe, VanillaItemsTools.rupeePickaxe, VanillaItemsTools.rupeeShovel, VanillaItemsTools.rupeeAxe, VanillaItemsTools.rupeeHoe);
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.divinePickaxe, "III", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.divineStone, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.divineShovel, " I ", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.divineStone, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.divineAxe, "II ", "IS ", " S ", Character.valueOf('I'), VanillaItemsOther.divineStone, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsTools.divineShickaxe, VanillaItemsTools.divinePickaxe, VanillaItemsTools.divineShovel, VanillaItemsTools.divineAxe);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.serenadeStriker, "I  ", "III", "  I", Character.valueOf('I'), Items.diamond);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.serenadeOfHealth, "I  ", "III", "  I", Character.valueOf('I'), VanillaItemsOther.netheriteChunk);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.serenadeOfDeath, "I  ", "III", "  I", Character.valueOf('I'), VanillaItemsOther.shadowBar);
        VanillaRecipeHelper.removeCraftingRecipe((Item)Items.diamond_chestplate);
        VanillaRecipeHelper.removeCraftingRecipe((Item)Items.diamond_leggings);
        VanillaRecipeHelper.removeCraftingRecipe((Item)Items.diamond_boots);
        VanillaRecipeHelper.removeCraftingRecipe((Item)Items.diamond_helmet);
        VanillaRecipeHelper.removeCraftingRecipe((Item)Items.golden_chestplate);
        VanillaRecipeHelper.removeCraftingRecipe((Item)Items.golden_leggings);
        VanillaRecipeHelper.removeCraftingRecipe((Item)Items.golden_boots);
        VanillaRecipeHelper.removeCraftingRecipe((Item)Items.golden_helmet);
        VanillaRecipeHelper.removeCraftingRecipe((Item)Items.iron_chestplate);
        VanillaRecipeHelper.removeCraftingRecipe((Item)Items.iron_leggings);
        VanillaRecipeHelper.removeCraftingRecipe((Item)Items.iron_boots);
        VanillaRecipeHelper.removeCraftingRecipe((Item)Items.iron_helmet);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.amazoniteHelmet, "III", "I I", Character.valueOf('I'), VanillaItemsOther.amazonite);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.amazoniteChestplate, "I I", "III", "III", Character.valueOf('I'), VanillaItemsOther.amazonite);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.amazoniteLeggings, "III", "I I", "I I", Character.valueOf('I'), VanillaItemsOther.amazonite);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.amazoniteBoots, "I I", "I I", Character.valueOf('I'), VanillaItemsOther.amazonite);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.copperHelmet, "III", "I I", Character.valueOf('I'), VanillaItemsOther.copperIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.copperChestplate, "I I", "III", "III", Character.valueOf('I'), VanillaItemsOther.copperIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.copperLeggings, "III", "I I", "I I", Character.valueOf('I'), VanillaItemsOther.copperIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.copperBoots, "I I", "I I", Character.valueOf('I'), VanillaItemsOther.copperIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.nightmareHelmet, "III", "I I", Character.valueOf('I'), VanillaItemsOther.nightmareSteel);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.nightmareChestplate, "I I", "III", "III", Character.valueOf('I'), VanillaItemsOther.nightmareSteel);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.nightmareLeggings, "III", "I I", "I I", Character.valueOf('I'), VanillaItemsOther.nightmareSteel);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.nightmareBoots, "I I", "I I", Character.valueOf('I'), VanillaItemsOther.nightmareSteel);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.netheriumHelmet, "III", "I I", Character.valueOf('I'), VanillaItemsOther.netheriumIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.netheriumChestplate, "I I", "III", "III", Character.valueOf('I'), VanillaItemsOther.netheriumIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.netheriumLeggings, "III", "I I", "I I", Character.valueOf('I'), VanillaItemsOther.netheriumIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.netheriumBoots, "I I", "I I", Character.valueOf('I'), VanillaItemsOther.netheriumIngot);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.copperBlock, "III", "III", "III", Character.valueOf('I'), VanillaItemsOther.copperIngot);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.nightmareBlock, "III", "III", "III", Character.valueOf('I'), VanillaItemsOther.nightmareSteel);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsOther.nightmareSteel, 9), "I", Character.valueOf('I'), VanillaBlocks.nightmareBlock);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsOther.copperIngot, 9), "I", Character.valueOf('I'), VanillaBlocks.copperBlock);
        VanillaRecipeHelper.addSmelting(VanillaBlocks.copperOre, VanillaItemsOther.copperIngot, 0.6f);
        VanillaRecipeHelper.addSmelting(VanillaBlocks.amazoniteOre, VanillaItemsOther.amazonite, 1.4f);
        VanillaRecipeHelper.addSmelting(VanillaBlocks.nightmareOre, VanillaItemsOther.nightmareSteel, 1.7f);
        VanillaRecipeHelper.addSmelting(VanillaItemsOther.netheriumShards, VanillaItemsOther.netheriumIngot, 1.0f);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.HeavySwordD, "  I", " I ", "S  ", Character.valueOf('I'), Blocks.diamond_block, Character.valueOf('S'), Items.stick);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.ironHeavySword, "  I", " I ", "S  ", Character.valueOf('I'), Blocks.iron_block, Character.valueOf('S'), Items.stick);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.copperHeavySword, "  I", " I ", "S  ", Character.valueOf('I'), VanillaBlocks.copperBlock, Character.valueOf('S'), Items.stick);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.copperSword, " I ", " I ", " S ", Character.valueOf('I'), VanillaItemsOther.copperIngot, Character.valueOf('S'), Items.stick);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.amazoniteSword, " I ", " I ", " S ", Character.valueOf('I'), VanillaItemsOther.amazonite, Character.valueOf('S'), Items.stick);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.nightmareSword, " I ", " I ", " S ", Character.valueOf('I'), VanillaItemsOther.nightmareSteel, Character.valueOf('S'), Items.stick);
        VanillaRecipeHelper.addRecipe(VanillaItemsWeapons.netheriumSword, " I ", "AIA", " S ", Character.valueOf('I'), VanillaItemsOther.netheriumIngot, Character.valueOf('S'), Items.stick, Character.valueOf('A'), VanillaItemsOther.netheriumShards);
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.amazonitePick, "III", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.amazonite, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.amazoniteShovel, " I ", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.amazonite, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.amazoniteAxe, "II ", "IS ", " S ", Character.valueOf('I'), VanillaItemsOther.amazonite, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.copperPick, "III", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.copperIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.copperShovel, " I ", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.copperIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.copperAxe, "II ", "IS ", " S ", Character.valueOf('I'), VanillaItemsOther.copperIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.nightmarePick, "III", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.nightmareSteel, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.nightmareShovel, " I ", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.nightmareSteel, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.nightmareAxe, "II ", "IS ", " S ", Character.valueOf('I'), VanillaItemsOther.nightmareSteel, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.netheriumPick, "III", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.netheriumIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.netheriumShovel, " I ", " S ", " S ", Character.valueOf('I'), VanillaItemsOther.netheriumIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addOredictRecipe(VanillaItemsTools.netheriumAxe, "II ", "IS ", " S ", Character.valueOf('I'), VanillaItemsOther.netheriumIngot, Character.valueOf('S'), "stickWood");
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.diamondHelmet, "III", "I I", Character.valueOf('I'), Items.diamond);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.diamondBody, "I I", "III", "III", Character.valueOf('I'), Items.diamond);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.diamondLegs, "III", "I I", "I I", Character.valueOf('I'), Items.diamond);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.diamondBoots, "I I", "I I", Character.valueOf('I'), Items.diamond);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.ironHelmet, "III", "I I", Character.valueOf('I'), Items.iron_ingot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.ironBody, "I I", "III", "III", Character.valueOf('I'), Items.iron_ingot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.ironLegs, "III", "I I", "I I", Character.valueOf('I'), Items.iron_ingot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.ironBoots, "I I", "I I", Character.valueOf('I'), Items.iron_ingot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.goldHelmet, "III", "I I", Character.valueOf('I'), Items.gold_ingot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.goldBody, "I I", "III", "III", Character.valueOf('I'), Items.gold_ingot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.goldLegs, "III", "I I", "I I", Character.valueOf('I'), Items.gold_ingot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.goldBoots, "I I", "I I", Character.valueOf('I'), Items.gold_ingot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.realmiteHelmet, "III", "I I", Character.valueOf('I'), VanillaItemsOther.realmiteIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.realmiteBody, "I I", "III", "III", Character.valueOf('I'), VanillaItemsOther.realmiteIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.realmiteLegs, "III", "I I", "I I", Character.valueOf('I'), VanillaItemsOther.realmiteIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.realmiteBoots, "I I", "I I", Character.valueOf('I'), VanillaItemsOther.realmiteIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.eliteRealmiteHelmet, "III", "I I", Character.valueOf('I'), VanillaBlocks.realmiteBlock);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.eliteRealmiteBody, "I I", "III", "III", Character.valueOf('I'), VanillaBlocks.realmiteBlock);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.eliteRealmiteLegs, "III", "I I", "I I", Character.valueOf('I'), VanillaBlocks.realmiteBlock);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.eliteRealmiteBoots, "I I", "I I", Character.valueOf('I'), VanillaBlocks.realmiteBlock);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.bedrockHelmet, "III", "I I", Character.valueOf('I'), Blocks.bedrock);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.bedrockBody, "I I", "III", "III", Character.valueOf('I'), Blocks.bedrock);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.bedrockLegs, "III", "I I", "I I", Character.valueOf('I'), Blocks.bedrock);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.bedrockBoots, "I I", "I I", Character.valueOf('I'), Blocks.bedrock);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.rupeeHelmet, "III", "I I", Character.valueOf('I'), VanillaItemsOther.rupeeIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.rupeeBody, "I I", "III", "III", Character.valueOf('I'), VanillaItemsOther.rupeeIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.rupeeLegs, "III", "I I", "I I", Character.valueOf('I'), VanillaItemsOther.rupeeIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.rupeeBoots, "I I", "I I", Character.valueOf('I'), VanillaItemsOther.rupeeIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.arlemiteHelmet, "III", "X X", Character.valueOf('I'), VanillaItemsOther.arlemiteIngot, Character.valueOf('X'), Items.iron_ingot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.arlemiteBody, "I I", "XIX", "IXI", Character.valueOf('I'), VanillaItemsOther.arlemiteIngot, Character.valueOf('X'), Items.iron_ingot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.arlemiteLegs, "III", "X X", "I I", Character.valueOf('I'), VanillaItemsOther.arlemiteIngot, Character.valueOf('X'), Items.iron_ingot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.arlemiteBoots, "X X", "I I", Character.valueOf('I'), VanillaItemsOther.arlemiteIngot, Character.valueOf('X'), Items.iron_ingot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.infernoHelmet, "III", "I I", Character.valueOf('I'), VanillaItemsOther.moltenStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.infernoBody, "I I", "III", "III", Character.valueOf('I'), VanillaItemsOther.moltenStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.infernoLegs, "III", "I I", "I I", Character.valueOf('I'), VanillaItemsOther.moltenStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.infernoBoots, "I I", "I I", Character.valueOf('I'), VanillaItemsOther.moltenStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.netheriteHelmet, "III", "S S", Character.valueOf('I'), VanillaBlocks.netheriteBlock, Character.valueOf('S'), VanillaItemsOther.shadowBar);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.netheriteBody, "S S", "III", "III", Character.valueOf('I'), VanillaBlocks.netheriteBlock, Character.valueOf('S'), VanillaItemsOther.shadowBar);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.netheriteLegs, "III", "S S", "I I", Character.valueOf('I'), VanillaBlocks.netheriteBlock, Character.valueOf('S'), VanillaItemsOther.shadowBar);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.netheriteBoots, "S S", "I I", Character.valueOf('I'), VanillaBlocks.netheriteBlock, Character.valueOf('S'), VanillaItemsOther.shadowBar);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.enderHelmet, "III", "I I", Character.valueOf('I'), VanillaItemsOther.enderStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.enderBody, "I I", "III", "III", Character.valueOf('I'), VanillaItemsOther.enderStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.enderLegs, "III", "I I", "I I", Character.valueOf('I'), VanillaItemsOther.enderStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.enderBoots, "I I", "I I", Character.valueOf('I'), VanillaItemsOther.enderStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.divineHelmet, "III", "I I", Character.valueOf('I'), VanillaItemsOther.divineStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.divineBody, "I I", "III", "III", Character.valueOf('I'), VanillaItemsOther.divineStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.divineLegs, "III", "I I", "I I", Character.valueOf('I'), VanillaItemsOther.divineStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.divineBoots, "I I", "I I", Character.valueOf('I'), VanillaItemsOther.divineStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.shadowHelmet, "IXI", "X X", Character.valueOf('I'), VanillaItemsOther.shadowStone, Character.valueOf('X'), VanillaItemsOther.shadowBar);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.shadowBody, "X X", "IXI", "IXI", Character.valueOf('I'), VanillaItemsOther.shadowStone, Character.valueOf('X'), VanillaItemsOther.shadowBar);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.shadowLegs, "IXI", "X X", "X X", Character.valueOf('I'), VanillaItemsOther.shadowStone, Character.valueOf('X'), VanillaItemsOther.shadowBar);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.shadowBoots, "X X", "I I", Character.valueOf('I'), VanillaItemsOther.shadowStone, Character.valueOf('X'), VanillaItemsOther.shadowBar);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.aquastriveHelmet, "III", "I I", Character.valueOf('I'), VanillaItemsOther.aquaticIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.aquastriveBody, "I I", "III", "III", Character.valueOf('I'), VanillaItemsOther.aquaticIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.aquastriveLegs, "III", "I I", "I I", Character.valueOf('I'), VanillaItemsOther.aquaticIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.aquastriveBoots, "I I", "I I", Character.valueOf('I'), VanillaItemsOther.aquaticIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.krakenHelmet, "III", "I I", Character.valueOf('I'), VanillaItemsOther.krakenSkin);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.krakenBody, "I I", "III", "III", Character.valueOf('I'), VanillaItemsOther.krakenSkin);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.krakenLegs, "III", "I I", "I I", Character.valueOf('I'), VanillaItemsOther.krakenSkin);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.krakenBoots, "I I", "I I", Character.valueOf('I'), VanillaItemsOther.krakenSkin);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.jungleHelmet, "III", "I I", Character.valueOf('I'), VanillaItemsOther.jungleStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.jungleBody, "I I", "III", "III", Character.valueOf('I'), VanillaItemsOther.jungleStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.jungleLegs, "III", "I I", "I I", Character.valueOf('I'), VanillaItemsOther.jungleStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.jungleBoots, "I I", "I I", Character.valueOf('I'), VanillaItemsOther.jungleStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.frozenHelmet, "III", "I I", Character.valueOf('I'), IceikaItems.iceStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.frozenBody, "I I", "III", "III", Character.valueOf('I'), IceikaItems.iceStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.frozenLegs, "III", "I I", "I I", Character.valueOf('I'), IceikaItems.iceStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.frozenBoots, "I I", "I I", Character.valueOf('I'), IceikaItems.iceStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.corruptedHelmet, "III", "I I", Character.valueOf('I'), VanillaItemsOther.corruptedStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.corruptedBody, "I I", "III", "III", Character.valueOf('I'), VanillaItemsOther.corruptedStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.corruptedLegs, "III", "I I", "I I", Character.valueOf('I'), VanillaItemsOther.corruptedStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.corruptedBoots, "I I", "I I", Character.valueOf('I'), VanillaItemsOther.corruptedStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.terranHelmet, "III", "I I", Character.valueOf('I'), VanillaItemsOther.terranStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.terranBody, "I I", "III", "III", Character.valueOf('I'), VanillaItemsOther.terranStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.terranLegs, "III", "I I", "I I", Character.valueOf('I'), VanillaItemsOther.terranStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsArmor.terranBoots, "I I", "I I", Character.valueOf('I'), VanillaItemsOther.terranStone);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.redRupeeHelmet, VanillaItemsArmor.rupeeHelmet, VanillaItemsOther.redDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.redRupeeBody, VanillaItemsArmor.rupeeBody, VanillaItemsOther.redDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.redRupeeLegs, VanillaItemsArmor.rupeeLegs, VanillaItemsOther.redDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.redRupeeBoots, VanillaItemsArmor.rupeeBoots, VanillaItemsOther.redDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.greenRupeeHelmet, VanillaItemsArmor.rupeeHelmet, VanillaItemsOther.greenDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.greenRupeeBody, VanillaItemsArmor.rupeeBody, VanillaItemsOther.greenDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.greenRupeeLegs, VanillaItemsArmor.rupeeLegs, VanillaItemsOther.greenDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.greenRupeeBoots, VanillaItemsArmor.rupeeBoots, VanillaItemsOther.greenDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.blueRupeeHelmet, VanillaItemsArmor.rupeeHelmet, VanillaItemsOther.blueDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.blueRupeeBody, VanillaItemsArmor.rupeeBody, VanillaItemsOther.blueDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.blueRupeeLegs, VanillaItemsArmor.rupeeLegs, VanillaItemsOther.blueDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.blueRupeeBoots, VanillaItemsArmor.rupeeBoots, VanillaItemsOther.blueDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.yellowRupeeHelmet, VanillaItemsArmor.rupeeHelmet, VanillaItemsOther.yellowDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.yellowRupeeBody, VanillaItemsArmor.rupeeBody, VanillaItemsOther.yellowDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.yellowRupeeLegs, VanillaItemsArmor.rupeeLegs, VanillaItemsOther.yellowDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.yellowRupeeBoots, VanillaItemsArmor.rupeeBoots, VanillaItemsOther.yellowDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.grayRupeeHelmet, VanillaItemsArmor.rupeeHelmet, VanillaItemsOther.grayDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.grayRupeeBody, VanillaItemsArmor.rupeeBody, VanillaItemsOther.grayDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.grayRupeeLegs, VanillaItemsArmor.rupeeLegs, VanillaItemsOther.grayDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.grayRupeeBoots, VanillaItemsArmor.rupeeBoots, VanillaItemsOther.grayDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.redEnderHelmet, VanillaItemsArmor.enderHelmet, VanillaItemsOther.redDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.redEnderBody, VanillaItemsArmor.enderBody, VanillaItemsOther.redDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.redEnderLegs, VanillaItemsArmor.enderLegs, VanillaItemsOther.redDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.redEnderBoots, VanillaItemsArmor.enderBoots, VanillaItemsOther.redDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.greenEnderHelmet, VanillaItemsArmor.enderHelmet, VanillaItemsOther.greenDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.greenEnderBody, VanillaItemsArmor.enderBody, VanillaItemsOther.greenDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.greenEnderLegs, VanillaItemsArmor.enderLegs, VanillaItemsOther.greenDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.greenEnderBoots, VanillaItemsArmor.enderBoots, VanillaItemsOther.greenDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.blueEnderHelmet, VanillaItemsArmor.enderHelmet, VanillaItemsOther.blueDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.blueEnderBody, VanillaItemsArmor.enderBody, VanillaItemsOther.blueDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.blueEnderLegs, VanillaItemsArmor.enderLegs, VanillaItemsOther.blueDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.blueEnderBoots, VanillaItemsArmor.enderBoots, VanillaItemsOther.blueDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.yellowEnderHelmet, VanillaItemsArmor.enderHelmet, VanillaItemsOther.yellowDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.yellowEnderBody, VanillaItemsArmor.enderBody, VanillaItemsOther.yellowDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.yellowEnderLegs, VanillaItemsArmor.enderLegs, VanillaItemsOther.yellowDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.yellowEnderBoots, VanillaItemsArmor.enderBoots, VanillaItemsOther.yellowDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.grayEnderHelmet, VanillaItemsArmor.enderHelmet, VanillaItemsOther.grayDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.grayEnderBody, VanillaItemsArmor.enderBody, VanillaItemsOther.grayDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.grayEnderLegs, VanillaItemsArmor.enderLegs, VanillaItemsOther.grayDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsArmor.grayEnderBoots, VanillaItemsArmor.enderBoots, VanillaItemsOther.grayDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsOther.redDiamondChunk, Items.diamond, VanillaItemsOther.netheriteChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsOther.greenDiamondChunk, Items.diamond, VanillaItemsOther.arlemiteIngot);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsOther.blueDiamondChunk, Items.diamond, VanillaItemsOther.rupeeIngot);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsOther.yellowDiamondChunk, Items.diamond, VanillaItemsOther.realmiteIngot);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsOther.grayDiamondChunk, Items.diamond, VanillaItemsOther.shadowBar);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsWeapons.redDivineSword, VanillaItemsWeapons.divineSword, VanillaItemsOther.redDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsWeapons.yellowDivineSword, VanillaItemsWeapons.divineSword, VanillaItemsOther.yellowDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsWeapons.greenDivineSword, VanillaItemsWeapons.divineSword, VanillaItemsOther.greenDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsWeapons.blueDivineSword, VanillaItemsWeapons.divineSword, VanillaItemsOther.blueDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsWeapons.grayDivineSword, VanillaItemsWeapons.divineSword, VanillaItemsOther.grayDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsWeapons.redEnderSword, VanillaItemsWeapons.enderSword, VanillaItemsOther.redDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsWeapons.yellowEnderSword, VanillaItemsWeapons.enderSword, VanillaItemsOther.yellowDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsWeapons.greenEnderSword, VanillaItemsWeapons.enderSword, VanillaItemsOther.greenDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsWeapons.blueEnderSword, VanillaItemsWeapons.enderSword, VanillaItemsOther.blueDiamondChunk);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsWeapons.grayEnderSword, VanillaItemsWeapons.enderSword, VanillaItemsOther.grayDiamondChunk);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.netheriteChunk, " I ", "III", " I ", Character.valueOf('I'), VanillaItemsOther.netheriteIngot);
        VanillaRecipeHelper.addShapelessRecipe(IS.eyeShards, VanillaItemsOther.cyclopsEye);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaItemsOther.corruptedBullet, 16), VanillaItemsOther.corruptedShards);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.arlemiteBlock, "III", "III", "III", Character.valueOf('I'), VanillaItemsOther.arlemiteIngot);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.rupeeBlock, "III", "III", "III", Character.valueOf('I'), VanillaItemsOther.rupeeIngot);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.realmiteBlock, "III", "III", "III", Character.valueOf('I'), VanillaItemsOther.realmiteIngot);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.netheriteBlock, "III", "III", "III", Character.valueOf('I'), VanillaItemsOther.netheriteIngot);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.bloodgemBlock, "III", "III", "III", Character.valueOf('I'), VanillaItemsOther.bloodgem);
        VanillaRecipeHelper.addRecipe(new ItemStack(ArcanaBlocks.arcanaPortalFrame, 12), " c ", "iii", " c ", Character.valueOf('c'), VanillaItemsOther.bluefireStone, Character.valueOf('i'), Blocks.iron_block);
        VanillaRecipeHelper.addRecipe(new ItemStack(ArcanaItems.regenArcanaPotion, 4), " S ", "SAS", "SAS", Character.valueOf('A'), ArcanaItems.arcanium, Character.valueOf('S'), VanillaItemsOther.nightmareSteel);
        VanillaRecipeHelper.addRecipe(TwilightItemsOther.twilightClock, " X ", "XCX", " X ", Character.valueOf('C'), Items.clock, Character.valueOf('X'), Items.diamond);
        VanillaRecipeHelper.addRecipe(IceikaItems.snowGlobe, " G ", "GSG", "DBD", Character.valueOf('G'), Blocks.glass, Character.valueOf('S'), Blocks.snow, Character.valueOf('D'), Items.diamond, Character.valueOf('B'), VanillaItemsOther.shadowBar);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.mysteriousClock, " H ", "SCS", " S ", Character.valueOf('C'), Items.clock, Character.valueOf('S'), VanillaItemsOther.corruptedStone, Character.valueOf('H'), VanillaItemsOther.hellstoneIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.callWatcher, " H ", "SES", " S ", Character.valueOf('E'), VanillaItemsOther.watchingEye, Character.valueOf('S'), VanillaItemsOther.moltenStone, Character.valueOf('H'), VanillaItemsOther.hellstoneIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.hordeHorn, " H ", "SES", " S ", Character.valueOf('E'), Items.ender_eye, Character.valueOf('S'), VanillaItemsOther.enderStone, Character.valueOf('H'), VanillaItemsOther.hellstoneIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.infernalFlame, "BBB", "BSB", "BBB", Character.valueOf('B'), VanillaItemsOther.purpleBlaze, Character.valueOf('S'), VanillaItemsWeapons.infernoSword);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.steel, 1, 0), "xxx", "xyx", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), new ItemStack(Items.dye, 1, 6));
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.steel, 1, 1), "xxx", "xyx", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), new ItemStack(Items.dye, 1, 1));
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.steel, 1, 2), "xxx", "xyx", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), new ItemStack(Items.dye, 1, 5));
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.steel, 1, 3), "xxx", "xyx", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), new ItemStack(Items.dye, 1, 2));
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.steel, 1, 4), "xxx", "xyx", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), new ItemStack(Items.dye, 1, 11));
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.steel, 1, 5), "xxx", "xyx", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), new ItemStack(Items.dye, 1, 4));
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.steel, 1, 6), "xxx", "xyx", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), new ItemStack(Items.dye, 1, 15));
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.steel, 1, 7), "xxx", "xyx", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), new ItemStack(Items.dye, 1, 0));
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.steel, 1, 8), "xxx", "xyx", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), new ItemStack(Items.dye, 1, 14));
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.steel, 1, 9), "xxx", "xyx", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), new ItemStack(Items.dye, 1, 13));
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.milkStone, 4), Blocks.stone, Blocks.stone, Blocks.stone, Items.milk_bucket);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.divineBricks, 4, 13), Blocks.stonebrick, Blocks.stonebrick, Blocks.stonebrick, Items.redstone);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.divineBricks, 4, 5), Blocks.stonebrick, Blocks.stonebrick, Blocks.stonebrick, new ItemStack(Items.dye, 1, 2));
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.divineBricks, 4, 10), Blocks.stonebrick, Blocks.stonebrick, Blocks.stonebrick, new ItemStack(Items.dye, 1, 9));
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.divineBricks, 4, 11), Blocks.stonebrick, Blocks.stonebrick, Blocks.stonebrick, new ItemStack(Items.dye, 1, 5));
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.divineBricks, 4, 7), Blocks.stonebrick, Blocks.stonebrick, Blocks.stonebrick, new ItemStack(Items.dye, 1, 4));
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.divineBricks, 4, 3), Blocks.stonebrick, Blocks.stonebrick, Blocks.stonebrick, Items.diamond);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.divineBricks, 4, 9), VanillaItemsOther.netheriteIngot);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.divineBricks, 4, 12), VanillaItemsOther.realmiteIngot, VanillaItemsOther.realmiteIngot, VanillaItemsOther.realmiteIngot, VanillaItemsOther.realmiteIngot, VanillaItemsOther.realmiteIngot);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.divineBricks, 4, 4), Blocks.stonebrick, Blocks.stonebrick, Blocks.stonebrick, Items.gold_ingot);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.divineBricks, 4, 8), Blocks.stonebrick, Blocks.stonebrick, Blocks.stonebrick, Items.lava_bucket);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.divineBricks, 4, 6), Blocks.stonebrick, Blocks.stonebrick, Blocks.stonebrick, Items.iron_ingot);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.divineBricks, 4, 2), Blocks.stonebrick, Blocks.stonebrick, Blocks.stonebrick, new ItemStack(Items.dye, 1, 0));
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.divineBricks, 4, 14), VanillaBlocks.milkStone, VanillaBlocks.milkStone, VanillaBlocks.milkStone, VanillaBlocks.milkStone);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.divineBricks, 4, 0), VanillaItemsOther.aquaBall, Blocks.stonebrick, Blocks.stonebrick, Blocks.stonebrick);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.divineBricks, 10, 1), "xyx", "yxy", "xyx", Character.valueOf('x'), VanillaItemsOther.arlemiteIngot, Character.valueOf('y'), Blocks.stonebrick);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.minibricks, 4, 3), "XXX", "XXX", "XXX", Character.valueOf('X'), Blocks.stonebrick);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.minibricks, 8, 0), "XXX", "XCX", "XXX", Character.valueOf('X'), new ItemStack(VanillaBlocks.minibricks, 1, 3), Character.valueOf('C'), VanillaItemsOther.rupeeIngot);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.minibricks, 8, 1), "XXX", "XCX", "XXX", Character.valueOf('X'), new ItemStack(VanillaBlocks.minibricks, 1, 3), Character.valueOf('C'), VanillaItemsOther.realmiteIngot);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.minibricks, 8, 2), "XXX", "XCX", "XXX", Character.valueOf('X'), new ItemStack(VanillaBlocks.minibricks, 1, 3), Character.valueOf('C'), VanillaItemsOther.arlemiteIngot);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.minibricks, 8, 4), "XXX", "XCX", "XXX", Character.valueOf('X'), new ItemStack(VanillaBlocks.minibricks, 1, 3), Character.valueOf('C'), VanillaItemsOther.bloodgem);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.minibricks, 8, 5), "XXX", "XCX", "XXX", Character.valueOf('X'), new ItemStack(VanillaBlocks.minibricks, 1, 3), Character.valueOf('C'), VanillaItemsOther.netheriteIngot);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.minibricks, 8, 6), "XXX", "XCX", "XXX", Character.valueOf('X'), new ItemStack(VanillaBlocks.minibricks, 1, 3), Character.valueOf('C'), Blocks.bedrock);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.darkStone, 10), Blocks.obsidian, Blocks.glowstone);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.lamp2, 1, 10), "xxx", "xyx", "xzx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), VanillaItemsOther.rupeeIngot, Character.valueOf('z'), Blocks.glowstone);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.lamp1, 1, 0), "xxx", "xyx", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), Items.water_bucket);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.lamp1, 1, 2), "xxx", "xyx", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), Items.blaze_rod);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.lamp1, 1, 6), "xxx", "zyz", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), Items.lava_bucket, Character.valueOf('z'), Blocks.gold_block);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.lamp1, 1, 1), "xxx", "xyx", "xzx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), VanillaItemsOther.arlemiteIngot, Character.valueOf('z'), Blocks.glowstone);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.lamp1, 1, 8), "xxx", "xyx", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), Items.ender_eye);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.lamp2, 1, 2), "xxx", "xyx", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), VanillaItemsOther.krakenSkin);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.lamp2, 1, 4), "xxx", "xyx", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), Items.lava_bucket);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.lamp2, 1, 5), "xxx", "xyx", "xxx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), Items.milk_bucket);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.lamp2, 1, 8), "xxx", "xyx", "xzx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), VanillaItemsOther.realmiteIngot, Character.valueOf('z'), Blocks.glowstone);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.lamp1, 1, 4), "xxx", "xyx", "xzx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), Items.diamond, Character.valueOf('z'), Blocks.glowstone);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.lamp1, 1, 10), "xxx", "xyx", "xzx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), Items.gold_ingot, Character.valueOf('z'), Blocks.glowstone);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.lamp2, 1, 9), "xxx", "xyx", "xzx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), Items.redstone, Character.valueOf('z'), Blocks.glowstone);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.lamp2, 1, 3), "xxx", "xyx", "xzx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), new ItemStack(Items.dye, 1, 4), Character.valueOf('z'), Blocks.glowstone);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.lamp2, 1, 7), "xxx", "xyx", "xzx", Character.valueOf('x'), Items.iron_ingot, Character.valueOf('y'), VanillaItemsOther.netheriteIngot, Character.valueOf('z'), Blocks.glowstone);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.lamp1, 1, 7), "xxx", "xyx", "xxx", Character.valueOf('y'), TwilightItemsOther.edenFragments, Character.valueOf('x'), Items.iron_ingot);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.lamp1, 2, 5), Blocks.glowstone, VanillaItemsOther.divineStone);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.lamp2, 2, 1), Blocks.glowstone, VanillaItemsOther.jungleStone);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.lamp2, 2, 0), Blocks.glowstone, IceikaItems.iceStone);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.lamp1, 2, 9), Blocks.glowstone, VanillaItemsOther.enderStone);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.lamp2, 2, 6), Blocks.glowstone, VanillaItemsOther.moltenStone);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.lamp1, 2, 3), Blocks.glowstone, VanillaItemsOther.bluefireStone);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.lamp2, 2, 11), Blocks.glowstone, VanillaItemsOther.terranStone);
        VanillaRecipeHelper.addRecipe(new ItemStack(ArcanaBlocks.stainedGlass, 1), "y  ", " x ", "   ", Character.valueOf('x'), Blocks.glass, Character.valueOf('y'), ArcanaItems.marsine);
        VanillaRecipeHelper.addRecipe(new ItemStack(ArcanaBlocks.stainedGlass2, 1), " y ", " x ", "   ", Character.valueOf('x'), Blocks.glass, Character.valueOf('y'), ArcanaItems.marsine);
        VanillaRecipeHelper.addRecipe(new ItemStack(ArcanaBlocks.stainedGlass3, 1), "  y", " x ", "   ", Character.valueOf('x'), Blocks.glass, Character.valueOf('y'), ArcanaItems.marsine);
        VanillaRecipeHelper.addRecipe(new ItemStack(ArcanaBlocks.stainedGlass4, 1), "   ", "yx ", "   ", Character.valueOf('x'), Blocks.glass, Character.valueOf('y'), ArcanaItems.marsine);
        VanillaRecipeHelper.addRecipe(new ItemStack(ArcanaBlocks.stainedGlass5, 1), "   ", " xy", "   ", Character.valueOf('x'), Blocks.glass, Character.valueOf('y'), ArcanaItems.marsine);
        VanillaRecipeHelper.addRecipe(new ItemStack(ArcanaBlocks.stainedGlass6, 1), "   ", " x ", "y  ", Character.valueOf('x'), Blocks.glass, Character.valueOf('y'), ArcanaItems.marsine);
        VanillaRecipeHelper.addRecipe(new ItemStack(ArcanaBlocks.stainedGlass7, 1), "   ", " x ", " y ", Character.valueOf('x'), Blocks.glass, Character.valueOf('y'), ArcanaItems.marsine);
        VanillaRecipeHelper.addRecipe(new ItemStack(ArcanaBlocks.stainedGlass8, 1), "   ", " x ", "  y", Character.valueOf('x'), Blocks.glass, Character.valueOf('y'), ArcanaItems.marsine);
        VanillaRecipeHelper.addRecipe(IS.bedrock, "OOO", "OBO", " OO", Character.valueOf('O'), Blocks.obsidian, Character.valueOf('B'), VanillaBlocks.rupeeBlock);
        VanillaRecipeHelper.addSmelting(VanillaBlocks.realmiteOre, VanillaItemsOther.realmiteIngot, 0.7f);
        VanillaRecipeHelper.addSmelting(VanillaBlocks.arlemiteOre, VanillaItemsOther.arlemiteIngot, 1.0f);
        VanillaRecipeHelper.addSmelting(VanillaBlocks.rupeeOre, VanillaItemsOther.rupeeIngot, 1.0f);
        VanillaRecipeHelper.addSmelting(VanillaBlocks.netheriteOre, VanillaItemsOther.netheriteIngot, 1.1f);
        VanillaRecipeHelper.addSmelting(VanillaBlocks.bloodgemOre, VanillaItemsOther.bloodgem, 1.2f);
        VanillaRecipeHelper.addSmelting(VanillaItemsOther.pureAquaticPellets, VanillaItemsOther.aquaticIngot, 0.6f);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsOther.hellstoneIngot, VanillaItemsOther.shadowBar, VanillaItemsOther.netheriteChunk);
        VanillaRecipeHelper.addShapelessRecipe(IS.arlemiteIngot, VanillaBlocks.arlemiteBlock);
        VanillaRecipeHelper.addShapelessRecipe(IS.rupeeIngot, VanillaBlocks.rupeeBlock);
        VanillaRecipeHelper.addShapelessRecipe(IS.realIngot, VanillaBlocks.realmiteBlock);
        VanillaRecipeHelper.addShapelessRecipe(IS.netherIngot, VanillaBlocks.netheriteBlock);
        VanillaRecipeHelper.addShapelessRecipe(IS.bloodgem, VanillaBlocks.bloodgemBlock);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsOther.shadowBar, VanillaItemsOther.rupeeIngot, VanillaItemsOther.arlemiteIngot);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaItemsOther.shadowCoins, 6), VanillaItemsOther.shadowStone);
        VanillaRecipeHelper.addSmelting(ItemsFood.rawEmpoweredMeat, ItemsFood.empoweredMeat, 1.0f);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.pureAquaticPellets, "PPP", "PPP", "PPP", Character.valueOf('P'), VanillaItemsOther.aquaticPellets);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.aquaBall, "wsw", "wkw", "wsw", Character.valueOf('w'), Items.water_bucket, Character.valueOf('s'), Items.slime_ball, Character.valueOf('k'), VanillaItemsOther.krakenSkin);
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsOther.aquaticBlazeRod, VanillaItemsOther.aquaBall, Items.blaze_rod);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.corruptedStone, "III", "III", "III", Character.valueOf('I'), VanillaItemsOther.corruptedShards);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.jungleStone, "III", "III", "III", Character.valueOf('I'), VanillaItemsOther.jungleShards);
        VanillaRecipeHelper.addRecipe(IceikaItems.iceStone, "III", "III", "III", Character.valueOf('I'), IceikaItems.iceShards);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.moltenStone, "III", "III", "III", Character.valueOf('I'), VanillaItemsOther.moltenShards);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.divineStone, "III", "III", "III", Character.valueOf('I'), VanillaItemsOther.divineShards);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.enderStone, "III", "III", "III", Character.valueOf('I'), VanillaItemsOther.enderShards);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.terranStone, "III", "III", "III", Character.valueOf('I'), VanillaItemsOther.terranShards);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.shadowStone, "II", "II", Character.valueOf('I'), VanillaItemsOther.shadowBar);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.legendaryEnderEye, "III", "III", "III", Character.valueOf('I'), VanillaItemsOther.enderStone);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.krakenScale, "K K", "K K", "KKK", Character.valueOf('K'), new ItemStack(Items.dye, 1, 0));
        VanillaRecipeHelper.addShapelessRecipe(VanillaItemsOther.krakenSkin, VanillaItemsOther.krakenScale, VanillaItemsOther.krakenScale);
        VanillaRecipeHelper.addShapelessRecipe(IS.bacon, Items.porkchop);
        VanillaRecipeHelper.addRecipe(IS.cheese, "MMM", "MMM", "MMM", Character.valueOf('M'), Items.milk_bucket);
        VanillaRecipeHelper.addSmelting(Items.egg, ItemsFood.boiledEgg, 0.3f);
        VanillaRecipeHelper.addSmelting(Blocks.pumpkin, ItemsFood.hotPie, 0.3f);
        VanillaRecipeHelper.addShapelessRecipe(ItemsFood.advMushroomStew, ItemsFood.whiteMushroom, Items.mushroom_stew);
        VanillaRecipeHelper.addShapelessRecipe(ItemsFood.chickenDinner, ItemsFood.advMushroomStew, Items.cooked_chicken, Items.bread);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.divinePlanks, 4), VanillaBlocks.divineWood);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.altarOfCorruption, "sss", "ddd", "ddd", Character.valueOf('s'), VanillaItemsOther.corruptedStone, Character.valueOf('d'), VanillaBlocks.darkStone);
        VanillaRecipeHelper.addRecipe(IceikaBlocks.coalstoneStairs, "c  ", "cc ", "ccc", Character.valueOf('c'), IceikaBlocks.coalstone);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.lightFenceRed, "   ", "III", "III", Character.valueOf('I'), Items.redstone);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.lightFenceGreen, "   ", "III", "III", Character.valueOf('I'), new ItemStack(Items.dye, 1, 2));
        VanillaRecipeHelper.addRecipe(VanillaBlocks.lightFenceBlue, "   ", "III", "III", Character.valueOf('I'), new ItemStack(Items.dye, 1, 4));
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.teleportationCrystal, " E ", "EDE", " E ", Character.valueOf('E'), Items.ender_pearl, Character.valueOf('D'), Items.diamond);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.hellspiderPumpkin, "MMM", "MPM", "MMM", Character.valueOf('M'), VanillaItemsOther.moltenShards, Character.valueOf('P'), Blocks.pumpkin);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.frostPumpkin, "MMM", "MPM", "MMM", Character.valueOf('M'), IceikaItems.iceStone, Character.valueOf('P'), Blocks.pumpkin);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.jungleSpiderPumpkin, "MMM", "MPM", "MMM", Character.valueOf('M'), VanillaItemsOther.jungleShards, Character.valueOf('P'), Blocks.pumpkin);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.blazePumpkin, "MMM", "MPM", "MMM", Character.valueOf('M'), Items.blaze_rod, Character.valueOf('P'), Blocks.pumpkin);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.enderWatcherPumpkin, "MMM", "MPM", "MMM", Character.valueOf('M'), VanillaItemsOther.enderShards, Character.valueOf('P'), Blocks.pumpkin);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.glaconPumpkin, "MMM", "MPM", "MMM", Character.valueOf('M'), IceikaItems.iceShards, Character.valueOf('P'), Blocks.pumpkin);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.zombiePumpkin, "MMM", "MPM", "MMM", Character.valueOf('M'), Items.rotten_flesh, Character.valueOf('P'), Blocks.pumpkin);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.creeperPumpkin, "MMM", "MPM", "MMM", Character.valueOf('M'), Items.gunpowder, Character.valueOf('P'), Blocks.pumpkin);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.cyclopsPumpkin, "MMM", "MPM", "MMM", Character.valueOf('M'), Items.gold_ingot, Character.valueOf('P'), Blocks.pumpkin);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.enderPumpkin, "MMM", "MPM", "MMM", Character.valueOf('M'), Items.ender_pearl, Character.valueOf('P'), Blocks.pumpkin);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.ghastPumpkin, "MMM", "MPM", "MMM", Character.valueOf('M'), Items.ghast_tear, Character.valueOf('P'), Blocks.pumpkin);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.skeletonPumpkin, "MMM", "MPM", "MMM", Character.valueOf('M'), Items.bone, Character.valueOf('P'), Blocks.pumpkin);
        VanillaRecipeHelper.addRecipe(VanillaBlocks.spiderPumpkin, "MMM", "MPM", "MMM", Character.valueOf('M'), Items.string, Character.valueOf('P'), Blocks.pumpkin);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaBlocks.rainbowWool, 4), new ItemStack(Blocks.wool, 1, 1), new ItemStack(Blocks.wool, 1, 14), new ItemStack(Blocks.wool, 1, 4), new ItemStack(Blocks.wool, 1, 5), new ItemStack(Blocks.wool, 1, 9), new ItemStack(Blocks.wool, 1, 11), new ItemStack(Blocks.wool, 1, 10));
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.blueStone, 8), "GGG", "GLG", "GGG", Character.valueOf('G'), Blocks.glowstone, Character.valueOf('L'), new ItemStack(Items.dye, 1, 4));
        VanillaRecipeHelper.addOredictRecipe(new ItemStack(VanillaBlocks.crate, 4), "xxx", "y y", "xxx", Character.valueOf('x'), "plankWood", Character.valueOf('y'), "logWood");
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.plankDesign, 4), "xyx", "yxy", "xyx", Character.valueOf('x'), new ItemStack(Blocks.planks, 1, 0), Character.valueOf('y'), new ItemStack(Blocks.planks, 1, 1));
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.skeletonTorch, 4), "x", "y", Character.valueOf('y'), Items.bone, Character.valueOf('x'), Items.coal);
        VanillaRecipeHelper.addOredictRecipe(new ItemStack(VanillaBlocks.aquaTorch, 4), "x", "y", Character.valueOf('y'), "stickWood", Character.valueOf('x'), VanillaItemsOther.aquaticBlazeRod);
        VanillaRecipeHelper.addOredictRecipe(new ItemStack(TwilightBlocks.edenTorch, 4), "x", "y", Character.valueOf('y'), "stickWood", Character.valueOf('x'), TwilightItemsOther.edenFragments);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.spikeBlock), "x x", " x ", "x x", Character.valueOf('x'), Items.iron_ingot);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.hotSpikeBlock), "x x", " x ", "x x", Character.valueOf('x'), VanillaItemsOther.netheriteIngot);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsOther.whiteChunk), " x ", "x x", " x ", Character.valueOf('x'), VanillaItemsOther.whiteShard);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsOther.whiteCrystal), " x ", "x x", " x ", Character.valueOf('x'), VanillaItemsOther.whiteChunk);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsOther.redChunk), " x ", "x x", " x ", Character.valueOf('x'), VanillaItemsOther.redShard);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsOther.redCrystal), " x ", "x x", " x ", Character.valueOf('x'), VanillaItemsOther.redChunk);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsOther.greenChunk), " x ", "x x", " x ", Character.valueOf('x'), VanillaItemsOther.greenShard);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsOther.greenCrystal), " x ", "x x", " x ", Character.valueOf('x'), VanillaItemsOther.greenChunk);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsOther.blueChunk), " x ", "x x", " x ", Character.valueOf('x'), VanillaItemsOther.blueShard);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsOther.blueCrystal), " x ", "x x", " x ", Character.valueOf('x'), VanillaItemsOther.blueChunk);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsOther.godlyCrystal), " r ", "g b", " w ", Character.valueOf('b'), VanillaItemsOther.blueCrystal, Character.valueOf('r'), VanillaItemsOther.redCrystal, Character.valueOf('g'), VanillaItemsOther.greenCrystal, Character.valueOf('w'), VanillaItemsOther.whiteCrystal);
        VanillaRecipeHelper.addRecipe(new ItemStack(VetheaItems.karosRockmaul), " g ", "xsx", " x ", Character.valueOf('x'), VanillaItemsOther.netheriumShards, Character.valueOf('s'), VanillaItemsOther.ancientSword, Character.valueOf('g'), VanillaItemsOther.godlyCrystal);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsWeapons.impulseSword), " s ", "sxs", " s ", Character.valueOf('x'), TwilightItemsWeapons.haliteBlade, Character.valueOf('s'), VanillaItemsOther.greenChunk);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsWeapons.ironDagger), "   ", " i ", " s ", Character.valueOf('i'), Items.iron_ingot, Character.valueOf('s'), Items.stick);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsWeapons.poisonDagger), "   ", " s ", " d ", Character.valueOf('s'), VanillaItemsOther.tarnishedDagger, Character.valueOf('d'), VanillaItemsOther.poisonScroll);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsWeapons.regenerationDagger), "   ", " s ", " d ", Character.valueOf('s'), VanillaItemsOther.tarnishedDagger, Character.valueOf('d'), VanillaItemsOther.regenerationScroll);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsWeapons.magmaDagger), "   ", " s ", " d ", Character.valueOf('s'), VanillaItemsOther.tarnishedDagger, Character.valueOf('d'), VanillaItemsOther.fireScroll);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsWeapons.griefDagger), "   ", " s ", " d ", Character.valueOf('s'), VanillaItemsOther.tarnishedDagger, Character.valueOf('d'), VanillaItemsOther.witherScroll);
        VanillaRecipeHelper.addRecipe(new ItemStack(TwilightItemsArmor.arcaniumHelmet), "   ", "ccc", "c c", Character.valueOf('c'), ArcanaItems.arcanaCrystall);
        VanillaRecipeHelper.addRecipe(new ItemStack(TwilightItemsArmor.arcaniumChestplate), "c c", "ccc", "ccc", Character.valueOf('c'), ArcanaItems.arcanaCrystall);
        VanillaRecipeHelper.addRecipe(new ItemStack(TwilightItemsArmor.arcaniumLeggings), "ccc", "c c", "c c", Character.valueOf('c'), ArcanaItems.arcanaCrystall);
        VanillaRecipeHelper.addRecipe(new ItemStack(TwilightItemsArmor.arcaniumBoots), "   ", "c c", "c c", Character.valueOf('c'), ArcanaItems.arcanaCrystall);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsArmor.archerHelmet), " c ", "cac", " c ", Character.valueOf('c'), VanillaItemsOther.whiteChunk, Character.valueOf('a'), VanillaItemsArmor.corruptedHelmet);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsArmor.archerBody), " c ", "cac", " c ", Character.valueOf('c'), VanillaItemsOther.whiteChunk, Character.valueOf('a'), VanillaItemsArmor.corruptedBody);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsArmor.archerLegs), " c ", "cac", " c ", Character.valueOf('c'), VanillaItemsOther.whiteChunk, Character.valueOf('a'), VanillaItemsArmor.corruptedLegs);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsArmor.archerBoots), " c ", "cac", " c ", Character.valueOf('c'), VanillaItemsOther.whiteChunk, Character.valueOf('a'), VanillaItemsArmor.corruptedBoots);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsOther.tarnishedDagger), "ccc", "cdc", "ccc", Character.valueOf('d'), VanillaItemsWeapons.ironDagger, Character.valueOf('c'), VanillaItemsOther.tarnishedCrystal);
        VanillaRecipeHelper.addRecipe(new ItemStack(TwilightItemsArmor.awakenedBoots), " x ", "xax", " x ", Character.valueOf('a'), TwilightItemsArmor.haliteBoots, Character.valueOf('x'), VanillaItemsOther.godlyCrystal);
        VanillaRecipeHelper.addRecipe(new ItemStack(TwilightItemsArmor.awakenedChestplate), " x ", "xax", " x ", Character.valueOf('a'), TwilightItemsArmor.haliteChestplate, Character.valueOf('x'), VanillaItemsOther.godlyCrystal);
        VanillaRecipeHelper.addRecipe(new ItemStack(TwilightItemsArmor.awakenedLeggings), " x ", "xax", " x ", Character.valueOf('a'), TwilightItemsArmor.haliteLeggings, Character.valueOf('x'), VanillaItemsOther.godlyCrystal);
        VanillaRecipeHelper.addRecipe(new ItemStack(TwilightItemsArmor.awakenedHelmet), " x ", "xax", " x ", Character.valueOf('a'), TwilightItemsArmor.haliteHelmet, Character.valueOf('x'), VanillaItemsOther.godlyCrystal);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsWeapons.godlySword), "xxx", "xax", "xxx", Character.valueOf('a'), VetheaItems.everlight, Character.valueOf('x'), VanillaItemsOther.godlyCrystal);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsWeapons.godlyDagger), "xxx", "xax", "xxx", Character.valueOf('a'), VanillaItemsOther.tarnishedDagger, Character.valueOf('x'), VanillaItemsOther.godlyCrystal);
        VanillaRecipeHelper.addRecipe(new ItemStack((Block)OmegaLevels.levelStation, 1), "sss", "scs", "sss", Character.valueOf('s'), VanillaItemsOther.shadowBar, Character.valueOf('c'), VanillaItemsOther.corruptedStone);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaItemsOther.mushroomSeeds, 4), ItemsFood.whiteMushroom);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(VanillaItemsOther.tomatoSeeds, 4), ItemsFood.tomato);
        VanillaRecipeHelper.addStairRecipe(VanillaBlocks.divinePlanks, VanillaBlocks.divineStairs);
        VanillaRecipeHelper.addSlabRecipe(VanillaBlocks.divinePlanks, VanillaBlocks.divineSlab);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(ArcanaBlocks.eucalyptusPlank, 4), ArcanaBlocks.eucalyptusWood);
        VanillaRecipeHelper.addShapelessRecipe(new ItemStack(IceikaBlocks.frozenPlanks, 4), IceikaBlocks.frozenWood);
        VanillaRecipeHelper.addStairRecipe(IceikaBlocks.frozenPlanks, IceikaBlocks.frozenStairs);
        VanillaRecipeHelper.addSlabRecipe(IceikaBlocks.frozenPlanks, IceikaBlocks.frozenSlab);
        VanillaRecipeHelper.addRecipe(new ItemStack(JourneyItemsOther.boilGem, 1), "CCC", "CCC", "CCC", Character.valueOf('C'), new ItemStack(JourneyItemsOther.boilChunk));
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.blueVane, 4), "CCC", "COC", "CCC", Character.valueOf('C'), new ItemStack(Items.dye, 4), Character.valueOf('O'), Blocks.obsidian);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.redVane, 4), "CCC", "COC", "CCC", Character.valueOf('C'), new ItemStack(Items.dye, 1, 1), Character.valueOf('O'), Blocks.obsidian);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.cyanVane, 4), "CCC", "COC", "CCC", Character.valueOf('C'), new ItemStack(Items.dye, 1, 6), Character.valueOf('O'), Blocks.obsidian);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.purpleVane, 4), "CCC", "COC", "CCC", Character.valueOf('C'), new ItemStack(Items.dye, 1, 5), Character.valueOf('O'), Blocks.obsidian);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.yellowVane, 4), "CCC", "COC", "CCC", Character.valueOf('C'), new ItemStack(Items.dye, 1, 11), Character.valueOf('O'), Blocks.obsidian);
        VanillaRecipeHelper.addRecipe(VetheaItems.moonClock, "III", "ISI", "III", Character.valueOf('I'), ArcanaItems.arcanium, Character.valueOf('S'), Items.clock);
        VanillaRecipeHelper.addRecipe(JourneyItemsOther.gemOfPeculiarSmelting, " I ", "ISI", " I ", Character.valueOf('I'), JourneyItemsOther.celestiumIngot, Character.valueOf('S'), VanillaItemsOther.mysticChunk);
        VanillaRecipeHelper.addRecipe(JourneyItemsOther.netherBeastOrb, "III", "ISI", "III", Character.valueOf('I'), VanillaItemsOther.netherSoul, Character.valueOf('S'), VanillaItemsOther.mysticChunk);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.soulOfRaglok, "III", "ISI", "III", Character.valueOf('I'), VanillaItemsOther.netheriumShards, Character.valueOf('S'), VanillaItemsOther.mysticChunk);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.wreckCore, "III", "ISI", "III", Character.valueOf('I'), IceikaItems.snowflake, Character.valueOf('S'), VanillaItemsOther.mysticChunk);
        VanillaRecipeHelper.addRecipe(VetheaItems.everlight, "III", "ISI", "III", Character.valueOf('I'), VanillaItemsOther.blueShard, Character.valueOf('S'), VetheaItems.karosRockmaul);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.netherSoul, " I ", "III", " I ", Character.valueOf('I'), VanillaItemsOther.netheriumIngot);
        VanillaRecipeHelper.addRecipe(VanillaItemsOther.mystic, "WIW", "ISI", "WIW", Character.valueOf('I'), VanillaItemsOther.mysticChunk, Character.valueOf('S'), VanillaItemsOther.netherSoul, Character.valueOf('W'), JourneyItemsOther.boilGem);
        VanillaRecipeHelper.addRecipe(new ItemStack(SkinItems.awakenedpremBoots), " x ", "xax", " x ", Character.valueOf('a'), TwilightItemsArmor.awakenedBoots, Character.valueOf('x'), VanillaItemsOther.mystic);
        VanillaRecipeHelper.addRecipe(new ItemStack(SkinItems.awakenedpremLeggings), " x ", "xax", " x ", Character.valueOf('a'), TwilightItemsArmor.awakenedLeggings, Character.valueOf('x'), VanillaItemsOther.mystic);
        VanillaRecipeHelper.addRecipe(new ItemStack(SkinItems.awakenedpremChestplate), " x ", "xax", " x ", Character.valueOf('a'), TwilightItemsArmor.awakenedChestplate, Character.valueOf('x'), VanillaItemsOther.mystic);
        VanillaRecipeHelper.addRecipe(new ItemStack(SkinItems.awakenedpremHelmet), " x ", "xax", " x ", Character.valueOf('a'), TwilightItemsArmor.awakenedHelmet, Character.valueOf('x'), VanillaItemsOther.mystic);
        VanillaRecipeHelper.addRecipe(new ItemStack(SkinItems.premfrossivence), " x ", "xax", " x ", Character.valueOf('a'), IceikaItems.frossivence, Character.valueOf('x'), VanillaItemsOther.mystic);
        VanillaRecipeHelper.addRecipe(new ItemStack(SkinItems.celestiumpremSword), " x ", "xax", " x ", Character.valueOf('a'), JourneyItemsWeapon.celestiumSword, Character.valueOf('x'), VanillaItemsOther.mystic);
        VanillaRecipeHelper.addRecipe(new ItemStack(SkinItems.lunaThunderbirdSword), " x ", "xax", " x ", Character.valueOf('a'), VanillaItemsWeapons.lunaSoulSword, Character.valueOf('x'), VanillaItemsOther.mystic);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsOther.teleportStaff), "xzx", " a ", " a ", Character.valueOf('x'), Items.ender_pearl, Character.valueOf('a'), Items.stick, Character.valueOf('z'), VanillaItemsOther.mysticChunk);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsWeapons.arcanaSword), " x ", "www", " a ", Character.valueOf('a'), Items.stick, Character.valueOf('x'), VanillaItemsOther.compressedArcana, Character.valueOf('w'), ArcanaItems.arcanium);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaItemsWeapons.enderFlameSword), " x ", "xxx", " a ", Character.valueOf('a'), Items.stick, Character.valueOf('x'), VanillaItemsOther.mysticSoul);
        VanillaRecipeHelper.addRecipe(new ItemStack(VanillaBlocks.repairBlock), "XLX", "LBL", "XLX", Character.valueOf('X'), JourneyItemsOther.celestiumIngot, Character.valueOf('L'), VanillaItemsOther.shadowBar, Character.valueOf('B'), Blocks.gold_block);
    }
}

