/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.MathHelper
 */
package net.divinerpg.client.render.entity.vethea.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class Dreamwrecker
extends ModelBase {
    ModelRenderer head;
    ModelRenderer bodyt1;
    ModelRenderer rightarmb;
    ModelRenderer leftarmb;
    ModelRenderer rightlegb;
    ModelRenderer leftlegb;
    ModelRenderer bodyt2;
    ModelRenderer rightlegt;
    ModelRenderer leftlegt;
    ModelRenderer body1;
    ModelRenderer body2;
    ModelRenderer bodyb1;
    ModelRenderer bodyb2;
    ModelRenderer rightarmt;
    ModelRenderer leftarmt;
    ModelRenderer rightarmspike1;
    ModelRenderer leftarmspike1;
    ModelRenderer body3;
    ModelRenderer seg1;
    ModelRenderer seg2;
    ModelRenderer seg3;
    ModelRenderer seg4;
    ModelRenderer seg5;
    ModelRenderer seg6;
    ModelRenderer seg7;
    ModelRenderer seg8;
    ModelRenderer seg9;
    ModelRenderer seg10;
    ModelRenderer seg11;
    ModelRenderer seg12;
    ModelRenderer seg13;
    ModelRenderer leftarmm;
    ModelRenderer rightarmm;
    ModelRenderer leftarmspike2;
    ModelRenderer rightarmspike2;
    ModelRenderer leftarmspike3;
    ModelRenderer rightarmspike3;
    ModelRenderer rightarmspike4;
    ModelRenderer leftarmspike4;
    ModelRenderer seg14;
    ModelRenderer seg15;
    ModelRenderer seg16;
    ModelRenderer seg17;
    ModelRenderer seg18;

    public Dreamwrecker() {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.head = new ModelRenderer((ModelBase)this, 0, 0);
        this.head.addBox(-4.0f, -8.0f, -4.0f, 8, 8, 8);
        this.head.setRotationPoint(0.0f, -41.0f, -3.0f);
        this.head.setTextureSize(64, 32);
        this.head.mirror = true;
        this.setRotation(this.head, 0.0f, 0.0f, 0.0f);
        this.bodyt1 = new ModelRenderer((ModelBase)this, 16, 18);
        this.bodyt1.addBox(-4.0f, 0.0f, -2.0f, 8, 6, 4);
        this.bodyt1.setRotationPoint(4.0f, -30.0f, 0.0f);
        this.bodyt1.setTextureSize(64, 32);
        this.bodyt1.mirror = true;
        this.setRotation(this.bodyt1, 0.0f, 0.0f, 0.0f);
        this.rightarmb = new ModelRenderer((ModelBase)this, 48, 8);
        this.rightarmb.addBox(-3.0f, 18.0f, -2.0f, 4, 4, 4);
        this.rightarmb.setRotationPoint(-9.0f, -26.0f, 0.0f);
        this.rightarmb.setTextureSize(64, 32);
        this.rightarmb.mirror = true;
        this.setRotation(this.rightarmb, 0.0f, 0.0f, 0.0f);
        this.leftarmb = new ModelRenderer((ModelBase)this, 48, 8);
        this.leftarmb.addBox(-1.0f, 18.0f, -2.0f, 4, 4, 4);
        this.leftarmb.setRotationPoint(9.0f, -26.0f, 0.0f);
        this.leftarmb.setTextureSize(64, 32);
        this.leftarmb.mirror = true;
        this.setRotation(this.leftarmb, 0.0f, 0.0f, 0.0f);
        this.rightlegb = new ModelRenderer((ModelBase)this, 0, 17);
        this.rightlegb.addBox(-2.0f, 8.0f, -2.0f, 4, 10, 4);
        this.rightlegb.setRotationPoint(-3.0f, 6.0f, 0.0f);
        this.rightlegb.setTextureSize(64, 32);
        this.rightlegb.mirror = true;
        this.setRotation(this.rightlegb, 0.0f, 0.0f, 0.0f);
        this.leftlegb = new ModelRenderer((ModelBase)this, 0, 17);
        this.leftlegb.addBox(-2.0f, 8.0f, -2.0f, 4, 10, 4);
        this.leftlegb.setRotationPoint(3.0f, 6.0f, 0.0f);
        this.leftlegb.setTextureSize(64, 32);
        this.leftlegb.mirror = true;
        this.setRotation(this.leftlegb, 0.0f, 0.0f, 0.0f);
        this.bodyt2 = new ModelRenderer((ModelBase)this, 16, 18);
        this.bodyt2.addBox(-4.0f, 0.0f, -2.0f, 8, 6, 4);
        this.bodyt2.setRotationPoint(-4.0f, -30.0f, 0.0f);
        this.bodyt2.setTextureSize(64, 32);
        this.bodyt2.mirror = true;
        this.setRotation(this.bodyt2, 0.0f, 0.0f, 0.0f);
        this.rightlegt = new ModelRenderer((ModelBase)this, 0, 16);
        this.rightlegt.addBox(-2.0f, 0.0f, -2.0f, 4, 8, 4);
        this.rightlegt.setRotationPoint(-3.0f, 6.0f, 0.0f);
        this.rightlegt.setTextureSize(64, 32);
        this.rightlegt.mirror = true;
        this.setRotation(this.rightlegt, 0.0f, 0.0f, 0.0f);
        this.leftlegt = new ModelRenderer((ModelBase)this, 0, 16);
        this.leftlegt.addBox(-2.0f, 0.0f, -2.0f, 4, 8, 4);
        this.leftlegt.setRotationPoint(3.0f, 6.0f, 0.0f);
        this.leftlegt.setTextureSize(64, 32);
        this.leftlegt.mirror = true;
        this.setRotation(this.leftlegt, 0.0f, 0.0f, 0.0f);
        this.body1 = new ModelRenderer((ModelBase)this, 16, 18);
        this.body1.addBox(-4.0f, 0.0f, -2.0f, 6, 8, 4);
        this.body1.setRotationPoint(1.0f, -8.0f, 0.0f);
        this.body1.setTextureSize(64, 32);
        this.body1.mirror = true;
        this.setRotation(this.body1, 0.0f, 0.0f, 0.0f);
        this.body2 = new ModelRenderer((ModelBase)this, 16, 18);
        this.body2.addBox(-4.0f, 0.0f, -2.0f, 6, 8, 4);
        this.body2.setRotationPoint(1.0f, -16.0f, 0.0f);
        this.body2.setTextureSize(64, 32);
        this.body2.mirror = true;
        this.setRotation(this.body2, 0.0f, 0.0f, 0.0f);
        this.bodyb1 = new ModelRenderer((ModelBase)this, 16, 18);
        this.bodyb1.addBox(-4.0f, 0.0f, -2.0f, 7, 6, 4);
        this.bodyb1.setRotationPoint(4.0f, 0.0f, 0.0f);
        this.bodyb1.setTextureSize(64, 32);
        this.bodyb1.mirror = true;
        this.setRotation(this.bodyb1, 0.0f, 0.0f, 0.0f);
        this.bodyb2 = new ModelRenderer((ModelBase)this, 16, 18);
        this.bodyb2.addBox(-4.0f, 0.0f, -2.0f, 7, 6, 4);
        this.bodyb2.setRotationPoint(-3.0f, 0.0f, 0.0f);
        this.bodyb2.setTextureSize(64, 32);
        this.bodyb2.mirror = true;
        this.setRotation(this.bodyb2, 0.0f, 0.0f, 0.0f);
        this.rightarmt = new ModelRenderer((ModelBase)this, 40, 16);
        this.rightarmt.addBox(-3.0f, -2.0f, -2.0f, 4, 12, 4);
        this.rightarmt.setRotationPoint(-9.0f, -26.0f, 0.0f);
        this.rightarmt.setTextureSize(64, 32);
        this.rightarmt.mirror = true;
        this.setRotation(this.rightarmt, 0.0f, 0.0f, 0.0f);
        this.leftarmt = new ModelRenderer((ModelBase)this, 40, 16);
        this.leftarmt.addBox(-1.0f, -2.0f, -2.0f, 4, 12, 4);
        this.leftarmt.setRotationPoint(9.0f, -26.0f, 0.0f);
        this.leftarmt.setTextureSize(64, 32);
        this.leftarmt.mirror = true;
        this.setRotation(this.leftarmt, 0.0f, 0.0f, 0.0f);
        this.rightarmspike1 = new ModelRenderer((ModelBase)this, 0, 17);
        this.rightarmspike1.addBox(1.0f, 21.0f, 0.0f, 1, 1, 11);
        this.rightarmspike1.setRotationPoint(-9.0f, -26.0f, 0.0f);
        this.rightarmspike1.setTextureSize(64, 32);
        this.rightarmspike1.mirror = true;
        this.setRotation(this.rightarmspike1, 0.0f, 0.0f, 0.0f);
        this.leftarmspike1 = new ModelRenderer((ModelBase)this, 0, 17);
        this.leftarmspike1.addBox(3.0f, 21.0f, 0.0f, 1, 1, 11);
        this.leftarmspike1.setRotationPoint(9.0f, -26.0f, 0.0f);
        this.leftarmspike1.setTextureSize(64, 32);
        this.leftarmspike1.mirror = true;
        this.setRotation(this.leftarmspike1, 0.0f, 0.0f, 0.0f);
        this.body3 = new ModelRenderer((ModelBase)this, 16, 18);
        this.body3.addBox(-4.0f, 0.0f, -2.0f, 6, 8, 4);
        this.body3.setRotationPoint(1.0f, -24.0f, 0.0f);
        this.body3.setTextureSize(64, 32);
        this.body3.mirror = true;
        this.setRotation(this.body3, 0.0f, 0.0f, 0.0f);
        this.seg1 = new ModelRenderer((ModelBase)this, 16, 18);
        this.seg1.addBox(-4.0f, -8.0f, 2.0f, 6, 5, 4);
        this.seg1.setRotationPoint(1.0f, -20.0f, 1.0f);
        this.seg1.setTextureSize(64, 32);
        this.seg1.mirror = true;
        this.setRotation(this.seg1, 0.0f, 0.0f, 0.0f);
        this.seg2 = new ModelRenderer((ModelBase)this, 16, 18);
        this.seg2.addBox(-4.0f, -8.0f, 1.0f, 6, 5, 4);
        this.seg2.setRotationPoint(1.0f, -35.0f, 0.0f);
        this.seg2.setTextureSize(64, 32);
        this.seg2.mirror = true;
        this.setRotation(this.seg2, 0.5235988f, 0.0f, 0.0f);
        this.seg3 = new ModelRenderer((ModelBase)this, 16, 18);
        this.seg3.addBox(-4.0f, -3.0f, 2.0f, 6, 5, 4);
        this.seg3.setRotationPoint(1.0f, -35.0f, 0.0f);
        this.seg3.setTextureSize(64, 32);
        this.seg3.mirror = true;
        this.setRotation(this.seg3, 0.3490659f, 0.0f, 0.0f);
        this.seg4 = new ModelRenderer((ModelBase)this, 16, 18);
        this.seg4.addBox(-4.0f, 2.0f, 2.0f, 6, 5, 4);
        this.seg4.setRotationPoint(1.0f, -35.0f, 0.0f);
        this.seg4.setTextureSize(64, 32);
        this.seg4.mirror = true;
        this.setRotation(this.seg4, 0.1745329f, 0.0f, 0.0f);
        this.seg5 = new ModelRenderer((ModelBase)this, 16, 18);
        this.seg5.addBox(-4.0f, -8.0f, 1.0f, 6, 5, 4);
        this.seg5.setRotationPoint(1.0f, -15.0f, 1.0f);
        this.seg5.setTextureSize(64, 32);
        this.seg5.mirror = true;
        this.setRotation(this.seg5, -0.1745329f, 0.0f, 0.0f);
        this.seg6 = new ModelRenderer((ModelBase)this, 16, 18);
        this.seg6.addBox(-4.0f, -3.0f, 1.0f, 6, 5, 4);
        this.seg6.setRotationPoint(1.0f, -15.0f, 1.0f);
        this.seg6.setTextureSize(64, 32);
        this.seg6.mirror = true;
        this.setRotation(this.seg6, -0.3490659f, 0.0f, 0.0f);
        this.seg7 = new ModelRenderer((ModelBase)this, 42, 2);
        this.seg7.addBox(-5.0f, -9.0f, 6.0f, 3, 2, 4);
        this.seg7.setRotationPoint(9.0f, -33.0f, 0.0f);
        this.seg7.setTextureSize(64, 32);
        this.seg7.mirror = true;
        this.setRotation(this.seg7, 1.047198f, 0.0f, 0.0f);
        this.seg8 = new ModelRenderer((ModelBase)this, 16, 18);
        this.seg8.addBox(-4.0f, 2.0f, 1.0f, 6, 1, 4);
        this.seg8.setRotationPoint(1.0f, -15.0f, 1.0f);
        this.seg8.setTextureSize(64, 32);
        this.seg8.mirror = true;
        this.setRotation(this.seg8, -0.5235988f, 0.0f, 0.0f);
        this.seg9 = new ModelRenderer((ModelBase)this, 36, 0);
        this.seg9.addBox(-5.0f, 2.0f, 0.0f, 8, 2, 6);
        this.seg9.setRotationPoint(1.0f, -15.0f, 1.0f);
        this.seg9.setTextureSize(64, 32);
        this.seg9.mirror = true;
        this.setRotation(this.seg9, -0.6981317f, 0.0f, 0.0f);
        this.seg10 = new ModelRenderer((ModelBase)this, 36, 0);
        this.seg10.addBox(-5.0f, -4.0f, 0.0f, 8, 2, 6);
        this.seg10.setRotationPoint(1.0f, -15.0f, 1.0f);
        this.seg10.setTextureSize(64, 32);
        this.seg10.mirror = true;
        this.setRotation(this.seg10, -0.3490659f, 0.0f, 0.0f);
        this.seg11 = new ModelRenderer((ModelBase)this, 36, 0);
        this.seg11.addBox(-5.0f, -9.0f, 0.0f, 8, 2, 6);
        this.seg11.setRotationPoint(1.0f, -15.0f, 1.0f);
        this.seg11.setTextureSize(64, 32);
        this.seg11.mirror = true;
        this.setRotation(this.seg11, -0.1745329f, 0.0f, 0.0f);
        this.seg12 = new ModelRenderer((ModelBase)this, 36, 0);
        this.seg12.addBox(-5.0f, -9.0f, 0.0f, 8, 2, 6);
        this.seg12.setRotationPoint(1.0f, -20.0f, 2.0f);
        this.seg12.setTextureSize(64, 32);
        this.seg12.mirror = true;
        this.setRotation(this.seg12, 0.0f, 0.0f, 0.0f);
        this.seg13 = new ModelRenderer((ModelBase)this, 36, 0);
        this.seg13.addBox(-5.0f, -9.0f, 0.0f, 8, 2, 6);
        this.seg13.setRotationPoint(1.0f, -26.0f, 3.0f);
        this.seg13.setTextureSize(64, 32);
        this.seg13.mirror = true;
        this.setRotation(this.seg13, 0.1745329f, 0.0f, 0.0f);
        this.leftarmm = new ModelRenderer((ModelBase)this, 40, 20);
        this.leftarmm.addBox(-1.0f, 10.0f, -2.0f, 4, 8, 4);
        this.leftarmm.setRotationPoint(9.0f, -26.0f, 0.0f);
        this.leftarmm.setTextureSize(64, 32);
        this.leftarmm.mirror = true;
        this.setRotation(this.leftarmm, 0.0f, 0.0f, 0.0f);
        this.rightarmm = new ModelRenderer((ModelBase)this, 40, 20);
        this.rightarmm.addBox(-3.0f, 10.0f, -2.0f, 4, 8, 4);
        this.rightarmm.setRotationPoint(-9.0f, -26.0f, 0.0f);
        this.rightarmm.setTextureSize(64, 32);
        this.rightarmm.mirror = true;
        this.setRotation(this.rightarmm, 0.0f, 0.0f, 0.0f);
        this.leftarmspike2 = new ModelRenderer((ModelBase)this, 0, 17);
        this.leftarmspike2.addBox(3.0f, 21.0f, -11.0f, 1, 1, 11);
        this.leftarmspike2.setRotationPoint(9.0f, -26.0f, 0.0f);
        this.leftarmspike2.setTextureSize(64, 32);
        this.leftarmspike2.mirror = true;
        this.setRotation(this.leftarmspike2, 0.0f, 0.0f, 0.0f);
        this.rightarmspike2 = new ModelRenderer((ModelBase)this, 0, 17);
        this.rightarmspike2.addBox(1.0f, 21.0f, -11.0f, 1, 1, 11);
        this.rightarmspike2.setRotationPoint(-9.0f, -26.0f, 0.0f);
        this.rightarmspike2.setTextureSize(64, 32);
        this.rightarmspike2.mirror = true;
        this.setRotation(this.rightarmspike2, 0.0f, 0.0f, 0.0f);
        this.leftarmspike3 = new ModelRenderer((ModelBase)this, 0, 17);
        this.leftarmspike3.addBox(-2.0f, 21.0f, 0.0f, 1, 1, 11);
        this.leftarmspike3.setRotationPoint(9.0f, -26.0f, 0.0f);
        this.leftarmspike3.setTextureSize(64, 32);
        this.leftarmspike3.mirror = true;
        this.setRotation(this.leftarmspike3, 0.0f, 0.0f, 0.0f);
        this.rightarmspike3 = new ModelRenderer((ModelBase)this, 0, 17);
        this.rightarmspike3.addBox(-4.0f, 21.0f, 0.0f, 1, 1, 11);
        this.rightarmspike3.setRotationPoint(-9.0f, -26.0f, 0.0f);
        this.rightarmspike3.setTextureSize(64, 32);
        this.rightarmspike3.mirror = true;
        this.setRotation(this.rightarmspike3, 0.0f, 0.0f, 0.0f);
        this.rightarmspike4 = new ModelRenderer((ModelBase)this, 0, 17);
        this.rightarmspike4.addBox(-4.0f, 21.0f, -11.0f, 1, 1, 11);
        this.rightarmspike4.setRotationPoint(-9.0f, -26.0f, 0.0f);
        this.rightarmspike4.setTextureSize(64, 32);
        this.rightarmspike4.mirror = true;
        this.setRotation(this.rightarmspike4, 0.0f, 0.0f, 0.0f);
        this.leftarmspike4 = new ModelRenderer((ModelBase)this, 0, 17);
        this.leftarmspike4.addBox(-2.0f, 21.0f, -11.0f, 1, 1, 11);
        this.leftarmspike4.setRotationPoint(9.0f, -26.0f, 0.0f);
        this.leftarmspike4.setTextureSize(64, 32);
        this.leftarmspike4.mirror = true;
        this.setRotation(this.leftarmspike4, 0.0f, 0.0f, 0.0f);
        this.seg14 = new ModelRenderer((ModelBase)this, 36, 0);
        this.seg14.addBox(-5.0f, 0.0f, 0.0f, 8, 2, 6);
        this.seg14.setRotationPoint(1.0f, -15.0f, 1.0f);
        this.seg14.setTextureSize(64, 32);
        this.seg14.mirror = true;
        this.setRotation(this.seg14, -0.5235988f, 0.0f, 0.0f);
        this.seg15 = new ModelRenderer((ModelBase)this, 36, 0);
        this.seg15.addBox(-5.0f, -9.0f, 0.0f, 8, 2, 6);
        this.seg15.setRotationPoint(1.0f, -31.0f, 2.0f);
        this.seg15.setTextureSize(64, 32);
        this.seg15.mirror = true;
        this.setRotation(this.seg15, 0.3490659f, 0.0f, 0.0f);
        this.seg16 = new ModelRenderer((ModelBase)this, 42, 2);
        this.seg16.addBox(-5.0f, -9.0f, 6.0f, 3, 2, 4);
        this.seg16.setRotationPoint(-2.0f, -33.0f, 0.0f);
        this.seg16.setTextureSize(64, 32);
        this.seg16.mirror = true;
        this.setRotation(this.seg16, 1.047198f, 0.0f, 0.0f);
        this.seg17 = new ModelRenderer((ModelBase)this, 36, 0);
        this.seg17.addBox(-5.0f, -9.0f, 0.0f, 2, 2, 6);
        this.seg17.setRotationPoint(9.0f, -33.0f, 0.0f);
        this.seg17.setTextureSize(64, 32);
        this.seg17.mirror = true;
        this.setRotation(this.seg17, 1.047198f, 0.0f, 0.0f);
        this.seg18 = new ModelRenderer((ModelBase)this, 36, 0);
        this.seg18.addBox(-5.0f, -9.0f, 0.0f, 2, 2, 6);
        this.seg18.setRotationPoint(-1.0f, -33.0f, 0.0f);
        this.seg18.setTextureSize(64, 32);
        this.seg18.mirror = true;
        this.setRotation(this.seg18, 1.047198f, 0.0f, 0.0f);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5);
        this.head.render(f5);
        this.bodyt1.render(f5);
        this.rightarmb.render(f5);
        this.leftarmb.render(f5);
        this.rightlegb.render(f5);
        this.leftlegb.render(f5);
        this.bodyt2.render(f5);
        this.rightlegt.render(f5);
        this.leftlegt.render(f5);
        this.body1.render(f5);
        this.body2.render(f5);
        this.bodyb1.render(f5);
        this.bodyb2.render(f5);
        this.rightarmt.render(f5);
        this.leftarmt.render(f5);
        this.rightarmspike1.render(f5);
        this.leftarmspike1.render(f5);
        this.body3.render(f5);
        this.seg1.render(f5);
        this.seg2.render(f5);
        this.seg3.render(f5);
        this.seg4.render(f5);
        this.seg5.render(f5);
        this.seg6.render(f5);
        this.seg7.render(f5);
        this.seg8.render(f5);
        this.seg9.render(f5);
        this.seg10.render(f5);
        this.seg11.render(f5);
        this.seg12.render(f5);
        this.seg13.render(f5);
        this.leftarmm.render(f5);
        this.rightarmm.render(f5);
        this.leftarmspike2.render(f5);
        this.rightarmspike2.render(f5);
        this.leftarmspike3.render(f5);
        this.rightarmspike3.render(f5);
        this.rightarmspike4.render(f5);
        this.leftarmspike4.render(f5);
        this.seg14.render(f5);
        this.seg15.render(f5);
        this.seg16.render(f5);
        this.seg17.render(f5);
        this.seg18.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
        this.leftlegt.rotateAngleX = MathHelper.cos((float)(f * 0.6662f)) * 1.4f * f1;
        this.leftlegb.rotateAngleX = MathHelper.cos((float)(f * 0.6662f)) * 1.4f * f1;
        this.rightlegt.rotateAngleX = MathHelper.cos((float)(f * 0.6662f + (float)Math.PI)) * 1.4f * f1;
        this.rightlegb.rotateAngleX = MathHelper.cos((float)(f * 0.6662f + (float)Math.PI)) * 1.4f * f1;
        this.rightarmt.rotateAngleX = MathHelper.cos((float)(f * 0.6662f + (float)Math.PI)) * 2.0f * f1 * 0.5f;
        this.rightarmm.rotateAngleX = MathHelper.cos((float)(f * 0.6662f + (float)Math.PI)) * 2.0f * f1 * 0.5f;
        this.rightarmb.rotateAngleX = MathHelper.cos((float)(f * 0.6662f + (float)Math.PI)) * 2.0f * f1 * 0.5f;
        this.rightarmspike1.rotateAngleX = MathHelper.cos((float)(f * 0.6662f + (float)Math.PI)) * 2.0f * f1 * 0.5f;
        this.rightarmspike2.rotateAngleX = MathHelper.cos((float)(f * 0.6662f + (float)Math.PI)) * 2.0f * f1 * 0.5f;
        this.rightarmspike3.rotateAngleX = MathHelper.cos((float)(f * 0.6662f + (float)Math.PI)) * 2.0f * f1 * 0.5f;
        this.rightarmspike4.rotateAngleX = MathHelper.cos((float)(f * 0.6662f + (float)Math.PI)) * 2.0f * f1 * 0.5f;
        this.leftarmt.rotateAngleX = MathHelper.cos((float)(f * 0.6662f)) * 2.0f * f1 * 0.5f;
        this.leftarmm.rotateAngleX = MathHelper.cos((float)(f * 0.6662f)) * 2.0f * f1 * 0.5f;
        this.leftarmb.rotateAngleX = MathHelper.cos((float)(f * 0.6662f)) * 2.0f * f1 * 0.5f;
        this.leftarmspike1.rotateAngleX = MathHelper.cos((float)(f * 0.6662f)) * 2.0f * f1 * 0.5f;
        this.leftarmspike2.rotateAngleX = MathHelper.cos((float)(f * 0.6662f)) * 2.0f * f1 * 0.5f;
        this.leftarmspike3.rotateAngleX = MathHelper.cos((float)(f * 0.6662f)) * 2.0f * f1 * 0.5f;
        this.leftarmspike4.rotateAngleX = MathHelper.cos((float)(f * 0.6662f)) * 2.0f * f1 * 0.5f;
    }
}

