/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.block.Block
 */
package net.divinerpg.dimensions.arcana.components;

import java.util.Random;
import net.divinerpg.dimensions.arcana.ChunkPrimer;
import net.divinerpg.dimensions.arcana.components.DungeonComponentBase;
import net.divinerpg.utils.blocks.ArcanaBlocks;
import net.minecraft.block.Block;

public class DungeonCeiling
extends DungeonComponentBase {
    @Override
    public boolean generate(ChunkPrimer chunkPrimer, Random rand, int x, int y, int z) {
        Block dungeonBricks = ArcanaBlocks.degradedBrick;
        chunkPrimer.setBlock(x, y, z, dungeonBricks);
        chunkPrimer.setBlock(x, y, z + 1, dungeonBricks);
        chunkPrimer.setBlock(x, y, z + 2, dungeonBricks);
        chunkPrimer.setBlock(x, y, z + 3, dungeonBricks);
        chunkPrimer.setBlock(x, y, z + 4, dungeonBricks);
        chunkPrimer.setBlock(x, y, z + 5, dungeonBricks);
        chunkPrimer.setBlock(x, y, z + 6, dungeonBricks);
        chunkPrimer.setBlock(x, y, z + 7, dungeonBricks);
        chunkPrimer.setBlock(x, y, z + 8, dungeonBricks);
        chunkPrimer.setBlock(x, y, z + 9, dungeonBricks);
        chunkPrimer.setBlock(x, y, z + 10, dungeonBricks);
        chunkPrimer.setBlock(x, y, z + 11, dungeonBricks);
        chunkPrimer.setBlock(x, y, z + 12, dungeonBricks);
        chunkPrimer.setBlock(x, y, z + 13, dungeonBricks);
        chunkPrimer.setBlock(x, y, z + 14, dungeonBricks);
        chunkPrimer.setBlock(x, y, z + 15, dungeonBricks);
        chunkPrimer.setBlock(x + 1, y, z, dungeonBricks);
        chunkPrimer.setBlock(x + 1, y, z + 1, dungeonBricks);
        chunkPrimer.setBlock(x + 1, y, z + 2, dungeonBricks);
        chunkPrimer.setBlock(x + 1, y, z + 3, dungeonBricks);
        chunkPrimer.setBlock(x + 1, y, z + 4, dungeonBricks);
        chunkPrimer.setBlock(x + 1, y, z + 5, dungeonBricks);
        chunkPrimer.setBlock(x + 1, y, z + 6, dungeonBricks);
        chunkPrimer.setBlock(x + 1, y, z + 7, dungeonBricks);
        chunkPrimer.setBlock(x + 1, y, z + 8, dungeonBricks);
        chunkPrimer.setBlock(x + 1, y, z + 9, dungeonBricks);
        chunkPrimer.setBlock(x + 1, y, z + 10, dungeonBricks);
        chunkPrimer.setBlock(x + 1, y, z + 11, dungeonBricks);
        chunkPrimer.setBlock(x + 1, y, z + 12, dungeonBricks);
        chunkPrimer.setBlock(x + 1, y, z + 13, dungeonBricks);
        chunkPrimer.setBlock(x + 1, y, z + 14, dungeonBricks);
        chunkPrimer.setBlock(x + 1, y, z + 15, dungeonBricks);
        chunkPrimer.setBlock(x + 2, y, z, dungeonBricks);
        chunkPrimer.setBlock(x + 2, y, z + 1, dungeonBricks);
        chunkPrimer.setBlock(x + 2, y, z + 2, dungeonBricks);
        chunkPrimer.setBlock(x + 2, y, z + 3, dungeonBricks);
        chunkPrimer.setBlock(x + 2, y, z + 4, dungeonBricks);
        chunkPrimer.setBlock(x + 2, y, z + 5, dungeonBricks);
        chunkPrimer.setBlock(x + 2, y, z + 6, dungeonBricks);
        chunkPrimer.setBlock(x + 2, y, z + 7, dungeonBricks);
        chunkPrimer.setBlock(x + 2, y, z + 8, dungeonBricks);
        chunkPrimer.setBlock(x + 2, y, z + 9, dungeonBricks);
        chunkPrimer.setBlock(x + 2, y, z + 10, dungeonBricks);
        chunkPrimer.setBlock(x + 2, y, z + 11, dungeonBricks);
        chunkPrimer.setBlock(x + 2, y, z + 12, dungeonBricks);
        chunkPrimer.setBlock(x + 2, y, z + 13, dungeonBricks);
        chunkPrimer.setBlock(x + 2, y, z + 14, dungeonBricks);
        chunkPrimer.setBlock(x + 2, y, z + 15, dungeonBricks);
        chunkPrimer.setBlock(x + 3, y, z, dungeonBricks);
        chunkPrimer.setBlock(x + 3, y, z + 1, dungeonBricks);
        chunkPrimer.setBlock(x + 3, y, z + 2, dungeonBricks);
        chunkPrimer.setBlock(x + 3, y, z + 3, dungeonBricks);
        chunkPrimer.setBlock(x + 3, y, z + 4, dungeonBricks);
        chunkPrimer.setBlock(x + 3, y, z + 5, dungeonBricks);
        chunkPrimer.setBlock(x + 3, y, z + 6, dungeonBricks);
        chunkPrimer.setBlock(x + 3, y, z + 7, dungeonBricks);
        chunkPrimer.setBlock(x + 3, y, z + 8, dungeonBricks);
        chunkPrimer.setBlock(x + 3, y, z + 9, dungeonBricks);
        chunkPrimer.setBlock(x + 3, y, z + 10, dungeonBricks);
        chunkPrimer.setBlock(x + 3, y, z + 11, dungeonBricks);
        chunkPrimer.setBlock(x + 3, y, z + 12, dungeonBricks);
        chunkPrimer.setBlock(x + 3, y, z + 13, dungeonBricks);
        chunkPrimer.setBlock(x + 3, y, z + 14, dungeonBricks);
        chunkPrimer.setBlock(x + 3, y, z + 15, dungeonBricks);
        chunkPrimer.setBlock(x + 4, y, z, dungeonBricks);
        chunkPrimer.setBlock(x + 4, y, z + 1, dungeonBricks);
        chunkPrimer.setBlock(x + 4, y, z + 2, dungeonBricks);
        chunkPrimer.setBlock(x + 4, y, z + 3, dungeonBricks);
        chunkPrimer.setBlock(x + 4, y, z + 4, dungeonBricks);
        chunkPrimer.setBlock(x + 4, y, z + 5, dungeonBricks);
        chunkPrimer.setBlock(x + 4, y, z + 6, dungeonBricks);
        chunkPrimer.setBlock(x + 4, y, z + 7, dungeonBricks);
        chunkPrimer.setBlock(x + 4, y, z + 8, dungeonBricks);
        chunkPrimer.setBlock(x + 4, y, z + 9, dungeonBricks);
        chunkPrimer.setBlock(x + 4, y, z + 10, dungeonBricks);
        chunkPrimer.setBlock(x + 4, y, z + 11, dungeonBricks);
        chunkPrimer.setBlock(x + 4, y, z + 12, dungeonBricks);
        chunkPrimer.setBlock(x + 4, y, z + 13, dungeonBricks);
        chunkPrimer.setBlock(x + 4, y, z + 14, dungeonBricks);
        chunkPrimer.setBlock(x + 4, y, z + 15, dungeonBricks);
        chunkPrimer.setBlock(x + 5, y, z, dungeonBricks);
        chunkPrimer.setBlock(x + 5, y, z + 1, dungeonBricks);
        chunkPrimer.setBlock(x + 5, y, z + 2, dungeonBricks);
        chunkPrimer.setBlock(x + 5, y, z + 3, dungeonBricks);
        chunkPrimer.setBlock(x + 5, y, z + 4, dungeonBricks);
        chunkPrimer.setBlock(x + 5, y, z + 5, dungeonBricks);
        chunkPrimer.setBlock(x + 5, y, z + 6, dungeonBricks);
        chunkPrimer.setBlock(x + 5, y, z + 7, dungeonBricks);
        chunkPrimer.setBlock(x + 5, y, z + 8, dungeonBricks);
        chunkPrimer.setBlock(x + 5, y, z + 9, dungeonBricks);
        chunkPrimer.setBlock(x + 5, y, z + 10, dungeonBricks);
        chunkPrimer.setBlock(x + 5, y, z + 11, dungeonBricks);
        chunkPrimer.setBlock(x + 5, y, z + 12, dungeonBricks);
        chunkPrimer.setBlock(x + 5, y, z + 13, dungeonBricks);
        chunkPrimer.setBlock(x + 5, y, z + 14, dungeonBricks);
        chunkPrimer.setBlock(x + 5, y, z + 15, dungeonBricks);
        chunkPrimer.setBlock(x + 6, y, z, dungeonBricks);
        chunkPrimer.setBlock(x + 6, y, z + 1, dungeonBricks);
        chunkPrimer.setBlock(x + 6, y, z + 2, dungeonBricks);
        chunkPrimer.setBlock(x + 6, y, z + 3, dungeonBricks);
        chunkPrimer.setBlock(x + 6, y, z + 4, dungeonBricks);
        chunkPrimer.setBlock(x + 6, y, z + 5, dungeonBricks);
        chunkPrimer.setBlock(x + 6, y, z + 6, dungeonBricks);
        chunkPrimer.setBlock(x + 6, y, z + 7, dungeonBricks);
        chunkPrimer.setBlock(x + 6, y, z + 8, dungeonBricks);
        chunkPrimer.setBlock(x + 6, y, z + 9, dungeonBricks);
        chunkPrimer.setBlock(x + 6, y, z + 10, dungeonBricks);
        chunkPrimer.setBlock(x + 6, y, z + 11, dungeonBricks);
        chunkPrimer.setBlock(x + 6, y, z + 12, dungeonBricks);
        chunkPrimer.setBlock(x + 6, y, z + 13, dungeonBricks);
        chunkPrimer.setBlock(x + 6, y, z + 14, dungeonBricks);
        chunkPrimer.setBlock(x + 6, y, z + 15, dungeonBricks);
        chunkPrimer.setBlock(x + 7, y, z, dungeonBricks);
        chunkPrimer.setBlock(x + 7, y, z + 1, dungeonBricks);
        chunkPrimer.setBlock(x + 7, y, z + 2, dungeonBricks);
        chunkPrimer.setBlock(x + 7, y, z + 3, dungeonBricks);
        chunkPrimer.setBlock(x + 7, y, z + 4, dungeonBricks);
        chunkPrimer.setBlock(x + 7, y, z + 5, dungeonBricks);
        chunkPrimer.setBlock(x + 7, y, z + 6, dungeonBricks);
        chunkPrimer.setBlock(x + 7, y, z + 7, dungeonBricks);
        chunkPrimer.setBlock(x + 7, y, z + 8, dungeonBricks);
        chunkPrimer.setBlock(x + 7, y, z + 9, dungeonBricks);
        chunkPrimer.setBlock(x + 7, y, z + 10, dungeonBricks);
        chunkPrimer.setBlock(x + 7, y, z + 11, dungeonBricks);
        chunkPrimer.setBlock(x + 7, y, z + 12, dungeonBricks);
        chunkPrimer.setBlock(x + 7, y, z + 13, dungeonBricks);
        chunkPrimer.setBlock(x + 7, y, z + 14, dungeonBricks);
        chunkPrimer.setBlock(x + 7, y, z + 15, dungeonBricks);
        chunkPrimer.setBlock(x + 8, y, z, dungeonBricks);
        chunkPrimer.setBlock(x + 8, y, z + 1, dungeonBricks);
        chunkPrimer.setBlock(x + 8, y, z + 2, dungeonBricks);
        chunkPrimer.setBlock(x + 8, y, z + 3, dungeonBricks);
        chunkPrimer.setBlock(x + 8, y, z + 4, dungeonBricks);
        chunkPrimer.setBlock(x + 8, y, z + 5, dungeonBricks);
        chunkPrimer.setBlock(x + 8, y, z + 6, dungeonBricks);
        chunkPrimer.setBlock(x + 8, y, z + 7, dungeonBricks);
        chunkPrimer.setBlock(x + 8, y, z + 8, dungeonBricks);
        chunkPrimer.setBlock(x + 8, y, z + 9, dungeonBricks);
        chunkPrimer.setBlock(x + 8, y, z + 10, dungeonBricks);
        chunkPrimer.setBlock(x + 8, y, z + 11, dungeonBricks);
        chunkPrimer.setBlock(x + 8, y, z + 12, dungeonBricks);
        chunkPrimer.setBlock(x + 8, y, z + 13, dungeonBricks);
        chunkPrimer.setBlock(x + 8, y, z + 14, dungeonBricks);
        chunkPrimer.setBlock(x + 8, y, z + 15, dungeonBricks);
        chunkPrimer.setBlock(x + 9, y, z, dungeonBricks);
        chunkPrimer.setBlock(x + 9, y, z + 1, dungeonBricks);
        chunkPrimer.setBlock(x + 9, y, z + 2, dungeonBricks);
        chunkPrimer.setBlock(x + 9, y, z + 3, dungeonBricks);
        chunkPrimer.setBlock(x + 9, y, z + 4, dungeonBricks);
        chunkPrimer.setBlock(x + 9, y, z + 5, dungeonBricks);
        chunkPrimer.setBlock(x + 9, y, z + 6, dungeonBricks);
        chunkPrimer.setBlock(x + 9, y, z + 7, dungeonBricks);
        chunkPrimer.setBlock(x + 9, y, z + 8, dungeonBricks);
        chunkPrimer.setBlock(x + 9, y, z + 9, dungeonBricks);
        chunkPrimer.setBlock(x + 9, y, z + 10, dungeonBricks);
        chunkPrimer.setBlock(x + 9, y, z + 11, dungeonBricks);
        chunkPrimer.setBlock(x + 9, y, z + 12, dungeonBricks);
        chunkPrimer.setBlock(x + 9, y, z + 13, dungeonBricks);
        chunkPrimer.setBlock(x + 9, y, z + 14, dungeonBricks);
        chunkPrimer.setBlock(x + 9, y, z + 15, dungeonBricks);
        chunkPrimer.setBlock(x + 10, y, z, dungeonBricks);
        chunkPrimer.setBlock(x + 10, y, z + 1, dungeonBricks);
        chunkPrimer.setBlock(x + 10, y, z + 2, dungeonBricks);
        chunkPrimer.setBlock(x + 10, y, z + 3, dungeonBricks);
        chunkPrimer.setBlock(x + 10, y, z + 4, dungeonBricks);
        chunkPrimer.setBlock(x + 10, y, z + 5, dungeonBricks);
        chunkPrimer.setBlock(x + 10, y, z + 6, dungeonBricks);
        chunkPrimer.setBlock(x + 10, y, z + 7, dungeonBricks);
        chunkPrimer.setBlock(x + 10, y, z + 8, dungeonBricks);
        chunkPrimer.setBlock(x + 10, y, z + 9, dungeonBricks);
        chunkPrimer.setBlock(x + 10, y, z + 10, dungeonBricks);
        chunkPrimer.setBlock(x + 10, y, z + 11, dungeonBricks);
        chunkPrimer.setBlock(x + 10, y, z + 12, dungeonBricks);
        chunkPrimer.setBlock(x + 10, y, z + 13, dungeonBricks);
        chunkPrimer.setBlock(x + 10, y, z + 14, dungeonBricks);
        chunkPrimer.setBlock(x + 10, y, z + 15, dungeonBricks);
        chunkPrimer.setBlock(x + 11, y, z, dungeonBricks);
        chunkPrimer.setBlock(x + 11, y, z + 1, dungeonBricks);
        chunkPrimer.setBlock(x + 11, y, z + 2, dungeonBricks);
        chunkPrimer.setBlock(x + 11, y, z + 3, dungeonBricks);
        chunkPrimer.setBlock(x + 11, y, z + 4, dungeonBricks);
        chunkPrimer.setBlock(x + 11, y, z + 5, dungeonBricks);
        chunkPrimer.setBlock(x + 11, y, z + 6, dungeonBricks);
        chunkPrimer.setBlock(x + 11, y, z + 7, dungeonBricks);
        chunkPrimer.setBlock(x + 11, y, z + 8, dungeonBricks);
        chunkPrimer.setBlock(x + 11, y, z + 9, dungeonBricks);
        chunkPrimer.setBlock(x + 11, y, z + 10, dungeonBricks);
        chunkPrimer.setBlock(x + 11, y, z + 11, dungeonBricks);
        chunkPrimer.setBlock(x + 11, y, z + 12, dungeonBricks);
        chunkPrimer.setBlock(x + 11, y, z + 13, dungeonBricks);
        chunkPrimer.setBlock(x + 11, y, z + 14, dungeonBricks);
        chunkPrimer.setBlock(x + 11, y, z + 15, dungeonBricks);
        chunkPrimer.setBlock(x + 12, y, z, dungeonBricks);
        chunkPrimer.setBlock(x + 12, y, z + 1, dungeonBricks);
        chunkPrimer.setBlock(x + 12, y, z + 2, dungeonBricks);
        chunkPrimer.setBlock(x + 12, y, z + 3, dungeonBricks);
        chunkPrimer.setBlock(x + 12, y, z + 4, dungeonBricks);
        chunkPrimer.setBlock(x + 12, y, z + 5, dungeonBricks);
        chunkPrimer.setBlock(x + 12, y, z + 6, dungeonBricks);
        chunkPrimer.setBlock(x + 12, y, z + 7, dungeonBricks);
        chunkPrimer.setBlock(x + 12, y, z + 8, dungeonBricks);
        chunkPrimer.setBlock(x + 12, y, z + 9, dungeonBricks);
        chunkPrimer.setBlock(x + 12, y, z + 10, dungeonBricks);
        chunkPrimer.setBlock(x + 12, y, z + 11, dungeonBricks);
        chunkPrimer.setBlock(x + 12, y, z + 12, dungeonBricks);
        chunkPrimer.setBlock(x + 12, y, z + 13, dungeonBricks);
        chunkPrimer.setBlock(x + 12, y, z + 14, dungeonBricks);
        chunkPrimer.setBlock(x + 12, y, z + 15, dungeonBricks);
        chunkPrimer.setBlock(x + 13, y, z, dungeonBricks);
        chunkPrimer.setBlock(x + 13, y, z + 1, dungeonBricks);
        chunkPrimer.setBlock(x + 13, y, z + 2, dungeonBricks);
        chunkPrimer.setBlock(x + 13, y, z + 3, dungeonBricks);
        chunkPrimer.setBlock(x + 13, y, z + 4, dungeonBricks);
        chunkPrimer.setBlock(x + 13, y, z + 5, dungeonBricks);
        chunkPrimer.setBlock(x + 13, y, z + 6, dungeonBricks);
        chunkPrimer.setBlock(x + 13, y, z + 7, dungeonBricks);
        chunkPrimer.setBlock(x + 13, y, z + 8, dungeonBricks);
        chunkPrimer.setBlock(x + 13, y, z + 9, dungeonBricks);
        chunkPrimer.setBlock(x + 13, y, z + 10, dungeonBricks);
        chunkPrimer.setBlock(x + 13, y, z + 11, dungeonBricks);
        chunkPrimer.setBlock(x + 13, y, z + 12, dungeonBricks);
        chunkPrimer.setBlock(x + 13, y, z + 13, dungeonBricks);
        chunkPrimer.setBlock(x + 13, y, z + 14, dungeonBricks);
        chunkPrimer.setBlock(x + 13, y, z + 15, dungeonBricks);
        chunkPrimer.setBlock(x + 14, y, z, dungeonBricks);
        chunkPrimer.setBlock(x + 14, y, z + 1, dungeonBricks);
        chunkPrimer.setBlock(x + 14, y, z + 2, dungeonBricks);
        chunkPrimer.setBlock(x + 14, y, z + 3, dungeonBricks);
        chunkPrimer.setBlock(x + 14, y, z + 4, dungeonBricks);
        chunkPrimer.setBlock(x + 14, y, z + 5, dungeonBricks);
        chunkPrimer.setBlock(x + 14, y, z + 6, dungeonBricks);
        chunkPrimer.setBlock(x + 14, y, z + 7, dungeonBricks);
        chunkPrimer.setBlock(x + 14, y, z + 8, dungeonBricks);
        chunkPrimer.setBlock(x + 14, y, z + 9, dungeonBricks);
        chunkPrimer.setBlock(x + 14, y, z + 10, dungeonBricks);
        chunkPrimer.setBlock(x + 14, y, z + 11, dungeonBricks);
        chunkPrimer.setBlock(x + 14, y, z + 12, dungeonBricks);
        chunkPrimer.setBlock(x + 14, y, z + 13, dungeonBricks);
        chunkPrimer.setBlock(x + 14, y, z + 14, dungeonBricks);
        chunkPrimer.setBlock(x + 14, y, z + 15, dungeonBricks);
        chunkPrimer.setBlock(x + 15, y, z, dungeonBricks);
        chunkPrimer.setBlock(x + 15, y, z + 1, dungeonBricks);
        chunkPrimer.setBlock(x + 15, y, z + 2, dungeonBricks);
        chunkPrimer.setBlock(x + 15, y, z + 3, dungeonBricks);
        chunkPrimer.setBlock(x + 15, y, z + 4, dungeonBricks);
        chunkPrimer.setBlock(x + 15, y, z + 5, dungeonBricks);
        chunkPrimer.setBlock(x + 15, y, z + 6, dungeonBricks);
        chunkPrimer.setBlock(x + 15, y, z + 7, dungeonBricks);
        chunkPrimer.setBlock(x + 15, y, z + 8, dungeonBricks);
        chunkPrimer.setBlock(x + 15, y, z + 9, dungeonBricks);
        chunkPrimer.setBlock(x + 15, y, z + 10, dungeonBricks);
        chunkPrimer.setBlock(x + 15, y, z + 11, dungeonBricks);
        chunkPrimer.setBlock(x + 15, y, z + 12, dungeonBricks);
        chunkPrimer.setBlock(x + 15, y, z + 13, dungeonBricks);
        chunkPrimer.setBlock(x + 15, y, z + 14, dungeonBricks);
        chunkPrimer.setBlock(x + 15, y, z + 15, dungeonBricks);
        return true;
    }
}

